// ÁREA: Fuentes y monitoreo.
//
// REGLA DE ORO: las 4 opciones van del MISMO largo (tolerancia ±5 caracteres).
// Validar con `python check_banco.py`. Ver juego/CONTENIDO.md.

export const FUENTES = [

  // ───────────────────────── SBIR y bordes ─────────────────────────
  {
    id: "fte-sbir-empotrar",
    cat: "SBIR", dif: 2,
    q: "¿Por qué empotrar los monitores (soffit) resuelve el SBIR de esa pared?",
    opts: [
      "Porque la pared absorbe la reflexión que genera el nulo.",
      "Con d→0, el nulo en c/(4d) se va fuera de la banda útil.",
      "Porque aleja el monitor de la posición real de escucha.",
      "Porque elimina los modos axiales del eje frontal largo.",
    ],
    ans: 1,
    why: "El nulo del SBIR está en <code>f = c/(4d)</code>. Si <code>d → 0</code>, <code>f → ∞</code>: el nulo se va de la banda problemática. Además el monitor pasa a radiar en <b>medio espacio (2π)</b> de forma controlada, ganando ~6 dB de acople y una carga predecible en graves. El precio es constructivo: el frente empotrado tiene que ser rígido, masivo y estar bien sellado, o aparecen resonancias nuevas.",
    src: "Toole, Sound Reproduction, §13.2, p. 201 · Newell, Recording Studio Design",
  },
  {
    id: "fte-sbir-peor",
    cat: "SBIR", dif: 3,
    q: "Un monitor a 0,9 m de la pared de atrás. ¿Cuál es el problema, y qué NO lo arregla?",
    opts: [
      "Nulo en ~95 Hz; no lo arregla ni más volumen ni un boost de EQ.",
      "Nulo en ~190 Hz; se arregla con un boost de EQ a esa frecuencia.",
      "No hay problema: 0,9 m es justo la distancia óptima de montaje.",
      "Nulo en ~380 Hz; se corrige alejando al oyente de esa pared.",
    ],
    ans: 0,
    why: "<code>f = c/(4·0,9) ≈ 95 Hz</code>, justo en la zona más comprometida. Lo importante es <b>por qué el EQ no sirve</b>: el nulo es una cancelación por interferencia, y en ese punto el directo y la reflexión se restan casi por completo. Meter boost sube los dos por igual y el nulo sigue ahí — lo único que lográs es quemar excursión y headroom del woofer. Un nulo por interferencia se resuelve con <b>geometría</b> (mover la fuente) o <b>absorción</b> (matar la reflexión), nunca con ganancia.",
    src: "Toole, Sound Reproduction, §13.2, p. 201 · Newell, Recording Studio Design",
  },
  {
    id: "fte-medio-espacio",
    cat: "Carga de bordes", dif: 2,
    q: "Poner un woofer omnidireccional contra una pared (medio espacio)…",
    opts: [
      "Sube el nivel unos 6 dB en la banda donde es omni.",
      "Baja el nivel unos 3 dB por absorción de la pared.",
      "No cambia el nivel, sólo la fase de la radiación.",
      "Sube el nivel unos 20 dB por acople con la pared.",
    ],
    ans: 0,
    why: "La fuente entrega la misma energía en la mitad del ángulo sólido: la presión se duplica, o sea <b>+6 dB</b>. Cada límite adicional suma otros 6 (esquina de dos paredes: +12; triedro: +18). Vale sólo donde el woofer es realmente omnidireccional, o sea en graves — por eso el acople de bordes desbalancea el espectro y hay que compensarlo. Es el mismo mecanismo que hace que un sub en una esquina «rinda más».",
    src: "Toole, Sound Reproduction, cap. 13 · Everest, Master Handbook of Acoustics",
  },
  {
    id: "fte-consola-reflexion",
    cat: "SBIR", dif: 2,
    q: "La reflexión en la superficie de la consola o el escritorio…",
    opts: [
      "Produce un filtro peine en medios, difícil de tratar.",
      "Es despreciable porque la consola es muy pequeña.",
      "Sólo afecta a los graves, por el tamaño del mueble.",
      "Mejora la imagen estéreo al reforzar el directo.",
    ],
    ans: 0,
    why: "Es una reflexión especular con un retardo de pocos ms respecto del directo: interfiere y arma un peine en medios y medios-agudos, justo donde el oído es más sensible. Es de los problemas más subestimados y más difíciles de resolver, porque la superficie tiene que estar ahí. Se mitiga inclinando la consola, bajando la mesa, o eligiendo la altura y el ángulo del monitor para que la reflexión no apunte al oyente.",
    src: "Newell, Recording Studio Design · Toole, Sound Reproduction, §13.2, p. 201",
  },

  // ───────────────────────── Corregibilidad ─────────────────────────
  {
    id: "fte-eq-picos-nulos",
    cat: "Corregibilidad", dif: 3,
    q: "¿Por qué un EQ puede domar un pico modal pero no rellenar un nulo?",
    opts: [
      "Porque los EQ paramétricos sólo tienen filtros de atenuación.",
      "El pico es exceso de energía; el nulo, cancelación espacial.",
      "Porque los nulos no son audibles y no hace falta corregirlos.",
      "Porque el nulo es de fase y el EQ sólo modifica la amplitud.",
    ],
    ans: 1,
    why: "Es la asimetría central de la corregibilidad. Un pico = un modo con Q alto acumulando energía: bajar la excitación a esa frecuencia funciona. Un nulo = dos caminos que llegan en contrafase y se cancelan: si subís la fuente, subís <b>ambos</b> caminos y la resta sigue dando ~cero, sólo consumís headroom. La opción que culpa a la fase es tentadora pero incompleta: un EQ de fase mínima sí toca la fase. El problema real es que la cancelación es <b>espacial</b>, no un defecto de la señal. Se ataca moviendo fuente/oyente, con absorción, o con múltiples subs.",
    src: "Toole, Sound Reproduction, §13.4, p. 239 · Welti & Devantier (2006)",
  },
  {
    id: "fte-eq-fase-minima",
    cat: "Corregibilidad", dif: 3,
    q: "Un EQ de fase mínima corrige bien…",
    opts: [
      "Los picos modales, que son de fase mínima también.",
      "Cualquier nulo, si se aplica suficiente ganancia.",
      "Las reflexiones tempranas de las paredes laterales.",
      "El decaimiento modal, acortando la cola del modo.",
    ],
    ans: 0,
    why: "Un modo resonante <b>es</b> un sistema de fase mínima: su magnitud y su fase están ligadas, así que un filtro de fase mínima inverso corrige las dos a la vez. Ahí el EQ funciona de verdad. Lo que no puede: rellenar nulos (cancelación espacial) ni borrar una reflexión discreta (eso es fase no-mínima, hay un retardo puro de por medio). Sobre la cola: al bajar el pico, el ringing baja en nivel, pero el Q del modo —o sea la duración— no cambia.",
    src: "Toole, Sound Reproduction, §13.4, p. 239 · Low-Frequency Modal Equalization — referencias/",
  },
  {
    id: "fte-multisub",
    cat: "Subwoofers", dif: 3,
    q: "¿Por qué varios subwoofers bien ubicados mejoran la respuesta en graves?",
    opts: [
      "Porque suman SPL y dan mucho más headroom en la banda grave.",
      "Cada sub excita los modos distinto: baja la varianza espacial.",
      "Porque reducen el RT60 de la sala en toda la banda grave.",
      "Porque cancelan entre sí los modos axiales del eje largo.",
    ],
    ans: 1,
    why: "La clave es que la mejora es <b>espacial</b>, no de nivel. Un sub en un nodo de cierto modo no lo excita; otro en un antinodo sí. Combinándolos con posiciones (y a veces ganancia/fase) elegidas, la suma tiene menos desviación punto a punto: la respuesta se parece más entre butacas. Eso es lo que hace que la corrección posterior tenga sentido — un EQ sirve para todos los oyentes sólo si el error es parecido en todos lados. Más SPL es un efecto colateral, no el objetivo.",
    src: "Welti & Devantier (2006) · Toole, Sound Reproduction, §13.3, p. 217",
  },
  {
    id: "fte-curva-objetivo",
    cat: "Corregibilidad", dif: 3,
    q: "¿Por qué la curva objetivo en sala no es plana sino con pendiente?",
    opts: [
      "Porque el oído responde peor a los graves en la sala.",
      "Porque un parlante plano en cámara mide inclinado en sala.",
      "Porque los micrófonos miden mal en la alta frecuencia.",
      "Porque los amplificadores dan menos potencia en agudos.",
    ],
    ans: 1,
    why: "La razón es de directividad, no de gusto. Un parlante bien diseñado radia casi omni en graves y cada vez más directivo en agudos, así que el campo reverberante que se suma en la medición estacionaria aporta <b>mucho más en graves</b> que en agudos. Un parlante plano en cámara anecoica mide, en sala, con una pendiente descendente natural. Perseguir una curva plana medida en sala te obliga a arruinar el directo — que es lo que el oído realmente juzga.",
    src: "Toole, Sound Reproduction, §13.4, p. 239 · Harman target curve",
  },
  {
    id: "fte-cardioide-sub",
    cat: "Subwoofers", dif: 3,
    q: "Un sub cardioide o dipolar, comparado con uno omnidireccional…",
    opts: [
      "Excita menos la sala porque radia menos hacia atrás.",
      "Da más SPL total con la misma potencia de entrada.",
      "Elimina los modos axiales del eje longitudinal largo.",
      "Sólo funciona por encima de la frecuencia de Schroeder.",
    ],
    ans: 0,
    why: "Al radiar con un patrón direccional, entrega menos energía hacia la pared de atrás y excita menos los modos de ese eje: la respuesta queda más limpia sin tocar la sala. El costo es que <b>tira menos SPL</b> por watt (parte de la energía se cancela a propósito) y necesita más excursión o más cajas. Los modos siguen existiendo — sólo que se los alimenta menos.",
    src: "Toole, Sound Reproduction, §13.3, p. 216 · Low frequency sound field control using CABS — referencias/",
  },

  // ───────────────────────── Ubicación y escucha ─────────────────────────
  {
    id: "fte-distancia-critica",
    cat: "Propagación", dif: 2,
    q: "La distancia crítica de una sala es…",
    opts: [
      "La distancia máxima a la que conviene ubicar los monitores.",
      "Donde el campo directo y el reverberante igualan su nivel.",
      "La separación óptima entre los dos monitores del par estéreo.",
      "La distancia a la que empieza el campo lejano de la fuente.",
    ],
    ans: 1,
    why: "Más cerca que la distancia crítica domina el <b>directo</b> (y vale la ley inversa del cuadrado: −6 dB por duplicación); más lejos domina el <b>reverberante</b> y el nivel se aplana. Depende de la absorción de la sala y de la directividad de la fuente: una fuente más directiva empuja la distancia crítica hacia afuera. Es el argumento físico del <b>near-field monitoring</b>: escuchar dentro de la distancia crítica hace que la sala pese menos en lo que oís.",
    src: "Everest, Master Handbook of Acoustics, p. 87 (critical distance)",
  },
  {
    id: "fte-near-field",
    cat: "Monitoreo", dif: 1,
    q: "Monitorear en near-field sirve porque…",
    opts: [
      "El directo domina: la sala pesa menos en lo que oís.",
      "El campo reverberante refuerza los graves útiles.",
      "Se pueden usar monitores de menor calidad general.",
      "Elimina por completo los modos propios de la sala.",
    ],
    ans: 0,
    why: "Acercándote quedás dentro de la distancia crítica: el directo domina sobre el reverberante y la sala «se oye» menos. Es una forma barata de mejorar lo que escuchás sin tocar la sala. Pero ojo con la letra chica — <b>no funciona en graves</b>: ahí λ es comparable a la sala, el campo es modal y no hay distancia crítica que valga. Podés estar a 80 cm del monitor y seguir oyendo el modo de la sala tal cual.",
    src: "Everest, Master Handbook of Acoustics, p. 87 · Newell, Recording Studio Design",
  },
  {
    id: "fte-campo-cercano",
    cat: "Propagación", dif: 2,
    q: "El campo cercano de una fuente es la región donde…",
    opts: [
      "La presión no sigue la ley inversa del cuadrado.",
      "El nivel cae exactamente 6 dB por duplicación.",
      "Domina el campo reverberante sobre el directo.",
      "La respuesta en frecuencia es perfectamente plana.",
    ],
    ans: 0,
    why: "Muy cerca de la fuente, las contribuciones de las distintas partes del radiador llegan con fases distintas y hay energía reactiva que no se propaga: la presión no cae de forma ordenada y depende de dónde midas. Recién en el <b>campo lejano</b> (a varias veces la dimensión de la fuente y varias λ) la fuente se comporta como puntual y aparece el −6 dB por duplicación. Es por esto que un parlante grande hay que medirlo de lejos.",
    src: "Toole, Sound Reproduction, §18.1.1, p. 366 · Beranek, Acústica",
  },
  {
    id: "fte-triangulo",
    cat: "Monitoreo", dif: 1,
    q: "El triángulo equilátero de escucha estéreo busca…",
    opts: [
      "Que ambos monitores estén a igual distancia y a 60°.",
      "Que los monitores queden lo más separados posible.",
      "Que el oyente quede pegado a la pared de atrás.",
      "Que la distancia sea siempre mayor a tres metros.",
    ],
    ans: 0,
    why: "Con 60° de apertura y distancias iguales, las señales de L y R llegan al oyente con los retardos y niveles que el estéreo asume: ahí el fantasma central se forma nítido y centrado. Abrir más los monitores agranda la imagen pero abre un agujero en el centro; cerrarlos la angosta. Y las distancias tienen que ser <b>iguales</b>: unos pocos centímetros de diferencia ya corren la imagen.",
    src: "Toole, Sound Reproduction · ITU-R BS.775",
  },
  {
    id: "fte-monitor-altura",
    cat: "Monitoreo", dif: 1,
    q: "El tweeter de un monitor debería quedar…",
    opts: [
      "A la altura del oído en la posición de escucha.",
      "Lo más alto posible para ganar directividad.",
      "A la altura del pecho, para no cansar el oído.",
      "Da igual: la directividad vertical es amplia.",
    ],
    ans: 0,
    why: "La directividad <b>vertical</b> de un monitor de dos vías es estrecha e irregular cerca del cruce: fuera del eje vertical aparecen lóbulos y nulos por la interferencia entre woofer y tweeter, que están separados físicamente. Salirse unos pocos grados en vertical ya cambia el timbre. En horizontal el patrón es mucho más amplio y benigno — por eso la altura importa bastante más que unos grados de rotación.",
    src: "Toole, Sound Reproduction, §18.2, p. 372",
  },
  {
    id: "fte-itu-775",
    cat: "Monitoreo", dif: 2,
    q: "La recomendación ITU-R BS.775 define…",
    opts: [
      "Los ángulos de los canales en una configuración 5.1.",
      "El nivel máximo de SPL admisible en sala de mezcla.",
      "La curva objetivo de respuesta en frecuencia en sala.",
      "El RT60 recomendado para posproducción de audio.",
    ],
    ans: 0,
    why: "Fija la geometría del multicanal: frontales a ±30°, surrounds a ±100–120°, todos a igual distancia del punto de escucha y con el mismo tipo de monitor. La idea es que el campo sonoro que se mezcla en un estudio se reproduzca igual en otro. Es geometría de reproducción: el nivel, la curva objetivo y el RT los tratan otras normas y recomendaciones.",
    src: "ITU-R BS.775",
  },

  // ───────────────────────── Subwoofers e integración ─────────────────────────
  {
    id: "fte-cruce-80",
    cat: "Subwoofers", dif: 2,
    q: "El cruce típico sub-satélite en 80 Hz se elige porque…",
    opts: [
      "Es donde el sub deja de localizarse y el satélite rinde.",
      "Es la frecuencia de Schroeder de cualquier sala chica.",
      "Es el límite inferior de la audición humana normal.",
      "Es donde el amplificador entrega su máxima potencia.",
    ],
    ans: 0,
    why: "Es un compromiso entre dos cosas: por debajo de ~80 Hz las pistas direccionales se debilitan (λ ≫ cabeza) y el sub no se delata, y por encima el satélite chico ya trabaja cómodo sin exigirle excursión. Que funcione depende de que el pasabajos <b>corte de verdad</b>: si el sub deja pasar armónicos o distorsión arriba del cruce, se localiza igual y se escucha «el sub» como objeto separado.",
    src: "Toole, Sound Reproduction, §13.3, p. 216 · ITU-R BS.775",
  },
  {
    id: "fte-alineacion-fase",
    cat: "Subwoofers", dif: 2,
    q: "Alinear en fase un sub con los monitores en el cruce evita…",
    opts: [
      "Un nulo por cancelación justo en la zona del cruce.",
      "Que el sub se localice como fuente independiente.",
      "La distorsión armónica del woofer en graves altos.",
      "Que el amplificador entre en protección térmica.",
    ],
    ans: 0,
    why: "En la zona de cruce las dos fuentes entregan energía comparable. Si llegan en contrafase al punto de escucha se restan y aparece un agujero — típicamente el «me falta cuerpo en 80 Hz» que ningún EQ arregla, porque es cancelación. Se corrige con el control de fase/polaridad o con delay, y se verifica midiendo: sumás y comparás contra cada fuente sola. Es de los ajustes más rentables de un sistema con sub.",
    src: "Toole, Sound Reproduction, §13.3, p. 216",
  },
  {
    id: "fte-bass-management",
    cat: "Subwoofers", dif: 2,
    q: "El bass management en un sistema multicanal…",
    opts: [
      "Deriva los graves de todos los canales a un sub.",
      "Es lo mismo que el canal LFE de la banda sonora.",
      "Aplica un EQ de graves a cada canal por separado.",
      "Limita el nivel de graves para proteger el sub.",
    ],
    ans: 0,
    why: "Filtra los graves de cada canal principal y los suma al subwoofer, para que los satélites no tengan que reproducir lo que no pueden. Es <b>independiente</b> del canal LFE: el sub termina reproduciendo la suma de los graves derivados <i>más</i> el LFE. Confundirlos es el error clásico — un sistema puede tener bass management sin LFE (música estéreo con sub) y viceversa.",
    src: "Toole, Sound Reproduction, §13.3, p. 216 · ITU-R BS.775",
  },
  {
    id: "fte-lfe",
    cat: "Subwoofers", dif: 2,
    q: "El canal LFE (.1) de un sistema 5.1…",
    opts: [
      "Es un canal aparte con 10 dB de headroom extra.",
      "Es exactamente el mismo canal que el subwoofer.",
      "Contiene los graves derivados de los otros cinco.",
      "Va siempre por encima de los 120 Hz de la banda.",
    ],
    ans: 0,
    why: "El LFE es un canal <b>discreto</b> de banda limitada (~120 Hz), pensado para efectos de mucha energía, y se calibra con +10 dB de headroom respecto de los canales principales. No es «el sub»: el subwoofer es un <i>parlante</i>, que suele reproducir el LFE más los graves que le deriva el bass management. Un sistema puede tener sub sin LFE, y el LFE se puede reproducir sin sub dedicado.",
    src: "Toole, Sound Reproduction, §13.3, p. 216 · ITU-R BS.775",
  },

  // ───────────────────────── Diseño de la fuente ─────────────────────────
  {
    id: "fte-directividad",
    cat: "Directividad", dif: 2,
    q: "¿Por qué importa que un monitor tenga directividad constante con la frecuencia?",
    opts: [
      "Para que el monitor entregue más SPL sobre el eje de escucha.",
      "Fuera de eje se excita la sala: si varía, el reflejado desentona.",
      "Porque de ese modo la sala no desarrolla modos axiales fuertes.",
      "Porque mejora la respuesta transitoria del woofer y el tweeter.",
    ],
    ans: 1,
    why: "Lo que oís es directo + sala, y la sala se alimenta de <b>todo</b> lo que radia el parlante, no sólo del eje. Si el woofer es omnidireccional en graves y el tweeter estrecho en agudos, el campo reverberante sale con exceso de graves respecto del directo. Por eso Toole insiste en juzgar un parlante por su familia completa de curvas (on-axis, listening window, early reflections, sound power) y no por la respuesta en eje sola: dos parlantes con el mismo eje pueden sonar muy distinto en la misma sala.",
    src: "Toole, Sound Reproduction, §18.2, p. 372 (Objective Evaluations)",
  },
  {
    id: "fte-directividad-q",
    cat: "Directividad", dif: 2,
    q: "El factor de directividad Q de una fuente…",
    opts: [
      "Es la relación entre la intensidad en eje y la media.",
      "Es el ángulo de cobertura nominal medido en grados.",
      "Es la impedancia de radiación que ve el diafragma.",
      "Es la potencia acústica total que entrega la fuente.",
    ],
    ans: 0,
    why: "<code>Q</code> compara la intensidad en el eje contra la que habría si la misma potencia se repartiera en todas las direcciones. Q = 1 es omnidireccional; Q = 2, medio espacio. El <b>índice de directividad</b> es su versión en dB: <code>DI = 10·log₁₀(Q)</code>. Es el número que entra en el cálculo de distancia crítica: más Q, más lejos llega el dominio del campo directo.",
    src: "Beranek, Acústica, p. 96 (índice de directividad) · Everest, Master Handbook of Acoustics",
  },
  {
    id: "fte-listening-window",
    cat: "Directividad", dif: 3,
    q: "La «listening window» de Toole es…",
    opts: [
      "El promedio de curvas en un abanico alrededor del eje.",
      "La ventana de vidrio entre control y sala de grabación.",
      "El rango de frecuencias donde el monitor es plano.",
      "La zona de la sala libre de reflexiones tempranas.",
    ],
    ans: 0,
    why: "Es un promedio espacial de la respuesta en un abanico de ±30° horizontal y ±10° vertical: representa lo que efectivamente oye una cabeza que se mueve un poco, en vez de la ficción del eje exacto. Es una de las curvas del «spinorama» (junto con early reflections y sound power), y correlaciona mucho mejor con la preferencia de los oyentes que la respuesta en eje sola.",
    src: "Toole, Sound Reproduction, §18.2, p. 373 · ANSI/CTA-2034",
  },
  {
    id: "fte-waveguide",
    cat: "Directividad", dif: 2,
    q: "Una guía de onda (waveguide) en un tweeter sirve para…",
    opts: [
      "Controlar la directividad y emparejarla con el woofer.",
      "Aumentar la potencia máxima que soporta el tweeter.",
      "Bajar la frecuencia de resonancia propia de la cúpula.",
      "Eliminar la distorsión armónica en alta frecuencia.",
    ],
    ans: 0,
    why: "El problema a resolver es la <b>discontinuidad de directividad</b> en el cruce: el woofer se vuelve directivo justo antes de cruzar, y el tweeter arranca ancho. Eso mete un salto en la energía que va a la sala, aunque el eje mida plano. La guía estrecha el patrón del tweeter en la zona de cruce y empareja la transición. Suele dar de yapa algo de ganancia y menos excursión, pero ése no es su propósito.",
    src: "Toole, Sound Reproduction, §18.2, p. 372",
  },
  {
    id: "fte-mtm-lobing",
    cat: "Directividad", dif: 3,
    q: "Un monitor con dos woofers y el tweeter al medio (MTM) vertical…",
    opts: [
      "Controla la directividad vertical y reduce el lobing.",
      "Duplica la directividad horizontal de la caja usada.",
      "Elimina la necesidad de cruce entre woofer y tweeter.",
      "Sólo funciona bien si el monitor se coloca acostado.",
    ],
    ans: 0,
    why: "La disposición simétrica (D'Appolito) hace que los lóbulos de interferencia entre los dos woofers y el tweeter se distribuyan de forma simétrica arriba y abajo del eje, en vez de inclinar el lóbulo principal como pasa en una caja de dos vías común. El patrón vertical se angosta de manera controlada. Y por eso mismo <b>no</b> hay que acostarlo: acostado, el patrón angosto queda en horizontal, que es justo donde lo querés ancho.",
    src: "Toole, Sound Reproduction, §18.2, p. 372 · D'Appolito (1983)",
  },
  {
    id: "fte-baffle-step",
    cat: "Diseño de caja", dif: 3,
    q: "El baffle step de una caja acústica es…",
    opts: [
      "La transición de 4π a 2π al subir en frecuencia.",
      "El escalón que produce el filtro de cruce agudo.",
      "La resonancia de la caja en su frecuencia de tuning.",
      "El salto de impedancia en la zona del crossover.",
    ],
    ans: 0,
    why: "En graves, λ es mucho mayor que el frente de la caja: el sonido «dobla» alrededor y radia en esfera completa (4π). En agudos, λ es chica frente al baffle y la radiación queda hacia adelante (2π). La transición vale <b>6 dB</b> y ocurre donde λ es comparable al ancho del frente. Por eso las cajas chicas suenan flacas si no se compensa, y por eso el mismo parlante empotrado en pared cambia por completo su balance.",
    src: "Toole, Sound Reproduction, §18.1, p. 366 · Beranek & Mellow, Sound Fields and Transducers, cap. 4, p. 129",
  },
  {
    id: "fte-difraccion-bordes",
    cat: "Diseño de caja", dif: 2,
    q: "Las aristas vivas del gabinete de un monitor…",
    opts: [
      "Difractan y ensucian la respuesta con ondulaciones.",
      "Mejoran la directividad al recortar la radiación.",
      "Sólo afectan por debajo de la frecuencia de cruce.",
      "No influyen: la difracción sólo ocurre en graves.",
    ],
    ans: 0,
    why: "Cada arista se comporta como una <b>fuente secundaria</b> retardada: su radiación interfiere con la del driver y arma ondulaciones en la respuesta y en el patrón de directividad. Por eso los monitores buenos tienen los cantos redondeados o biselados y el tweeter descentrado. Es un efecto de medios y agudos, donde λ es comparable al tamaño de la caja — en graves la caja es acústicamente diminuta.",
    src: "Toole, Sound Reproduction, §18.2, p. 372 · Beranek & Mellow, Sound Fields and Transducers, cap. 4, p. 129",
  },
  {
    id: "fte-sellada-ported",
    cat: "Diseño de caja", dif: 3,
    q: "Frente a una caja sellada, una bass-reflex con el mismo woofer…",
    opts: [
      "Extiende los graves pero con más retardo de grupo.",
      "Tiene menos retardo de grupo y mejor transitorio.",
      "Da exactamente la misma respuesta, con más SPL.",
      "No necesita amplificación adicional en la banda.",
    ],
    ans: 0,
    why: "El puerto es un resonador que aporta salida cerca de la sintonía: extiende la respuesta y alivia la excursión del woofer. El costo es que la caída pasa de 12 dB/oct (sellada, 2º orden) a 24 dB/oct (reflex, 4º orden), y ese orden más alto trae más <b>retardo de grupo</b> cerca de la sintonía. Debajo del tuning, además, el woofer se queda sin carga y desprotegido. Ninguna es «mejor»: es un canje entre extensión, SPL y comportamiento temporal.",
    src: "Beranek & Mellow, Sound Fields and Transducers, cap. 7 (Loudspeaker Enclosures), p. 289 · Toole, Sound Reproduction",
  },
  {
    id: "fte-port-noise",
    cat: "Diseño de caja", dif: 2,
    q: "El ruido de puerto (chuffing) en una caja bass-reflex…",
    opts: [
      "Aparece a alto nivel por velocidad de aire excesiva.",
      "Es la resonancia del puerto en su frecuencia de tuning.",
      "Se produce sólo en cajas selladas, no en las ported.",
      "Baja cuando aumenta el nivel de graves reproducido.",
    ],
    ans: 0,
    why: "A niveles altos el aire pasa tan rápido por el puerto que el flujo se vuelve turbulento y se oye un soplido, sumado a distorsión. Se combate con puertos de mayor área (baja la velocidad para el mismo caudal), bordes acampanados (flared) que evitan el desprendimiento, o puertos múltiples. Es un límite <b>no lineal</b>: no aparece en la medición de respuesta a bajo nivel, sólo cuando exigís la caja.",
    src: "Beranek & Mellow, Sound Fields and Transducers, cap. 7 (Loudspeaker Enclosures), p. 289",
  },
  {
    id: "fte-line-array",
    cat: "Directividad", dif: 3,
    q: "Un line array bien diseñado, en su campo cercano…",
    opts: [
      "Radia onda cilíndrica: cae 3 dB por duplicación.",
      "Radia onda esférica: cae 6 dB por duplicación.",
      "No pierde nivel con la distancia en ningún caso.",
      "Sólo funciona por debajo de los 100 Hz de banda.",
    ],
    ans: 0,
    why: "Una línea de fuentes lo bastante larga y con separación ≪ λ genera un frente <b>cilíndrico</b>: la energía se reparte en la superficie de un cilindro (∝ r) y no de una esfera (∝ r²), así que cae 3 dB por duplicación en vez de 6. Eso vale sólo en el campo cercano de la línea, cuya extensión depende de la longitud y la frecuencia; más lejos vuelve a comportarse como fuente puntual y a caer 6 dB.",
    src: "Toole, Sound Reproduction, §18.1.2, p. 368 · Beranek & Mellow, Sound Fields and Transducers, cap. 4",
  },

  // ───────────────────────── Medición y límites ─────────────────────────
  {
    id: "fte-lede-rfz",
    cat: "Salas de control", dif: 2,
    q: "¿Cuál es la idea central de LEDE / RFZ en una sala de control?",
    opts: [
      "Hacer la sala lo más muerta posible en toda la banda audible.",
      "Directo primero, sin reflexiones tempranas; cola difusa atrás.",
      "Cubrir todas las superficies con difusores de fase cuadrática.",
      "Eliminar los modos propios por debajo de la f de Schroeder.",
    ],
    ans: 1,
    why: "LEDE (Live End Dead End) y RFZ (Reflection Free Zone) atacan las <b>reflexiones tempranas</b>, que se funden perceptualmente con el directo (efecto de precedencia) y corrompen timbre e imagen sin oírse como eco. La receta: frente controlado geométricamente para que la reflexión no vuelva a la posición de escucha, y fondo vivo pero <b>difuso</b>, que sostiene una cola densa y sin dirección definida. No es hacer la sala muerta: una sala anecoica es incómoda y engañosa para mezclar.",
    src: "Newell, Recording Studio Design · Everest, Master Handbook of Acoustics, p. 431 (LEDE/RFZ)",
  },
  {
    id: "fte-medicion-gated",
    cat: "Medición", dif: 3,
    q: "Una medición gated (con ventana) de un monitor en sala…",
    opts: [
      "Pierde resolución en graves: la ventana es muy corta.",
      "Elimina los modos y da la respuesta anecoica real.",
      "Mejora la precisión justamente en la banda grave.",
      "Sólo sirve si la sala tiene RT60 mayor a un segundo.",
    ],
    ans: 0,
    why: "La ventana corta la respuesta al impulso antes de que lleguen las reflexiones, así que «simula» una cámara anecoica. Pero la ventana impone un límite: si podés ventanear 5 ms, la resolución en frecuencia es ~1/5 ms = 200 Hz, o sea que <b>abajo de ~200 Hz la medición no vale nada</b>. Y en una sala chica la primera reflexión llega enseguida, dejando ventanas cortísimas. Justamente donde más problemas hay —los graves— es donde el gating no ayuda.",
    src: "Toole, Sound Reproduction, §18.2.2, p. 376",
  },
  {
    id: "fte-klippel-nfs",
    cat: "Medición", dif: 3,
    q: "Un escáner de campo cercano (NFS) resuelve…",
    opts: [
      "Medir anecoico en graves sin cámara anecoica.",
      "Eliminar la distorsión armónica del parlante.",
      "Medir el RT60 de una sala con más precisión.",
      "Calibrar la respuesta del micro de medición.",
    ],
    ans: 0,
    why: "Muestrea el campo sobre una superficie cerrada alrededor de la caja y, con una expansión en armónicos esféricos, separa matemáticamente lo que radia la fuente de lo que aporta la sala. Así obtiene la respuesta anecoica completa —incluidos los graves— en una sala normal, que es justo lo que ni el gating ni una cámara anecoica chica pueden dar. Es la razón por la que hoy hay tantos datos de spinorama disponibles.",
    src: "Klippel & Bellmann (2016) · Toole, Sound Reproduction, §18.2.2, p. 376",
  },
  {
    id: "fte-thd-imd",
    cat: "Distorsión", dif: 2,
    q: "La distorsión por intermodulación (IMD) en un woofer…",
    opts: [
      "Aparece al reproducir dos tonos y genera sumas y restas.",
      "Es siempre menor que la armónica, en cualquier caso.",
      "Sólo se manifiesta a niveles muy bajos de excursión.",
      "Es idéntica a la THD, sólo que medida de otra forma.",
    ],
    ans: 0,
    why: "Con dos tonos, una no linealidad genera productos en <b>f₂ ± f₁</b> y sus combinaciones. La diferencia perceptual con la THD es clave: los armónicos caen en frecuencias musicalmente relacionadas con el original y se enmascaran bastante, mientras que los productos de intermodulación caen en <b>lugares no relacionados</b> y se oyen como suciedad. Por eso un woofer con THD baja puede sonar sucio si su IMD es alta.",
    src: "Beranek & Mellow, Sound Fields and Transducers, cap. 6, p. 241 · Toole, Sound Reproduction",
  },
  {
    id: "fte-compresion",
    cat: "Distorsión", dif: 2,
    q: "La compresión de potencia en un parlante a alto SPL…",
    opts: [
      "Sube la Re de la bobina al calentarse y baja el nivel.",
      "Es un efecto del compresor de la consola de mezcla.",
      "Mejora la respuesta transitoria por amortiguamiento.",
      "Sólo ocurre en tweeters, nunca en woofers grandes.",
    ],
    ans: 0,
    why: "La bobina se calienta, su resistencia sube (el cobre tiene coeficiente térmico positivo) y el mismo voltaje entrega menos corriente: el parlante rinde menos. Puede llegar a varios dB en uso exigido, y aparece <b>lentamente</b>, así que no la ves en una medición corta. Además cambia el amortiguamiento y con eso el Q del sistema, o sea que el balance tonal se corre a medida que el sistema se calienta.",
    src: "Beranek & Mellow, Sound Fields and Transducers, cap. 6, p. 241",
  },
  {
    id: "fte-sensibilidad",
    cat: "Especificaciones", dif: 2,
    q: "La sensibilidad de un parlante (dB SPL a 2,83 V y 1 m)…",
    opts: [
      "No es lo mismo que eficiencia: depende de la impedancia.",
      "Es exactamente lo mismo que la eficiencia en porcentaje.",
      "Mide la potencia acústica total en todas las direcciones.",
      "Sólo tiene sentido para parlantes de 8 ohms nominales.",
    ],
    ans: 0,
    why: "2,83 V son 1 W <b>sólo en 8 Ω</b>. En un parlante de 4 Ω, esos mismos 2,83 V entregan 2 W, así que la sensibilidad «gana» 3 dB sin que el parlante sea más eficiente. La eficiencia real es potencia acústica sobre potencia eléctrica (típicamente 0,5–2 %, deprimente). Es una de las especificaciones más usadas para inflar planillas: comparar sensibilidades entre impedancias distintas no dice nada.",
    src: "Beranek & Mellow, Sound Fields and Transducers, cap. 6, p. 241 · Toole, Sound Reproduction, §18.6, p. 418",
  },
  {
    id: "fte-impedancia-minima",
    cat: "Especificaciones", dif: 2,
    q: "El mínimo de impedancia de un parlante importa porque…",
    opts: [
      "Es donde el amplificador entrega más corriente.",
      "Es donde el parlante suena con más distorsión.",
      "Coincide siempre con la resonancia del woofer.",
      "Marca la frecuencia de cruce entre las dos vías.",
    ],
    ans: 0,
    why: "El amplificador ve una carga, y donde la impedancia cae la corriente que tiene que entregar sube para el mismo voltaje. Un «8 Ω nominal» con mínimos de 3 Ω y fase muy reactiva es una carga exigente, y ahí es donde un amplificador flojo se queda sin nafta o distorsiona. Ojo con el error de la última opción: en la <b>resonancia</b> del woofer la impedancia tiene un <i>máximo</i>, no un mínimo.",
    src: "Toole, Sound Reproduction, §18.6, p. 418 · Beranek & Mellow, Sound Fields and Transducers, cap. 6, p. 241",
  },
  {
    id: "fte-retardo-grupo",
    cat: "Distorsión", dif: 3,
    q: "El retardo de grupo en graves se vuelve audible…",
    opts: [
      "Cuando supera aproximadamente un ciclo de la señal.",
      "Siempre: cualquier retardo de grupo se oye enseguida.",
      "Sólo en sistemas de más de 1000 W de potencia real.",
      "Nunca, porque el oído es totalmente sordo a la fase.",
    ],
    ans: 0,
    why: "Los umbrales medidos rondan el orden de un ciclo a la frecuencia en cuestión (varias decenas de ms en graves), y son bastante tolerantes: el oído es mucho menos sensible a la fase que a la magnitud. Ni «siempre» ni «nunca». Ese margen es lo que hace viables las cajas reflex y los filtros de orden alto — el retardo de grupo que introducen suele quedar por debajo del umbral con material musical real.",
    src: "Toole, Sound Reproduction, §18.6.2, p. 420 · Blauert & Laws (1978)",
  },

  // ═══════════════════════ TANDA 2 (nuevas) ═══════════════════════
  {
    id: "fte-toe-in",
    cat: "Monitoreo", dif: 1,
    q: "Angular los monitores hacia el oyente (toe-in) sirve para…",
    opts: [
      "Subir el nivel de presión sonora en la escucha.",
      "Poner el eje en el oyente y atenuar reflexiones.",
      "Alejar el punto de escucha de la pared de atrás.",
      "Reforzar los graves por acople con la pared.",
    ],
    ans: 1,
    why: "Con toe-in, el <b>eje directo</b> (donde el monitor es más plano y neutro) apunta al oyente, y de paso la energía que rebota en las paredes laterales llega más fuera de eje y atenuada. También ensancha el sweet spot horizontal. No sube el nivel de forma relevante ni tiene que ver con graves o distancia a la pared: es geometría de directividad.",
    src: "Toole, Sound Reproduction · Newell, Recording Studio Design",
  },
  {
    id: "fte-sweet-spot",
    cat: "Monitoreo", dif: 2,
    q: "El «sweet spot» de un sistema estéreo es…",
    opts: [
      "El punto donde la imagen y el balance son correctos.",
      "La zona de la sala con más nivel de presión sonora.",
      "El lugar donde no llega ninguna reflexión temprana.",
      "El punto de máxima excitación de los modos graves.",
    ],
    ans: 0,
    why: "Es el punto (o zona chica) donde llegan L y R con los tiempos y niveles que el estéreo asume: ahí la imagen fantasma se arma centrada y el balance tonal es el correcto. Salirse rompe la simetría y corre la imagen hacia el monitor más cercano (precedencia). No es donde hay más nivel ni menos reflexiones ni más modos: es donde la <b>geometría estéreo</b> cierra.",
    src: "Toole, Sound Reproduction · ITU-R BS.775",
  },
  {
    id: "fte-crossover-orden",
    cat: "Diseño de caja", dif: 3,
    q: "Un crossover de mayor orden (pendiente más pronunciada)…",
    opts: [
      "Reduce el solapamiento entre vías pero rota más la fase.",
      "Mejora la fase y ensancha el solapamiento entre vías.",
      "No afecta la fase, sólo la potencia que entra al driver.",
      "Elimina por completo la interferencia entre las vías.",
    ],
    ans: 0,
    why: "Más orden = pendiente más abrupta = menos solapamiento entre woofer y tweeter (cada uno trabaja sólo en lo suyo, con menos zona de interferencia y menos exigencia fuera de banda). El costo es más <b>rotación de fase</b> alrededor del cruce y más retardo de grupo. Es un canje: los diseños buscan un orden que controle el lobing sin ensuciar la fase de más. No elimina la interferencia, la acota.",
    src: "Beranek & Mellow, Sound Fields and Transducers · Toole, Sound Reproduction",
  },
  {
    id: "fte-fase-crossover",
    cat: "Diseño de caja", dif: 3,
    q: "En la zona de cruce entre woofer y tweeter puede aparecer…",
    opts: [
      "Un pico o nulo según cómo sumen las dos vías en fase.",
      "Un aumento uniforme de nivel en toda la banda audible.",
      "La resonancia de la caja en su frecuencia de sintonía.",
      "El baffle step, que es independiente del crossover.",
    ],
    ans: 0,
    why: "Cerca del cruce las dos vías entregan energía comparable: si llegan en fase suman (pico), si llegan en contrafase se restan (nulo), y el resultado depende de la distancia entre drivers, la altura de escucha y el diseño del filtro. Por eso el eje vertical de un monitor es tan sensible. Es un problema de <b>suma en fase</b>, distinto del baffle step (transición 4π→2π) y de la resonancia de la caja.",
    src: "Toole, Sound Reproduction · Beranek & Mellow, Sound Fields and Transducers",
  },
  {
    id: "fte-time-align",
    cat: "Diseño de caja", dif: 2,
    q: "Alinear temporalmente woofer y tweeter busca que…",
    opts: [
      "Los dos drivers reciban igual potencia eléctrica.",
      "Sus frentes de onda lleguen a la vez al oyente.",
      "El tweeter cruce en una frecuencia más baja aún.",
      "La caja resuene en fase con la sala de escucha.",
    ],
    ans: 1,
    why: "Los centros acústicos del woofer y el tweeter suelen estar a distintas profundidades: sin alinear, sus frentes de onda llegan <b>desfasados</b> al oyente y la suma en el cruce se degrada. Se corrige retrasando el driver adelantado (baffle escalonado, o delay en un sistema activo). Da una respuesta de fase más limpia y mejor transitorio en el cruce. No tiene que ver con potencia, frecuencia de cruce ni con la sala.",
    src: "Beranek & Mellow, Sound Fields and Transducers · Toole, Sound Reproduction",
  },
  {
    id: "fte-activo-pasivo",
    cat: "Diseño de caja", dif: 2,
    q: "Un monitor activo, frente a uno pasivo, tiene la ventaja de…",
    opts: [
      "Pesar bastante menos por no llevar amplificador.",
      "Cruzar en señal y adaptar cada ampli al driver.",
      "No necesitar corriente eléctrica para funcionar.",
      "Eliminar por completo la distorsión del woofer.",
    ],
    ans: 1,
    why: "En el activo el crossover trabaja a <b>nivel de línea</b> (antes de amplificar) y cada vía tiene su amplificador dedicado, ajustado al driver: mejor control, menos pérdidas que un filtro pasivo de potencia, y posibilidad de EQ y protección por vía. Pesa más (lleva los amplis) y necesita alimentación. No elimina la distorsión, pero permite manejarla mejor. Por eso casi todos los monitores de estudio modernos son activos.",
    src: "Beranek & Mellow, Sound Fields and Transducers · Toole, Sound Reproduction",
  },
  {
    id: "fte-dispersion-horizontal",
    cat: "Directividad", dif: 2,
    q: "Una dispersión horizontal amplia y pareja en un monitor conviene porque…",
    opts: [
      "Concentra toda la energía en el eje de escucha.",
      "Alimenta la sala con un timbre parejo fuera de eje.",
      "Elimina las reflexiones de las paredes laterales.",
      "Sube el nivel de graves por acople con los bordes.",
    ],
    ans: 1,
    why: "Lo que rebota en las paredes laterales viene de la energía <b>fuera de eje</b> horizontal. Si la dispersión es amplia y pareja, ese campo reflejado tiene el mismo timbre que el directo y la imagen se mantiene sana aun con reflexiones. Si es angosta o irregular, el reflejado desentona. No concentra la energía (eso sería directividad estrecha) ni elimina reflexiones: hace que las que haya no arruinen el timbre.",
    src: "Toole, Sound Reproduction (spinorama)",
  },
  {
    id: "fte-cardioide-medios",
    cat: "Directividad", dif: 2,
    q: "Un micrófono cardioide capta principalmente…",
    opts: [
      "Por igual en todas las direcciones del espacio.",
      "Por el frente, rechazando lo que viene atrás.",
      "Sólo por los costados, en forma de ocho ancho.",
      "Sólo la presión, sin nada de direccionalidad.",
    ],
    ans: 1,
    why: "El cardioide combina un elemento de presión (omni) con uno de gradiente (figura-8) para captar por el <b>frente</b> y rechazar la parte de atrás (~unos 20-25 dB en el nulo trasero). Por eso sirve para aislar una fuente del resto de la sala y para controlar realimentación. El omni capta todo; el figura-8 capta frente y espalda rechazando los lados. La direccionalidad viene del gradiente de presión.",
    src: "Beranek & Mellow, Sound Fields and Transducers",
  },
  {
    id: "fte-proximidad",
    cat: "Directividad", dif: 3,
    q: "El efecto de proximidad en un micrófono direccional es…",
    opts: [
      "Un realce de graves al acercar la fuente al micro.",
      "Un realce de agudos cuando la fuente se aleja.",
      "La pérdida total de señal muy cerca de la cápsula.",
      "Un aumento de la direccionalidad a baja frecuencia.",
    ],
    ans: 0,
    why: "En los micrófonos de gradiente de presión (cardioide, figura-8), acercarse a la fuente <b>realza los graves</b> de forma creciente: es el efecto de proximidad, consecuencia del gradiente ante un frente de onda curvo (campo cercano). Los locutores lo usan para «engordar» la voz. Un omni puro no lo tiene. No afecta los agudos ni la direccionalidad: es un realce grave dependiente de la distancia.",
    src: "Beranek & Mellow, Sound Fields and Transducers",
  },
  {
    id: "fte-headroom",
    cat: "Niveles", dif: 2,
    q: "El headroom de un sistema de monitoreo es…",
    opts: [
      "El margen entre el nivel medio y el recorte.",
      "La ganancia total del amplificador de potencia.",
      "El nivel de ruido de fondo del conversor D/A.",
      "La distancia entre el monitor y el cielorraso.",
    ],
    ans: 0,
    why: "Es el <b>margen</b> disponible por encima del nivel promedio de trabajo antes de que algo recorte o el driver llegue a su límite de excursión. La música tiene transitorios que superan mucho el nivel medio (factor de cresta): sin headroom, esos picos distorsionan. Por eso se elige un monitor con SPL de sobra para el nivel de escucha habitual. No es la ganancia, ni el ruido de fondo, ni algo físico del cuarto.",
    src: "Toole, Sound Reproduction · Beranek & Mellow, Sound Fields and Transducers",
  },
  {
    id: "fte-factor-cresta",
    cat: "Niveles", dif: 2,
    q: "El factor de cresta de una señal es…",
    opts: [
      "La relación entre su valor de pico y su RMS.",
      "El promedio de nivel medido en toda la señal.",
      "La diferencia entre el canal izquierdo y derecho.",
      "La frecuencia donde la señal tiene más energía.",
    ],
    ans: 0,
    why: "Es <b>pico / RMS</b>: cuánto sobresalen los transitorios sobre el nivel medio. Una onda senoidal tiene ~3 dB; la música sin comprimir, 12-20 dB; muy comprimida, poco. Importa para el headroom (los picos son los que recortan) y explica por qué dos señales con el mismo RMS pueden necesitar amplificadores muy distintos. No es el promedio, ni la diferencia estéreo, ni dónde está la energía.",
    src: "Beranek & Mellow, Sound Fields and Transducers",
  },
  {
    id: "fte-dbfs-spl",
    cat: "Niveles", dif: 3,
    q: "Calibrar el monitoreo a un SPL de referencia por dBFS sirve para…",
    opts: [
      "Que dos estudios traduzcan igual el nivel de mezcla.",
      "Subir bastante el volumen máximo que da el sistema.",
      "Eliminar el ruido de fondo del cuarto de control.",
      "Aplanar la respuesta en frecuencia de toda la sala.",
    ],
    ans: 0,
    why: "Fijar cuántos dB SPL corresponden a un nivel digital de referencia (p. ej. −20 dBFS → 79 u 83 dB SPL) hace que <b>mezcles siempre al mismo nivel acústico</b>, lo que estabiliza el balance tonal que percibís (las isofónicas cambian con el nivel) y hace que otra sala calibrada igual «traduzca». Es consistencia de referencia, no más volumen ni menos ruido ni corrección de sala.",
    src: "Toole, Sound Reproduction · ITU / K-System",
  },
  {
    id: "fte-comb-directo-reflejado",
    cat: "Reflexiones", dif: 2,
    q: "El directo sumado a una reflexión de pocos ms produce…",
    opts: [
      "Un filtro peine: picos y nulos a intervalos fijos.",
      "Un aumento parejo de nivel en toda la banda audible.",
      "Una cola reverberante larga en la banda de graves.",
      "Una rotación de fase constante en toda la banda.",
    ],
    ans: 0,
    why: "Directo + copia retardada = interferencia periódica: aparecen nulos donde el retardo vale media onda y picos donde vale una onda entera, repetidos a intervalos de <code>1/Δt</code> Hz. Es el <b>filtro peine</b>, la firma de una reflexión temprana especular (consola, pared lateral). Cuanto más corto el retardo, más separados los dientes. No es un realce parejo ni una cola: es un patrón de peine fijo.",
    src: "Everest, Master Handbook of Acoustics · Toole, Sound Reproduction",
  },
  {
    id: "fte-atril-difraccion",
    cat: "Diseño de caja", dif: 2,
    q: "Un objeto duro justo al lado del tweeter (reja, tornillo, borde)…",
    opts: [
      "Mejora la directividad recortando la radiación.",
      "Difracta y mete ondulaciones finas en la respuesta.",
      "Sólo afecta los graves, por su tamaño pequeño.",
      "Absorbe los agudos y suaviza la respuesta en eje.",
    ],
    ans: 1,
    why: "Cualquier discontinuidad cerca del tweeter actúa como <b>fuente secundaria</b> por difracción: su radiación interfiere con la del driver y mete ondulaciones (ripple) en la respuesta y el patrón. Por eso los monitores buenos tienen frentes limpios, cantos redondeados y rejillas acústicamente transparentes. Es un efecto de agudos (λ chica comparable al objeto), no de graves, y ensucia en vez de suavizar.",
    src: "Beranek & Mellow, Sound Fields and Transducers · Toole, Sound Reproduction",
  },
  {
    id: "fte-rew-medicion",
    cat: "Medición", dif: 2,
    q: "Para medir la respuesta en frecuencia de la sala en la escucha se usa…",
    opts: [
      "Un sonómetro con ponderación A y lectura lenta.",
      "Un barrido (sweep) con micro de medición y software.",
      "El oído entrenado comparando con un disco de prueba.",
      "Un osciloscopio conectado a la salida del monitor.",
    ],
    ans: 1,
    why: "El método estándar es un <b>barrido senoidal</b> reproducido por el monitor y capturado con un micrófono de medición calibrado; el software (REW, etc.) extrae la respuesta al impulso y de ahí la magnitud, la fase, el decaimiento (waterfall) y el RT. Un sonómetro sólo da un número global; el oído no cuantifica; el osciloscopio no separa sala de señal. El sweep + micro es lo que da el detalle por frecuencia.",
    src: "Toole, Sound Reproduction · Everest, Master Handbook of Acoustics",
  },
  {
    id: "fte-micro-calibracion",
    cat: "Medición", dif: 2,
    q: "Un micrófono de medición debe ser…",
    opts: [
      "Muy direccional, para captar sólo el monitor.",
      "Omnidireccional y plano, con curva de calibración.",
      "De condensador grande, para captar más graves.",
      "Cardioide, para rechazar el ruido de la sala.",
    ],
    ans: 1,
    why: "Para medir una sala querés captar el <b>campo real</b> en el punto de escucha sin colorearlo: eso pide un micro <b>omnidireccional</b> y de respuesta plana, idealmente con su curva de calibración individual para corregir las pequeñas desviaciones. Uno direccional (cardioide) o «musical» mete su propia firma (proximidad, realces) y falsea la medición. La direccionalidad es justo lo que NO querés acá.",
    src: "Toole, Sound Reproduction · IEC 61094",
  },
  {
    id: "fte-latencia-monitoreo",
    cat: "Sistema", dif: 2,
    q: "La latencia de monitoreo por software (round-trip) molesta sobre todo al…",
    opts: [
      "Mezclar, porque desfasa los graves de toda la sala.",
      "Grabar en vivo, por el retardo entre tocar y oír.",
      "Masterizar, porque altera la respuesta de la sala.",
      "Ecualizar, porque corre la fase de los filtros.",
    ],
    ans: 1,
    why: "El retardo de ida y vuelta por el conversor y el buffer (varios ms) es un problema al <b>grabar monitoreando por la compu</b>: el músico toca y se oye tarde, lo que descoloca. Se resuelve con monitoreo de latencia cero (por hardware) o bajando el tamaño del buffer. Al mezclar, masterizar o ecualizar ya reproducido, la latencia constante es irrelevante — no cambia el sonido, sólo importa cuando hay que tocar en tiempo real.",
    src: "Práctica de estudio · Newell, Recording Studio Design",
  },
  {
    id: "fte-mono-compatibilidad",
    cat: "Corregibilidad", dif: 2,
    q: "Chequear la mezcla en mono sirve para detectar…",
    opts: [
      "Cancelaciones por fase entre los canales L y R.",
      "El nivel de graves absoluto de la mezcla final.",
      "La distorsión armónica del amplificador de audio.",
      "El ruido de fondo del cuarto de control usado.",
    ],
    ans: 0,
    why: "Al sumar L+R en mono, todo lo que esté en <b>contrafase</b> entre canales se cancela: elementos que sonaban bien en estéreo desaparecen o pierden cuerpo. Es la prueba clásica de compatibilidad — importa porque mucha reproducción real colapsa a mono (parlantes de teléfono, algunos sistemas de PA). No revela distorsión del amplificador ni ruido del cuarto: revela problemas de <b>fase</b> entre canales.",
    src: "Toole, Sound Reproduction · práctica de mezcla",
  },
  {
    id: "fte-nearfield-vs-mid",
    cat: "Monitoreo", dif: 2,
    q: "Frente a los mains empotrados, los monitores near-field se caracterizan por…",
    opts: [
      "Dar más SPL y llegar más profundo en los graves.",
      "Reducir el peso de la sala al escuchar de cerca.",
      "Cubrir mejor a varias personas a la vez sentadas.",
      "Depender bastante menos de la posición de escucha.",
    ],
    ans: 1,
    why: "Escuchar de cerca (dentro de la distancia crítica) hace que domine el <b>directo</b> y la sala pese menos en lo que oís — es la razón de ser del near-field. Los mains empotrados dan más SPL y extensión y sirven para revisar a nivel alto, pero involucran mucho más a la sala. El near-field cubre <i>peor</i> a varios (sweet spot chico) y no es menos sensible a la posición: su fuerte es aislar del cuarto.",
    src: "Newell, Recording Studio Design · Everest, Master Handbook of Acoustics",
  },

  // ═══════════════════════ TANDA 3 (difíciles) ═══════════════════════
  {
    id: "fte-thiele-small",
    cat: "Diseño de caja", dif: 3,
    q: "Los parámetros de Thiele-Small de un driver describen…",
    opts: [
      "Su comportamiento electromecánico en baja frecuencia.",
      "La respuesta en agudos por encima del cruce elegido.",
      "La directividad del driver bien fuera de su eje.",
      "La distorsión armónica del driver a máxima potencia.",
    ],
    ans: 0,
    why: "Los parámetros de Thiele-Small (fs, Qts, Vas, Bl, Sd, Mms…) modelan el driver como un sistema masa-resorte-amortiguado acoplado a lo eléctrico, y predicen su comportamiento en <b>baja frecuencia</b> dentro de una caja. Con ellos se diseña el volumen y la sintonía del recinto. No dicen nada de agudos, directividad ni distorsión: son un modelo de parámetros concentrados válido donde el cono se mueve como pistón.",
    src: "Beranek & Mellow, Sound Fields and Transducers · Thiele; Small (1972)",
  },
  {
    id: "fte-qts",
    cat: "Diseño de caja", dif: 3,
    q: "El Qts de un woofer determina, sobre todo…",
    opts: [
      "Qué tipo de caja y alineación le conviene.",
      "La máxima potencia que soporta sin dañarse.",
      "Su sensibilidad en decibeles por vatio.",
      "La frecuencia de cruce con el tweeter.",
    ],
    ans: 0,
    why: "El Qts (Q total a la resonancia) marca el <b>amortiguamiento</b> del driver y con eso a qué caja se adapta: Qts bajo (~0,2-0,4) quiere caja reflex o incluso bocina; Qts medio (~0,4-0,7) va bien en caja sellada; Qts alto puede sonar en pantalla infinita. Meter un driver en la caja equivocada da una respuesta con joroba o floja en graves. No fija potencia, sensibilidad ni cruce.",
    src: "Beranek & Mellow, Sound Fields and Transducers · Small (1972)",
  },
  {
    id: "fte-vas",
    cat: "Diseño de caja", dif: 3,
    q: "El parámetro Vas de un driver representa…",
    opts: [
      "El volumen de aire con igual rigidez que la suspensión.",
      "El volumen interno mínimo que debe tener la caja usada.",
      "El volumen de aire que desplaza el cono al moverse.",
      "El volumen del puerto de una caja bass-reflex típica.",
    ],
    ans: 0,
    why: "Vas es el <b>volumen de aire equivalente</b> a la rigidez (compliance) de la suspensión del driver: un aire encerrado de ese volumen tendría la misma rigidez que las arañas y el surround. Junto con Qts y fs, determina el volumen de caja necesario. Un Vas grande (suspensión blanda) pide caja grande. No es el volumen de la caja, ni el desplazado por el cono, ni el del puerto.",
    src: "Beranek & Mellow, Sound Fields and Transducers · Small (1972)",
  },
  {
    id: "fte-bl",
    cat: "Diseño de caja", dif: 3,
    q: "El factor de fuerza Bl de un driver mide…",
    opts: [
      "El acople entre la corriente y la fuerza en el cono.",
      "El brillo del driver en toda la banda de agudos.",
      "La masa móvil total del conjunto cono más bobina.",
      "El ancho de banda útil del driver medido en octavas.",
    ],
    ans: 0,
    why: "Bl (producto del campo magnético B por el largo de hilo l en el entrehierro) es el <b>factor de conversión</b> electromecánico: la fuerza sobre el cono es <code>F = Bl·i</code>. Un Bl alto da un motor «fuerte», más control y eficiencia. Si Bl <b>varía</b> con la excursión (el cono sale del campo uniforme), aparece distorsión. No tiene que ver con brillo, masa ni ancho de banda directamente.",
    src: "Beranek & Mellow, Sound Fields and Transducers",
  },
  {
    id: "fte-hoffman",
    cat: "Diseño de caja", dif: 3,
    q: "La «ley de hierro» de Hoffman dice que no se puede tener a la vez…",
    opts: [
      "Extensión grave, alta sensibilidad y caja chica.",
      "Baja distorsión, mucha potencia y bajo costo total.",
      "Fase lineal, respuesta plana y directividad ancha.",
      "Aislamiento, absorción y difusión en un solo panel.",
    ],
    ans: 0,
    why: "Es un compromiso físico ineludible: <b>graves profundos + alta sensibilidad + caja chica</b> — sólo se pueden elegir dos. Querés graves de un monitor chico: pagás sensibilidad (necesita más potencia y excursión). Querés graves y eficiencia: la caja se vuelve enorme (bocinas). Por eso los monitores compactos son activos y comen mucha potencia en graves. Es el marco para entender toda caja acústica.",
    src: "Beranek & Mellow, Sound Fields and Transducers · Hofmann (Acoustic Research)",
  },
  {
    id: "fte-cone-breakup",
    cat: "Diseño de caja", dif: 3,
    q: "La «ruptura del cono» (breakup) de un woofer ocurre cuando…",
    opts: [
      "El cono deja de moverse como un pistón rígido.",
      "El puerto se satura por el exceso de nivel alto.",
      "La bobina roza contra las paredes del entrehierro.",
      "El amplificador recorta la señal de entrada fuerte.",
    ],
    ans: 0,
    why: "En su banda baja el cono se mueve como un <b>pistón rígido</b>, pero al subir en frecuencia aparecen modos de flexión del propio cono (breakup): distintas zonas vibran desfasadas, metiendo picos y valles agudos en la respuesta y distorsión. Marca el límite superior útil del driver, por eso se cruza antes. Se combate con materiales rígidos/amortiguados o cruzando por debajo del breakup.",
    src: "Beranek & Mellow, Sound Fields and Transducers",
  },
  {
    id: "fte-doppler",
    cat: "Distorsión", dif: 3,
    q: "La distorsión Doppler en un woofer de vía ancha aparece porque…",
    opts: [
      "El cono que reproduce el grave modula al agudo.",
      "La caja reflex retarda la señal grave un ciclo.",
      "El tweeter y el woofer están desalineados.",
      "El amplificador introduce retardo de grupo.",
    ],
    ans: 0,
    why: "Si un mismo cono reproduce un grave de gran excursión y un agudo a la vez, el movimiento del grave desplaza la fuente del agudo adelante y atrás: eso <b>modula en frecuencia</b> al agudo (efecto Doppler), una forma de intermodulación. Es un argumento a favor de dividir en vías (que el woofer no cargue agudos) y a favor de excursiones moderadas. No viene de la caja, la alineación ni el amplificador.",
    src: "Beranek & Mellow, Sound Fields and Transducers",
  },
  {
    id: "fte-csd-waterfall",
    cat: "Medición", dif: 3,
    q: "Un gráfico cascada (CSD/waterfall) de un monitor revela…",
    opts: [
      "Resonancias que decaen lento tras el impulso.",
      "La directividad horizontal del sistema medido.",
      "La sensibilidad en decibeles por vatio y metro.",
      "El nivel de ruido de fondo de la sala vacía.",
    ],
    ans: 0,
    why: "La cascada muestra cómo el espectro <b>decae en el tiempo</b> tras el impulso: una resonancia (del cono, la caja o un panel) aparece como una «cresta» que persiste después de que el resto ya cayó. Delata almacenamiento de energía que la respuesta de magnitud sola no muestra. Es el equivalente al waterfall modal de una sala, pero para el driver. No mide directividad, sensibilidad ni ruido.",
    src: "Beranek & Mellow, Sound Fields and Transducers · Toole, Sound Reproduction",
  },
  {
    id: "fte-driver-fase-minima",
    cat: "Medición", dif: 3,
    q: "Un altavoz bien diseñado es, en su banda de paso…",
    opts: [
      "De fase mínima, salvo un retardo puro global.",
      "De fase no mínima en toda la banda audible.",
      "Totalmente independiente de fase y magnitud.",
      "De fase aleatoria por las resonancias del cono.",
    ],
    ans: 0,
    why: "En su banda útil, un driver se comporta como sistema de <b>fase mínima</b>: su fase queda determinada por su magnitud, salvo un <b>retardo puro</b> (el tiempo de vuelo). Consecuencia práctica importante: si la respuesta de magnitud es plana, la fase también lo es (descontado el delay), y un EQ de fase mínima puede corregir ambas. Las excepciones son los cruces y ciertas resonancias.",
    src: "Toole, Sound Reproduction · Beranek & Mellow, Sound Fields and Transducers",
  },
  {
    id: "fte-power-response",
    cat: "Directividad", dif: 3,
    q: "La curva de potencia sonora (sound power) de un parlante integra…",
    opts: [
      "Toda la energía radiada en todas las direcciones.",
      "Sólo la respuesta medida sobre el eje directo.",
      "La energía dentro de un cono de más menos 10°.",
      "La reflexión de las paredes de la sala tratada.",
    ],
    ans: 0,
    why: "El sound power suma la energía radiada en <b>todas las direcciones</b> (esfera completa): es lo que alimenta el campo reverberante de la sala. Junto con la respuesta en eje y la listening window forma el «spinorama». Una discontinuidad en la curva de potencia (por un salto de directividad en el cruce) colorea el sonido reflejado aunque el eje mida plano. No es la respuesta en eje ni la de la sala.",
    src: "Toole, Sound Reproduction · ANSI/CTA-2034",
  },
  {
    id: "fte-di-curva",
    cat: "Directividad", dif: 3,
    q: "El índice de directividad (DI) en función de la frecuencia debería ser…",
    opts: [
      "Suave y creciente, sin saltos bruscos.",
      "Plano y nulo en toda la banda audible.",
      "Máximo en graves y mínimo en agudos.",
      "Irregular, con picos y valles marcados.",
    ],
    ans: 0,
    why: "El DI (diferencia entre la respuesta en eje y la potencia total) mide cuán directiva es la fuente. Un buen monitor lo tiene <b>suave y creciendo gradualmente</b> con la frecuencia (naturalmente se vuelve más directivo en agudos), sin <b>saltos</b> — un salto en el DI, típico de un cruce mal integrado, mete un cambio de timbre en el campo reflejado. No puede ser nulo (siempre hay algo de directividad en agudos).",
    src: "Toole, Sound Reproduction · ANSI/CTA-2034",
  },
  {
    id: "fte-preference-score",
    cat: "Directividad", dif: 3,
    q: "El «preference score» de Olive predice la preferencia a partir de…",
    opts: [
      "La suavidad y planitud de las curvas del spinorama.",
      "El precio y la marca del monitor bajo evaluación.",
      "El nivel máximo de SPL que alcanza el parlante.",
      "La opinión de un solo crítico experto reconocido.",
    ],
    ans: 0,
    why: "A partir de escuchas ciegas, Olive halló que la <b>preferencia</b> de los oyentes se predice bien con métricas objetivas del spinorama: qué tan plana y suave es la respuesta en eje y la listening window, y qué tan libres de irregularidades están las curvas de potencia y reflexiones. Correlaciona fuerte con el juicio subjetivo. No depende del precio, el SPL ni de un crítico: es la validación objetiva del enfoque de Toole.",
    src: "Olive (2004) · Toole, Sound Reproduction",
  },
  {
    id: "fte-linkwitz-riley",
    cat: "Diseño de caja", dif: 3,
    q: "Un cruce Linkwitz-Riley se usa porque, en la frecuencia de cruce…",
    opts: [
      "Las dos vías suman plano y en fase (−6 dB cada una).",
      "Cada vía cae −3 dB y suman con un pico de +3 dB.",
      "El tweeter queda desfasado 180° respecto del woofer.",
      "Elimina toda la energía justo en la zona de cruce.",
    ],
    ans: 0,
    why: "El Linkwitz-Riley (dos Butterworth en cascada) cruza a <b>−6 dB</b> con las dos vías <b>en fase</b>: suman a respuesta plana y con el lóbulo principal centrado en el eje. Un Butterworth simple cruza a −3 dB y suma +3 dB con el lóbulo inclinado fuera de eje. Por eso LR (sobre todo LR4) es el estándar en monitores. No cancela energía ni deja las vías en contrafase — al contrario, las alinea.",
    src: "Beranek & Mellow, Sound Fields and Transducers · Linkwitz & Riley (1976)",
  },
  {
    id: "fte-lufs",
    cat: "Niveles", dif: 2,
    q: "La medida de loudness LUFS (EBU R128 / ITU BS.1770)…",
    opts: [
      "Estima la sonoridad percibida, ponderada en frecuencia.",
      "Es sólo el nivel de pico digital de la señal grabada.",
      "Mide el ruido de fondo del cuarto de control usado.",
      "Es idéntica al RMS crudo, sin ninguna ponderación.",
    ],
    ans: 0,
    why: "LUFS mide la <b>sonoridad percibida integrada</b> en el tiempo, con un filtro de ponderación (K-weighting) que imita la respuesta del oído y un gating que ignora los silencios. Es lo que usan las plataformas para normalizar loudness entre temas (−14 LUFS en streaming típico). No es el pico (eso es dBTP/true peak) ni un RMS crudo: por eso dos temas al mismo LUFS «suenan» igual de fuertes.",
    src: "ITU-R BS.1770 · EBU R128",
  },
  {
    id: "fte-true-peak",
    cat: "Niveles", dif: 3,
    q: "El true peak (dBTP), frente al pico de muestra, detecta…",
    opts: [
      "Picos entre muestras que superan 0 dBFS al reconstruir.",
      "El nivel medio de la señal en toda su larga duración.",
      "La distorsión armónica del conversor digital usado.",
      "El ruido de cuantización del formato de 24 bits real.",
    ],
    ans: 0,
    why: "La señal analógica reconstruida entre muestras puede superar el mayor valor de muestra: son los <b>picos intermuestra</b>. El true peak los estima sobremuestreando antes de medir, y por eso se limita a −1 dBTP: un archivo con muestras bajo 0 dBFS igual puede recortar en el D/A o al codificarse a MP3. El pico de muestra solo no los ve. No mide nivel medio, distorsión ni ruido de cuantización.",
    src: "ITU-R BS.1770 · Bob Katz, Mastering Audio",
  },
  {
    id: "fte-mid-side",
    cat: "Corregibilidad", dif: 2,
    q: "La técnica Mid/Side descompone el estéreo en…",
    opts: [
      "Un canal suma (M) y un canal diferencia (S).",
      "El canal izquierdo y el derecho por separado.",
      "Los graves y los agudos de toda la mezcla.",
      "El directo y el reverberante de la señal dada.",
    ],
    ans: 0,
    why: "M/S codifica <b>M = L+R</b> (lo común, el centro) y <b>S = L−R</b> (lo diferente, los lados). Permite procesar el centro y los lados por separado: subir los lados ensancha la imagen, ecualizar sólo el mid limpia la voz, comprimir sólo el side controla la amplitud estéreo. Es reversible (L=M+S, R=M−S). Chequear el canal S revela problemas de fase (lo que se cancelaría en mono).",
    src: "Bob Katz, Mastering Audio · práctica de mezcla",
  },
  {
    id: "fte-haas-paneo",
    cat: "Corregibilidad", dif: 3,
    q: "El paneo por tiempo (efecto Haas en mezcla) corre la imagen porque…",
    opts: [
      "El oído localiza según el canal que llega primero.",
      "El canal retardado se percibe como más fuerte.",
      "El retardo cancela los graves del canal opuesto.",
      "El oído promedia las posiciones de los dos canales.",
    ],
    ans: 0,
    why: "Retrasar un canal unos pocos ms (sin cambiar su nivel) corre la imagen hacia el canal que llega <b>primero</b>: es la precedencia aplicada a la mezcla. Se usa para ensanchar o mover fuentes sin tocar niveles. El riesgo es la <b>compatibilidad mono</b>: al sumar, ese retardo produce un filtro peine. Por eso se usa con cuidado. No es que el canal tardío suene más fuerte ni que cancele graves.",
    src: "Toole, Sound Reproduction · Blauert, Spatial Hearing",
  },
  {
    id: "fte-decorrelacion",
    cat: "Corregibilidad", dif: 3,
    q: "Para ensanchar una fuente en la mezcla sin romper el mono conviene…",
    opts: [
      "Decorrelacionar los canales sin invertir polaridad.",
      "Invertir la polaridad de uno solo de los canales.",
      "Subir mucho el nivel del canal izquierdo solo.",
      "Retrasar un canal más de cien milisegundos enteros.",
    ],
    ans: 0,
    why: "El ancho estéreo se logra <b>decorrelacionando</b> los canales (que se parezcan poco: distintas reflexiones, micro-retardos, doblajes), lo que baja el IACC percibido y agranda la imagen. Invertir la polaridad de un canal «ensancha» pero <b>colapsa a nada en mono</b> (se cancela) y suena raro. Un retardo enorme ya es eco. La decorrelación bien hecha mantiene compatibilidad mono razonable.",
    src: "Blauert, Spatial Hearing · Toole, Sound Reproduction",
  },
  {
    id: "fte-room-gain",
    cat: "Carga de bordes", dif: 3,
    q: "El «room gain» en un recinto chico y cerrado (o un auto)…",
    opts: [
      "Realza los graves muy bajos por presurización.",
      "Atenúa los graves muy bajos por fugas de la sala.",
      "Aplana la respuesta en toda la banda audible.",
      "Sólo afecta a los agudos por absorción del aire.",
    ],
    ans: 0,
    why: "Por debajo del primer modo, un recinto chico y sellado se comporta como una cámara de presión: el woofer «presuriza» el volumen y la respuesta <b>sube</b> hacia lo más grave (típicamente +12 dB/oct bajo cierta frecuencia). Es enorme en autos (graves potentes de sistemas modestos) y notable en salas chicas herméticas. Requiere que la sala sea estanca; las fugas lo debilitan. No es absorción del aire.",
    src: "Toole, Sound Reproduction · Beranek & Mellow, Sound Fields and Transducers",
  },
  {
    id: "fte-dvc-isobarik",
    cat: "Diseño de caja", dif: 3,
    q: "Una configuración isobárica (dos woofers acoplados) permite…",
    opts: [
      "La misma respuesta grave en la mitad del volumen.",
      "El doble de SPL con la misma caja de siempre.",
      "Extender los agudos por encima del cruce alto.",
      "Eliminar la distorsión total del segundo woofer.",
    ],
    ans: 0,
    why: "En isobárico, dos drivers idénticos trabajan en tándem con un pequeño volumen de aire atrapado entre ambos: el par se comporta como un solo driver con el <b>doble de masa y compliance</b>, lo que permite lograr la misma extensión grave en una caja de <b>la mitad</b> del volumen. El precio: dos drivers, más peso y costo, y sin ganancia de SPL. Es un canje tamaño-por-costo, útil donde el volumen es crítico.",
    src: "Beranek & Mellow, Sound Fields and Transducers",
  },
  {
    id: "fte-cardioide-sub-array",
    cat: "Subwoofers", dif: 3,
    q: "Un arreglo de subs en gradiente (end-fire o cardioide) logra dirección…",
    opts: [
      "Sumando adelante y cancelando atrás con retardo.",
      "Subiendo la potencia de todos los subs por igual.",
      "Usando un solo sub muy grande y muy directivo.",
      "Absorbiendo el sonido en la pared trasera dura.",
    ],
    ans: 0,
    why: "Con dos o más subs separados y un <b>retardo</b> (eléctrico o por distancia) elegido, las radiaciones se <b>suman hacia adelante y se cancelan hacia atrás</b> por interferencia: el conjunto se vuelve direccional aunque cada sub sea omni. Sirve para no excitar el fondo del escenario o los modos traseros. Es geometría + timing, no más potencia ni un sub gigante ni absorción.",
    src: "Toole, Sound Reproduction · Low frequency sound field control using CABS — referencias/",
  },
  {
    id: "fte-fase-alineacion-medida",
    cat: "Medición", dif: 3,
    q: "Para alinear el sub con los mains se mide y ajusta hasta que…",
    opts: [
      "En el cruce, las dos fuentes sumen sin caer de nivel.",
      "El sub tenga el mayor SPL posible por sí mismo solo.",
      "El main quede 180° desfasado del subwoofer usado.",
      "El RT60 de la sala baje justo en la banda del cruce.",
    ],
    ans: 0,
    why: "El método correcto: medir main solo, sub solo y la suma en el cruce, y ajustar <b>polaridad, fase/allpass y delay</b> hasta que la suma <b>no tenga un nulo</b> en la zona de cruce (que sume en fase). Un desajuste da el clásico agujero en ~80 Hz que ningún EQ arregla. No se trata de maximizar el SPL del sub ni de desfasarlo 180°, ni tiene que ver con el RT.",
    src: "Toole, Sound Reproduction · práctica de calibración",
  },
  {
    id: "fte-earl-geddes-multisub",
    cat: "Subwoofers", dif: 3,
    q: "El enfoque de Geddes para multisubs propone…",
    opts: [
      "Subs asimétricos en posiciones irregulares.",
      "Subs simétricos y apareados en las esquinas.",
      "Un solo sub potente en el centro de la pared.",
      "Subs sólo detrás de la posición de escucha.",
    ],
    ans: 0,
    why: "Geddes argumenta que ubicar varios subs de forma <b>asimétrica e irregular</b> (no en posiciones simétricas) excita el conjunto de modos de manera más «aleatoria», suavizando la respuesta espacial en la zona de escucha mejor que colocaciones simétricas. Es una variante del principio multisub (bajar la varianza espacial). Contrasta con el enfoque simétrico de Welti; ambos buscan lo mismo por caminos distintos.",
    src: "Geddes; Welti & Devantier (2006) · Toole, Sound Reproduction",
  },

].map((q) => ({ ...q, area: "fuentes" }));
