// ÁREA: Geometría y modos.
//
// REGLA DE ORO: las 4 opciones van del MISMO largo (tolerancia ±5 caracteres).
// Validar con `python check_banco.py`. Ver juego/CONTENIDO.md.

export const GEOMETRIA = [

  // ───────────────────────── Modos ─────────────────────────
  {
    id: "geo-schroeder-sentido",
    cat: "Frecuencia de Schroeder", dif: 2,
    q: "¿Qué separa la frecuencia de Schroeder?",
    opts: [
      "Marca el límite inferior de la audición humana de los graves.",
      "Abajo, campo modal con modos separados; arriba, campo difuso.",
      "Es la frecuencia a la que la sala deja de tener modos propios.",
      "Es el punto donde el RT60 se vuelve constante en frecuencia.",
    ],
    ans: 1,
    why: "Arriba de f_S hay ≳3 modos por ancho de banda modal: se solapan tanto que ya no tiene sentido contarlos de a uno y conviene la acústica estadística. Debajo, cada modo se resuelve individualmente y la respuesta es un peine de picos y valles que depende de la posición. Ojo con el error frecuente: <b>la sala no deja de tener modos arriba de f_S</b> — al contrario, tiene tantos que dejan de importar individualmente.",
    src: "Everest, Master Handbook of Acoustics, p. 325 (frecuencia de corte/crossover)",
  },
  {
    id: "geo-axial-energia",
    cat: "Modos", dif: 2,
    q: "¿Por qué los modos axiales molestan más que los tangenciales y oblicuos?",
    opts: [
      "Son los únicos modos que existen por debajo de los 100 Hz.",
      "Tocan sólo dos paredes: menos absorción por ciclo, más Q.",
      "Tienen más nodos de presión que tangenciales y oblicuos.",
      "Caen siempre en la zona de máxima sensibilidad del oído.",
    ],
    ans: 1,
    why: "Un modo axial rebota entre <b>dos</b> superficies enfrentadas; uno tangencial involucra cuatro y uno oblicuo, las seis. Más superficies tocadas por ciclo = más absorción por ciclo = menos Q y cola más corta. Por eso los axiales dominan la respuesta en graves y son el blanco principal del tratamiento. Suelen estimarse ~3 dB más fuertes que los tangenciales y ~6 dB más que los oblicuos.",
    src: "Everest, Master Handbook of Acoustics, p. 140 (potencia axial/tangencial/oblicuo)",
  },
  {
    id: "geo-tangencial-superficies",
    cat: "Modos", dif: 1,
    q: "Un modo tangencial involucra…",
    opts: [
      "Dos superficies enfrentadas, en incidencia normal.",
      "Cuatro superficies: rebota en dos pares de paredes.",
      "Las seis superficies del recinto rectangular cerrado.",
      "Sólo el piso y el cielorraso, nunca las paredes.",
    ],
    ans: 1,
    why: "La cuenta sale de los índices <code>(nx, ny, nz)</code>: cuántos son distintos de cero. Uno solo → <b>axial</b> (2 superficies). Dos → <b>tangencial</b> (4 superficies). Los tres → <b>oblicuo</b> (las 6). Cuantas más superficies toca por ciclo, más absorción se come y más rápido decae: por eso los oblicuos son los más débiles.",
    src: "Everest, Master Handbook of Acoustics, p. 140",
  },
  {
    id: "geo-cubo",
    cat: "Modos", dif: 2,
    q: "¿Por qué un cubo es la peor forma posible para una sala?",
    opts: [
      "Porque concentra todo el sonido en el centro geométrico.",
      "Los tres ejes coinciden: los modos se apilan (degeneran).",
      "Porque tiene la mayor superficie posible para su volumen.",
      "Porque el RT60 se vuelve muy largo cerca de las esquinas.",
    ],
    ans: 1,
    why: "Con Lx = Ly = Lz, los modos (1,0,0), (0,1,0) y (0,0,1) caen <b>exactamente</b> en la misma frecuencia: están degenerados. En vez de tres resonancias repartidas tenés una sola, tres veces más fuerte, y huecos enormes entre ella y la siguiente. Es el caso patológico que las proporciones recomendadas buscan evitar. Peor aún: la degeneración se repite en todos los armónicos.",
    src: "Everest, Master Handbook of Acoustics, p. 284 (modos degenerados)",
  },
  {
    id: "geo-nodo-escucha",
    cat: "Modos", dif: 2,
    q: "Sentarse justo en un nodo de presión de un modo significa…",
    opts: [
      "Que ese modo se escucha reforzado desde ese punto.",
      "Que ese modo casi no se escucha desde ese punto.",
      "Que el modo desaparece de la sala por completo.",
      "Que la fase de ese modo se invierte al escucharlo.",
    ],
    ans: 1,
    why: "Un nodo es un punto donde la presión de ese modo es ~cero: ahí ese modo es casi inaudible, y en la FRF aparece como un valle profundo. El modo <b>sigue existiendo</b> en la sala — sólo que ese punto no lo ve. De ahí que mover el oyente medio metro cambie tanto la respuesta en graves, y que el primer «tratamiento» de graves siempre sea reubicar oyente y fuentes.",
    src: "Everest, Master Handbook of Acoustics, p. 140",
  },
  {
    id: "geo-fs-volumen",
    cat: "Frecuencia de Schroeder", dif: 2,
    q: "Entre dos salas con el mismo RT60, la más grande tiene…",
    opts: [
      "Una frecuencia de Schroeder más baja que la chica.",
      "Una frecuencia de Schroeder más alta que la chica.",
      "La misma f_S: sólo depende del RT60 de la sala.",
      "Modos más separados entre sí en la banda grave.",
    ],
    ans: 0,
    why: "<code>f_S = 2000·√(RT60/V)</code>: el volumen está en el denominador, así que más V baja f_S. Tiene sentido físico — más volumen significa más modos y más juntos (Weyl va con V·f²), o sea que la sala entra antes en régimen difuso. Es exactamente por esto que las salas chicas sufren: su f_S alta deja buena parte de la música en régimen modal.",
    src: "Everest, Master Handbook of Acoustics, p. 325",
  },

  // ────────────────────── Proporciones y forma ──────────────────────
  {
    id: "geo-ratios-por-que",
    cat: "Proporciones", dif: 2,
    q: "¿Por qué se recomiendan ciertas proporciones de sala (Bolt, Louden, Sepmeyer…)?",
    opts: [
      "Vienen de la proporción áurea y la tradición arquitectónica.",
      "Reparten los modos parejo, sin coincidencias ni huecos grandes.",
      "Minimizan el RT60 de la sala sin tratamiento acústico extra.",
      "Hacen que la sala no desarrolle modos por debajo de 100 Hz.",
    ],
    ans: 1,
    why: "El problema no es que haya modos —siempre los hay— sino que se <b>agolpen</b>. Dos modos en la misma frecuencia dan un pico exagerado; un hueco grande deja notas sin sostén. Las proporciones recomendadas buscan un espaciado parejo en graves. Un cubo es el peor caso: los tres ejes coinciden y triplican cada modo. Ahora la letra chica: son criterios para salas <b>rectangulares, vacías y de paredes rígidas</b>. En la práctica el tratamiento y la carga real de la sala suelen pesar más que dar con el ratio exacto.",
    src: "Everest, Master Handbook of Acoustics, p. 276 · Bolt (1946); Louden (1971)",
  },
  {
    id: "geo-bonello",
    cat: "Proporciones", dif: 3,
    q: "¿Qué evalúa el criterio de Bonello?",
    opts: [
      "Que el RT60 se mantenga plano con la frecuencia en la banda.",
      "Que los modos por tercio de octava no decrezcan ni coincidan.",
      "Que la sala cumpla la proporción áurea en sus tres dimensiones.",
      "Que la absorción esté bien repartida en las seis superficies.",
    ],
    ans: 1,
    why: "Bonello cuenta modos por banda de 1/3 de octava y pide dos cosas: que la curva <b>no baje</b> al subir en frecuencia (un bache = región pobre en modos = notas sin sostén), y que no haya modos coincidentes en las bandas bajas. Es más fino que un ratio suelto, porque mira la distribución completa en vez de tres números.",
    src: "Everest, Master Handbook of Acoustics, p. 348 (The Bonello Criterion) · Bonello (1981)",
  },
  {
    id: "geo-splayed",
    cat: "Forma", dif: 2,
    q: "Inclinar (splay) una pared respecto de la opuesta…",
    opts: [
      "Elimina por completo los modos de ese eje del recinto.",
      "Rompe el flutter, pero los modos siguen existiendo igual.",
      "Baja el RT60 sin necesidad de agregar nada de absorción.",
      "Aumenta la difusión en toda la banda audible de la sala.",
    ],
    ans: 1,
    why: "Inclinar rompe el camino de ida y vuelta que sostiene el flutter echo, y corre las frecuencias modales respecto de la fórmula rectangular. Pero <b>el volumen sigue teniendo modos</b>: sólo que dejan de ser predecibles analíticamente (hay que ir a FEM). Tampoco baja el RT60 — eso depende de V y de A, no de la forma. Ángulos típicos: al menos 1:5 para que sirva de algo.",
    src: "Everest, Master Handbook of Acoustics, cap. 13 · Newell, Recording Studio Design",
  },
  {
    id: "geo-concava",
    cat: "Forma", dif: 1,
    q: "Una superficie cóncava en una sala…",
    opts: [
      "Difunde la energía de manera homogénea en el recinto.",
      "Focaliza el sonido y crea puntos calientes y muertos.",
      "Absorbe bastante más que una superficie plana igual.",
      "Elimina el flutter echo gracias a su curvatura suave.",
    ],
    ans: 1,
    why: "Una cóncava es lo <b>opuesto</b> de un difusor: concentra. Una parábola da un foco nítido; un cilindro, uno difuso pero igual de concentrado. Incluso un polígono cóncavo de 6 u 8 lados se aproxima a un círculo y focaliza. El resultado son zonas con exceso de energía y otras muertas — desastroso para una posición de escucha. Si la arquitectura las impone, se tratan con absorción o difusión encima.",
    src: "Everest, Master Handbook of Acoustics, p. 276 (formas cóncavas/foco)",
  },
  {
    id: "geo-simetria",
    cat: "Forma", dif: 2,
    q: "¿Por qué importa la simetría izquierda-derecha en una sala de control?",
    opts: [
      "Porque reparte los modos de forma mucho más pareja.",
      "Para que las reflexiones sean iguales en ambos oídos.",
      "Porque reduce el RT60 del canal izquierdo del par.",
      "Para que el volumen se distribuya de forma uniforme.",
    ],
    ans: 1,
    why: "La imagen estéreo depende de que L y R lleguen con el mismo patrón de reflexiones. Una asimetría (una puerta de un lado, un placard del otro) corre la imagen y descentra el fantasma central. Es de las cosas más audibles y más baratas de resolver en la etapa de diseño. Ojo con el error: los modos <b>no</b> se reparten mejor por ser simétrica — al contrario, la simetría favorece la degeneración.",
    src: "Newell, Recording Studio Design · Everest, Master Handbook of Acoustics, cap. 19",
  },
  {
    id: "geo-flutter",
    cat: "Forma", dif: 1,
    q: "¿Qué es un flutter echo y entre qué superficies aparece?",
    opts: [
      "Un eco tardío que vuelve desde el fondo de la sala grande.",
      "Repeticiones rápidas entre dos superficies paralelas y duras.",
      "La cola reverberante que sigue al corte de la fuente sonora.",
      "Un refuerzo de graves por acople con las esquinas del recinto.",
    ],
    ans: 1,
    why: "Es un tren de reflexiones periódicas rebotando entre dos superficies paralelas y reflectantes: se oye como un «zing» metálico al aplaudir. Dato práctico útil: alcanza con tratar <b>una</b> de las dos superficies para matarlo — absorber, difundir o inclinar. No hace falta tratar las dos, porque el flutter necesita el ida y vuelta completo.",
    src: "Everest, Master Handbook of Acoustics, p. 494 (flutter → filtro peine)",
  },
  {
    id: "geo-mean-free-path",
    cat: "Campo difuso", dif: 2,
    q: "El camino libre medio (4V/S) de una sala es…",
    opts: [
      "La distancia media entre dos reflexiones consecutivas.",
      "La distancia máxima que recorre el sonido en la sala.",
      "La distancia entre la fuente y la pared más cercana.",
      "La distancia a la que el directo cae 6 dB de nivel.",
    ],
    ans: 0,
    why: "<code>MFP = 4V/S</code> es cuánto viaja en promedio un rayo entre rebote y rebote, en campo difuso. De ahí sale el resto: dividiendo por c obtenés el tiempo medio entre reflexiones, y contando cuántas reflexiones hacen falta para caer 60 dB llegás a la fórmula de Sabine. Es la bisagra entre la visión de rayos y la estadística.",
    src: "Everest, Master Handbook of Acoustics, p. 354 (Mean Free Path)",
  },

  // ───────────────────────── RT60 ─────────────────────────
  {
    id: "geo-sabine-limites",
    cat: "RT60", dif: 3,
    q: "¿Por qué el RT60 es poco confiable en una sala de control chica?",
    opts: [
      "Los micrófonos pierden precisión en recintos de poco volumen.",
      "Supone campo difuso, y en sala chica no se cumple casi nada.",
      "El RT60 sólo está bien definido para salas de más de 1000 m³.",
      "En salas chicas el sonido decae demasiado rápido para medirlo.",
    ],
    ans: 1,
    why: "Sabine y Eyring asumen campo difuso. En una sala chica: (a) debajo de f_S hay pocos modos y el decaimiento es la suma de resonancias con Q distintos, no una exponencial única; (b) la absorción está concentrada (trampas en esquinas, nada en el vidrio); (c) las dimensiones son comparables a λ. El decaimiento se vuelve dependiente de la posición y multi-pendiente. Por eso en salas chicas se mira <b>decaimiento modal por frecuencia</b> (o ETC/waterfall) en vez de un número único.",
    src: "Toole, Sound Reproduction, cap. 13 (Below the Transition Frequency)",
  },
  {
    id: "geo-eyring-cuando",
    cat: "RT60", dif: 2,
    q: "¿Cuándo se separan sensiblemente Eyring y Sabine?",
    opts: [
      "Cuando el volumen supera los 1000 metros cúbicos.",
      "Cuando la absorción media ᾱ es alta, digamos > 0,3.",
      "Cuando la sala tiene forma muy irregular en planta.",
      "Cuando la frecuencia sube por encima de los 2 kHz.",
    ],
    ans: 1,
    why: "Las dos comparten el <code>0,161·V</code> pero difieren en el denominador: Sabine usa <code>S·ᾱ</code> y Eyring <code>−S·ln(1−ᾱ)</code>. Como <code>−ln(1−ᾱ) ≈ ᾱ</code> para ᾱ chico, convergen en salas poco absorbentes. Con ᾱ alto Sabine <b>sobrestima</b>: supone que la energía se absorbe de a poquito, cuando en realidad cada reflexión se come una fracción grande. En el límite ᾱ = 1, Sabine da un RT finito absurdo; Eyring da cero, que es lo correcto.",
    src: "Everest, Master Handbook of Acoustics, p. 160 · Beranek, Acústica, p. 218",
  },
  {
    id: "geo-millington",
    cat: "RT60", dif: 3,
    q: "La fórmula de Millington-Sette conviene cuando…",
    opts: [
      "La absorción está muy dispareja entre superficies.",
      "El recinto es muy grande y el aire absorbe bastante.",
      "Se necesita el RT60 en bandas de un tercio de octava.",
      "La sala tiene paredes no paralelas o bien inclinadas.",
    ],
    ans: 0,
    why: "Sabine y Eyring promedian la absorción en un <code>ᾱ</code> único, lo que asume que un rayo ve «un poco de cada material» en cada rebote. Millington-Sette aplica el logaritmo <b>superficie por superficie</b> (<code>−Σ Sᵢ·ln(1−αᵢ)</code>), lo que respeta mejor una sala con materiales muy distintos. Su rareza: si alguna superficie tiene α = 1, el término se va a infinito y el RT da cero — señal de que ninguna fórmula estadística sirve en casos extremos.",
    src: "Everest, Master Handbook of Acoustics",
  },
  {
    id: "geo-aire-absorcion",
    cat: "RT60", dif: 2,
    q: "La absorción del aire empieza a importar…",
    opts: [
      "En agudos, salas grandes y con humedad relativa baja.",
      "En graves, salas chicas y con humedad relativa alta.",
      "Sólo cuando la temperatura supera los 30 grados.",
      "En toda la banda, si el recinto está presurizado.",
    ],
    ans: 0,
    why: "El aire disipa por relajación molecular, y el efecto crece fuerte con la frecuencia: es despreciable en graves y significativo arriba de ~2 kHz. Como depende del <b>camino recorrido</b>, sólo pesa donde el sonido viaja mucho: salas grandes. Y empeora con humedad baja. Por eso en salas grandes el RT cae en agudos aunque el tratamiento sea plano — y por eso en una sala de control chica se puede ignorar tranquilo.",
    src: "Everest, Master Handbook of Acoustics, p. 203 · ISO 9613-1",
  },
  {
    id: "geo-volumen-rt",
    cat: "RT60", dif: 2,
    q: "Duplicar el volumen manteniendo la misma área de absorción A…",
    opts: [
      "Duplica el RT60: en Sabine, V está en el numerador.",
      "No cambia el RT60, porque A no se modificó en nada.",
      "Baja el RT60 a la mitad por el mayor camino libre.",
      "Sólo cambia la frecuencia de Schroeder, no el RT60.",
    ],
    ans: 0,
    why: "<code>RT60 = 0,161·V/A</code> es lineal en V. Físicamente: más volumen con la misma absorción significa que el sonido recorre más distancia entre rebote y rebote (el camino libre medio 4V/S crece), o sea menos encuentros con material absorbente por segundo, o sea que tarda más en perder 60 dB. Es el mismo motivo por el que una catedral retumba y un placard no.",
    src: "Everest, Master Handbook of Acoustics, p. 159 (ecuación de Sabine)",
  },
  {
    id: "geo-absorcion-distribuida",
    cat: "RT60", dif: 3,
    q: "Sabine supone la absorción repartida. Concentrarla toda en una pared…",
    opts: [
      "Mejora la difusión y hace el campo más homogéneo.",
      "Rompe el supuesto: el RT real difiere del calculado.",
      "No afecta el cálculo mientras A total sea la misma.",
      "Duplica la eficiencia del material absorbente usado.",
    ],
    ans: 1,
    why: "El campo difuso supone que un rayo tiene la misma probabilidad de pegarle a cualquier superficie. Con toda la absorción en una pared, los rayos que viajan paralelos a ella casi no la tocan y sobreviven mucho más: aparecen <b>decaimientos de dos pendientes</b> y modos tangenciales que quedan vivos. El RT medido puede diferir bastante del calculado, aunque el A total coincida.",
    src: "Everest, Master Handbook of Acoustics, p. 160 · Beranek, Acústica, p. 218",
  },
  {
    id: "geo-rt-objetivo",
    cat: "RT60", dif: 1,
    q: "El RT60 objetivo de una sala de control chica suele estar en…",
    opts: [
      "0,2–0,4 s, lo más plano posible con la frecuencia.",
      "0,8–1,2 s, como una sala de estar doméstica típica.",
      "1,5–2,0 s, para darle cuerpo a la cola reverberante.",
      "Menos de 0,05 s: cuanto más muerta, mejor precisión.",
    ],
    ans: 0,
    why: "El valor exacto importa menos que dos cosas: que sea <b>corto</b> y sobre todo que sea <b>parejo con la frecuencia</b>. Una sala con 0,3 s en medios pero 0,8 s en graves suena embarrada aunque el número «promedio» cierre. Y no: más muerta no es mejor — una sala anecoica es agotadora e induce a mezclar con exceso de reverb artificial. Se busca control, no ausencia.",
    src: "Newell, Recording Studio Design · Everest, cap. 19",
  },

  // ─────────────────────── Absorción ───────────────────────
  {
    id: "geo-esquinas",
    cat: "Absorción", dif: 2,
    q: "¿Por qué las trampas de graves se ponen en las esquinas?",
    opts: [
      "Porque es donde sobra lugar y no molestan a la circulación.",
      "Todos los modos tienen máximo de presión ahí, y entra espesor.",
      "El poroso pide máximo de velocidad, y la esquina se lo ofrece.",
      "Porque la esquina concentra más agudos que una pared plana.",
    ],
    ans: 1,
    why: "En una esquina <b>todos</b> los modos tienen antinodo de presión, así que un absorbente ahí ve energía de todos. Pero atención al matiz: un poroso disipa por <b>velocidad</b> de partícula, que es mínima justo contra la pared — la esquina NO es un máximo de velocidad. Lo que la salva es (a) que hay lugar para espesores grandes o para separar el poroso de la pared, llevándolo hacia la región de velocidad alta, y (b) que ve varios modos simultáneamente. La opción que habla de velocidad es la trampa clásica: describe bien la física, pero saca de ahí la conclusión equivocada.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers, cap. 5 · Everest, p. 203 (bass traps)",
  },
  {
    id: "geo-poroso-espesor",
    cat: "Absorción", dif: 2,
    q: "Un poroso montado directo sobre la pared empieza a ser efectivo…",
    opts: [
      "A cualquier frecuencia, si el material tiene un buen NRC.",
      "Cuando su espesor es comparable a λ/4 de esa frecuencia.",
      "A partir de la frecuencia de Schroeder del recinto tratado.",
      "A partir de 1 kHz, sin importar el espesor del material.",
    ],
    ans: 1,
    why: "Un poroso convierte en calor la <b>velocidad</b> de partícula. Contra una pared rígida la velocidad es cero, y su primer máximo está a λ/4. Un material de 10 cm tiene su λ/4 en ~860 Hz y ya casi no hace nada en 80 Hz (donde λ/4 ≈ 1,07 m). De ahí dos trucos: <b>separarlo</b> de la pared con cámara de aire (lo lleva a la zona de velocidad alta sin pagar todo el espesor en material) o usar <b>resonadores</b>, que no dependen de este mecanismo.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers, cap. 5 (Porous absorption), p. 156",
  },
  {
    id: "geo-airgap",
    cat: "Absorción", dif: 2,
    q: "Separar un poroso de la pared dejando cámara de aire…",
    opts: [
      "Mejora los graves sin agregar espesor de material.",
      "Empeora la absorción: el aire refleja la energía.",
      "Sólo sirve si la cámara se rellena con más lana.",
      "No cambia nada: lo que importa es el α del material.",
    ],
    ans: 0,
    why: "Es el truco más rentable del tratamiento de graves. La velocidad de partícula es cero en la pared y máxima a λ/4: dejando aire detrás, el poroso se corre hacia la zona de velocidad alta y trabaja mucho mejor en baja frecuencia, sin pagar el costo de un bloque macizo. Un panel de 10 cm con 10 cm de aire baja bastante más que uno de 10 cm pegado — y menos que uno macizo de 20 cm, pero sale la mitad.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers, cap. 5, p. 156",
  },
  {
    id: "geo-resistividad",
    cat: "Absorción", dif: 3,
    q: "Si la resistividad al flujo de un poroso es demasiado alta…",
    opts: [
      "Absorbe más, porque opone más resistencia al aire.",
      "El material refleja: el aire ya casi no lo penetra.",
      "No influye, mientras el espesor sea el adecuado.",
      "Sólo cambia su comportamiento por encima de 2 kHz.",
    ],
    ans: 1,
    why: "Hay un <b>óptimo</b>, no un «más es mejor». Muy baja: el aire atraviesa sin rozar y disipa poco. Muy alta: la superficie se vuelve reflectante y la onda ni entra. La lana de roca típica (~10–50 kPa·s/m²) está en la zona buena. Consecuencia práctica contraintuitiva: <b>apretar la lana no la mejora</b> — sube la resistividad y la acerca al régimen reflectante.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers, §3.6/cap. 5, p. 95",
  },
  {
    id: "geo-panel-membrana",
    cat: "Absorción", dif: 3,
    q: "La frecuencia de resonancia de un panel/membrana depende de…",
    opts: [
      "La masa por unidad de área y la profundidad de la cámara.",
      "Sólo del espesor del panel de madera que se utilice.",
      "La densidad del material poroso que se ponga detrás.",
      "El área total del panel montado sobre la pared rígida.",
    ],
    ans: 0,
    why: "Es un sistema masa-resorte: la masa es el panel (kg/m²) y el resorte, el aire encerrado. De ahí la aproximación clásica <code>f₀ ≈ 60/√(m·d)</code>, con m en kg/m² y d en metros. Al ser resonante trabaja en una banda <b>angosta</b> alrededor de f₀ — por eso sirve para modos puntuales en graves, donde un poroso necesitaría un espesor imposible. La lana adentro no fija f₀: amortigua y ensancha la banda.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers, cap. 6 (Resonant absorbers), p. 196",
  },
  {
    id: "geo-helmholtz-resonador",
    cat: "Absorción", dif: 2,
    q: "Un resonador de Helmholtz se sintoniza variando…",
    opts: [
      "El volumen de la cavidad y la geometría del cuello.",
      "La densidad del material absorbente de su interior.",
      "El espesor de la pared rígida donde está montado.",
      "La superficie total que expone al campo sonoro.",
    ],
    ans: 0,
    why: "Otro masa-resorte: la masa es el tapón de aire del cuello y el resorte, el aire de la cavidad — <code>f₀ = (c/2π)·√(A/(V·L_eff))</code>. Es la física de soplar una botella. Como el panel-membrana, es de banda angosta y muy eficiente en su frecuencia: ideal para un modo puntual que no se puede mover. La lana adentro amortigua y ensancha, a costa del pico.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers, cap. 6 (Resonant absorbers), p. 196",
  },
  {
    id: "geo-perforado",
    cat: "Absorción", dif: 3,
    q: "Un panel perforado con cámara de aire funciona como…",
    opts: [
      "Un poroso de banda ancha, si la cámara es profunda.",
      "Un resonador de Helmholtz: los agujeros son cuellos.",
      "Un difusor de fase que dispersa las reflexiones.",
      "Una membrana cuya masa es la del panel completo.",
    ],
    ans: 1,
    why: "Cada perforación es el cuello de un Helmholtz y la cámara detrás, la cavidad: el conjunto se sintoniza con el <b>porcentaje de perforación</b>, el diámetro y espesor del agujero, y la profundidad de la cámara. Es el mecanismo de los cielorrasos perforados. Detalle práctico: si el porcentaje de perforación es alto (≳20 %) el panel se vuelve acústicamente casi transparente y lo que absorbe es la lana de atrás.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers, cap. 6 (Resonant absorbers), p. 196",
  },
  {
    id: "geo-membrana-vs-poroso",
    cat: "Absorción", dif: 2,
    q: "Para atacar un modo en 50 Hz en una sala chica, conviene…",
    opts: [
      "Un poroso de 5 cm montado directo sobre la pared.",
      "Un resonador o membrana sintonizado a esa banda.",
      "Un difusor QRD de profundidad moderada en pared.",
      "Alfombra gruesa en el piso y cortinas bien pesadas.",
    ],
    ans: 1,
    why: "A 50 Hz, λ ≈ 6,9 m y λ/4 ≈ 1,7 m: un poroso tendría que ser absurdamente grueso para hacer algo. Un resonador no depende del espesor sino de la <b>sintonía</b> masa-resorte, así que en pocos centímetros ataca la frecuencia que quieras. El precio es la banda angosta: hay que saber a qué frecuencia sintonizarlo, lo que exige medir o simular primero.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers, cap. 6, p. 196 · Newell, Recording Studio Design",
  },
  {
    id: "geo-alpha-mayor-1",
    cat: "Medición", dif: 3,
    q: "¿Por qué un α medido en cámara reverberante puede dar mayor que 1?",
    opts: [
      "Porque el material absorbe más energía de la que le llega.",
      "Por efecto de borde y difracción: el área efectiva es mayor.",
      "Porque la norma ISO 354 admite valores de hasta 1,2 sin más.",
      "Porque el micrófono satura durante la medición del RT60.",
    ],
    ans: 1,
    why: "α > 1 es <b>físicamente imposible</b>: nada absorbe más del 100 % de lo que recibe. El número sale del cálculo, que divide la absorción medida por el área <b>geométrica</b> de la muestra. La difracción en los bordes hace que la muestra capture energía de más allá de su perímetro, así que se comporta como si fuera más grande. Por eso ISO 354 fija tamaño y montaje: para acotar el efecto, no para eliminarlo.",
    src: "UNE-EN ISO 354:2004 — referencias/ · Cox & D'Antonio, §3.4 (cámara reverberante), p. 84",
  },
  {
    id: "geo-iso354",
    cat: "Medición", dif: 2,
    q: "¿Qué mide el ensayo de ISO 354 en cámara reverberante?",
    opts: [
      "El coeficiente de absorción con incidencia aleatoria.",
      "El coeficiente a incidencia normal, en tubo de ondas.",
      "La impedancia acústica compleja de la superficie dada.",
      "El coeficiente de dispersión (scattering) de un panel.",
    ],
    ans: 0,
    why: "Se mide el RT de la cámara vacía y con la muestra, y se despeja la absorción por Sabine: el resultado es <code>α_s</code> con <b>incidencia aleatoria</b>, que es el régimen del campo difuso. Es el dato que usan las tablas de materiales y el que corresponde meter en un cálculo de RT. No confundir con el α del tubo de impedancia, que es a incidencia normal y da valores distintos.",
    src: "UNE-EN ISO 354:2004 — referencias/ · Cox & D'Antonio, §3.4, p. 84",
  },
  {
    id: "geo-tubo-kundt",
    cat: "Medición", dif: 2,
    q: "El tubo de impedancia (Kundt) mide α con…",
    opts: [
      "Incidencia aleatoria, como en una cámara reverberante.",
      "Incidencia normal: sólo vale con ondas perpendiculares.",
      "Incidencia rasante, típica de los modos tangenciales.",
      "Incidencia a 45 grados, promediada en tercio de octava.",
    ],
    ans: 1,
    why: "El tubo impone una onda plana viajando derecho contra la muestra: da <code>α₀</code> a <b>incidencia normal</b>. Es barato, rápido y necesita una muestra chica, pero <b>no es el número que va en un cálculo de RT</b>, donde el campo es difuso. Suele ser bastante menor que el α de ISO 354. Su fuerte es otro: permite obtener la impedancia compleja de superficie, que es justo lo que pide un modelo FEM.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers, §3.6, p. 95 · ISO 10534",
  },
  {
    id: "geo-nrc-saa",
    cat: "Medición", dif: 2,
    q: "El NRC de un material es…",
    opts: [
      "El promedio de α en 250, 500, 1000 y 2000 Hz redondeado.",
      "El coeficiente de absorción medido a 1 kHz exactamente.",
      "El promedio de α sobre las 18 bandas de tercio de octava.",
      "La absorción total del material expresada en m² sabine.",
    ],
    ans: 0,
    why: "Promedia sólo cuatro bandas medias y redondea al 0,05 más cercano: es <b>ciego en graves</b>. Un panel con NRC 0,95 puede no hacer literalmente nada en 80 Hz, que es donde está tu problema en una sala chica. El SAA (ASTM C423) promedia 12 bandas de 1/3 de octava entre 200 y 2500 Hz — algo mejor, pero tampoco llega a graves. Moraleja: en salas chicas, mirá <b>α por banda</b>, nunca un número resumen.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers · ASTM C423",
  },

  // ─────────────────────── Difusión ───────────────────────
  {
    id: "geo-qrd-ancho-banda",
    cat: "Difusión", dif: 3,
    q: "En un difusor QRD, el ancho de banda de trabajo lo fijan…",
    opts: [
      "La profundidad máxima (grave) y el ancho de pozo (agudo).",
      "Sólo el número primo que se elija para armar la secuencia.",
      "El tipo de madera con que se construyen los separadores.",
      "La distancia a la que se ubique el oyente frente al panel.",
    ],
    ans: 0,
    why: "El pozo más profundo fija la frecuencia <b>más baja</b> que puede difundir (necesita ~λ/4 de profundidad), y el ancho del pozo fija la <b>más alta</b>: cuando λ se vuelve comparable al ancho, el panel deja de comportarse como difusor y refleja como una superficie plana. El número primo determina la <i>secuencia</i> de profundidades (y con eso la calidad de la dispersión), pero no los límites de la banda.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers",
  },
  {
    id: "geo-scattering-vs-diffusion",
    cat: "Difusión", dif: 3,
    q: "Los coeficientes de scattering y de difusión son…",
    opts: [
      "Sinónimos: miden lo mismo con distinta normalización.",
      "Distintos: uno mide cuánta energía sale del especular.",
      "El mismo dato, uno en dB y el otro adimensional puro.",
      "Dos formas distintas de medir la absorción del panel.",
    ],
    ans: 1,
    why: "El de <b>scattering</b> (ISO 17497-1) es la fracción de energía que <i>no</i> se refleja especularmente: un número por banda, pensado para alimentar software de rayos. El de <b>difusión</b> (AES-4id) mide qué tan <i>uniforme</i> es la dispersión en el hemisferio. Son cosas distintas: un panel puede tener scattering alto y difusión pobre si manda toda la energía a una única dirección no especular. Para elegir un difusor mirás difusión; para simular, scattering.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers, §4.4–4.5, p. 130–135 · ISO 17497-1; AES-4id",
  },
  {
    id: "geo-difusor-distancia",
    cat: "Difusión", dif: 3,
    q: "Un difusor QRD puesto muy cerca del oyente…",
    opts: [
      "Funciona mejor: la energía difusa llega antes al oyente.",
      "No alcanza a formar el campo difuso; hay que alejarlo.",
      "Se comporta exactamente igual a cualquier distancia.",
      "Aumenta su ancho de banda útil por estar más cerca.",
    ],
    ans: 1,
    why: "Un difusor funciona porque las ondas que salen de cada pozo, con sus distintos retardos, <b>se suman</b> en el aire y arman un frente disperso. Eso necesita distancia (campo lejano): la regla habitual es al menos ~3 veces la λ más baja de diseño. Demasiado cerca oís los pozos como fuentes individuales, con su propia coloración, en vez de un campo difuso. Es un error frecuente en salas chicas, donde justamente no sobra distancia.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers",
  },

  // ─────────────────── Construcción ───────────────────
  {
    id: "geo-sala-dentro-sala",
    cat: "Construcción", dif: 2,
    q: "Una construcción «sala dentro de sala» resuelve…",
    opts: [
      "El aislamiento hacia afuera, no la acústica interior.",
      "Los modos internos, porque desacopla bien las paredes.",
      "El RT60 interno, que baja gracias a la doble estructura.",
      "El SBIR, porque aleja los monitores de la pared trasera.",
    ],
    ans: 0,
    why: "Es la confusión más común entre estudiantes: <b>aislamiento ≠ acústica interna</b>. Una caja flotante desacoplada resuelve que no se escuche afuera (y que no entre ruido), atacando la transmisión estructural. Pero adentro seguís teniendo exactamente los mismos modos, el mismo RT y el mismo SBIR, que se tratan con absorción, difusión y geometría. Son dos problemas independientes, con dos presupuestos independientes.",
    src: "Newell, Recording Studio Design · Hopkins, Sound Insulation",
  },
  {
    id: "geo-puerta-ventana",
    cat: "Construcción", dif: 2,
    q: "Una ventana de vidrio grande en una sala de control…",
    opts: [
      "Es acústicamente neutra: el vidrio no tiene α propio.",
      "Refleja casi todo en medios y agudos; hay que compensar.",
      "Absorbe graves como membrana, y con eso ya alcanza.",
      "Difunde el sonido por las irregularidades del vidrio.",
    ],
    ans: 1,
    why: "El vidrio es duro, liso y pesado: en medios y agudos refleja prácticamente todo (α ≈ 0,03–0,05) y suele ser una de las primeras reflexiones más problemáticas hacia la posición de escucha. La letra chica: en <b>graves</b> sí trabaja algo como membrana (un panel grande de vidrio flexa), pero es un aporte modesto e imposible de sintonizar. Se compensa con geometría — inclinarla — o tratando las superficies vecinas.",
    src: "Newell, Recording Studio Design · Everest, cap. 19",
  },

  // ═══════════════════════ TANDA 2 (nuevas) ═══════════════════════
  {
    id: "geo-densidad-modal-graves",
    cat: "Modos", dif: 2,
    q: "¿Por qué en graves hay «pocos» modos y muy separados?",
    opts: [
      "Porque la sala absorbe casi toda la energía grave.",
      "La densidad crece con f²: abajo hay pocos por banda.",
      "Porque los modos graves se cancelan de a pares.",
      "Porque el oído no percibe los modos bajo 100 Hz.",
    ],
    ans: 1,
    why: "La densidad de modos crece con <b>f²</b> (Weyl): a 40 Hz hay poquísimos por banda y quedan bien separados, cada uno audible como un pico o un valle. Al subir en frecuencia se agolpan hasta solaparse (frecuencia de Schroeder). Por eso el problema modal es un fenómeno de <b>graves</b>: no es que la sala los absorba ni que se cancelen, es que hay tan pocos que no se promedian.",
    src: "Everest, Master Handbook of Acoustics · Kuttruff, Room Acoustics",
  },
  {
    id: "geo-sala-larga",
    cat: "Forma", dif: 2,
    q: "En una sala muy larga y angosta, el problema típico es…",
    opts: [
      "Exceso de difusión en el eje más largo del cuarto.",
      "Un modo axial grave muy fuerte en el eje largo.",
      "La falta total de modos en el eje corto del cuarto.",
      "Un RT60 demasiado corto en la banda de los agudos.",
    ],
    ans: 1,
    why: "El eje largo tiene el modo axial fundamental más <b>grave</b> (<code>f = c/2L</code>), y al ser el más separado del resto suele quedar aislado y muy audible como una resonancia en una nota puntual. Además su serie de armónicos es densa. Por eso las proporciones buscan que ningún eje sea desproporcionadamente largo: no es que falten modos en el eje corto, es que sobra energía en uno del eje largo.",
    src: "Everest, Master Handbook of Acoustics · Bolt (1946)",
  },
  {
    id: "geo-primera-reflexion",
    cat: "Reflexiones", dif: 2,
    q: "El «truco del espejo» sirve para…",
    opts: [
      "Medir el RT60 de la sala con un espejo y un láser.",
      "Ubicar los puntos de primera reflexión en las paredes.",
      "Calcular la frecuencia de Schroeder desde la geometría.",
      "Detectar los nodos de presión de los modos axiales.",
    ],
    ans: 1,
    why: "Un ayudante desliza un espejo por la pared lateral mientras vos, en la posición de escucha, mirás: donde ves reflejado el <b>monitor</b>, ahí pega la primera reflexión y ahí va el panel absorbente. Es el método práctico para colocar el tratamiento de reflexiones tempranas sin medir nada. No tiene que ver con RT, Schroeder ni nodos.",
    src: "Everest, Master Handbook of Acoustics · Newell, Recording Studio Design",
  },
  {
    id: "geo-rt-desparejo",
    cat: "RT60", dif: 2,
    q: "Una sala con RT60 corto en medios pero largo en graves suena…",
    opts: [
      "Brillante y con exceso de definición en la voz.",
      "Embarrada: la cola grave tapa el resto del sonido.",
      "Perfectamente neutra si el promedio da bajo igual.",
      "Con exceso de agudos y sin cuerpo en los graves.",
    ],
    ans: 1,
    why: "El promedio engaña: lo que importa es que el RT sea <b>parejo con la frecuencia</b>. Una cola grave larga (modos con Q alto sin tratar) enturbia la mezcla y hace difícil juzgar el bajo, aunque el número «promedio» cierre. Por eso el tratamiento de graves —trampas, resonadores— busca bajar el RT de esa banda para emparejar la curva, no el valor medio.",
    src: "Newell, Recording Studio Design · Everest, Master Handbook of Acoustics",
  },
  {
    id: "geo-aislar-vs-absorber",
    cat: "Construcción", dif: 2,
    q: "Aislar acústicamente una sala es lo mismo que…",
    opts: [
      "Tratarla con absorción: ambos bajan el ruido interno.",
      "Nada que ver: aislar es que no pase el sonido afuera.",
      "Difundirla: repartir la energía de forma homogénea.",
      "Ecualizarla: corregir la respuesta en frecuencia.",
    ],
    ans: 1,
    why: "Son dos problemas <b>independientes</b>, y confundirlos es el error más caro. <b>Aislar</b> (que no entre/salga sonido) se resuelve con masa, desacople y hermeticidad. <b>Absorber</b> (controlar la acústica interna: RT, reflexiones) se resuelve con paneles y trampas. Poner mucha espuma no aísla nada, y una pared masiva no mejora la acústica interna. Dos presupuestos, dos técnicas.",
    src: "Hopkins, Sound Insulation · Newell, Recording Studio Design",
  },
  {
    id: "geo-ley-masa",
    cat: "Aislamiento", dif: 3,
    q: "Según la ley de masa, al duplicar la masa de una pared el aislamiento…",
    opts: [
      "Sube unos 6 dB por octava y por duplicación de masa.",
      "Se duplica en decibeles respecto del valor anterior.",
      "No cambia: depende del material, no de la masa total.",
      "Baja, porque la pared pesada transmite más vibración.",
    ],
    ans: 0,
    why: "La ley de masa da ~<b>6 dB</b> más de aislamiento por cada <b>duplicación</b> de masa superficial (y otros 6 por octava de frecuencia). Es un rendimiento decreciente: llegar a mucho aislamiento a fuerza de masa es carísimo y pesado. Por eso, pasado cierto punto, conviene el sistema <b>masa-resorte-masa</b> (doble pared), que rinde mucho más por kilo que seguir engrosando una sola hoja.",
    src: "Hopkins, Sound Insulation · Beranek, Acústica",
  },
  {
    id: "geo-doble-pared",
    cat: "Aislamiento", dif: 3,
    q: "Una doble pared con cámara de aire tiene una frecuencia donde el aislamiento…",
    opts: [
      "Sube mucho: la cámara refuerza las dos hojas juntas.",
      "Cae: es la resonancia masa-resorte-masa del sistema.",
      "Es infinito: las dos hojas cancelan la transmisión.",
      "No existe: la doble pared aísla igual en toda banda.",
    ],
    ans: 1,
    why: "Las dos hojas (masas) y el aire encerrado (resorte) forman un resonador con una <b>f₀</b> donde el aislamiento se desploma — por debajo de ella la doble pared aísla <i>peor</i> que una sola equivalente. Se diseña para poner esa f₀ debajo de la banda de interés (cámara ancha, hojas pesadas, lana adentro para amortiguar). Arriba de f₀ el sistema rinde mucho más que la ley de masa.",
    src: "Hopkins, Sound Insulation · Fahy, Sound and Structural Vibration",
  },
  {
    id: "geo-coincidencia",
    cat: "Aislamiento", dif: 3,
    q: "La frecuencia de coincidencia de un panel produce…",
    opts: [
      "Un pico de aislamiento por la rigidez del material.",
      "Un bajón de aislamiento: la flexión iguala al aire.",
      "Una resonancia grave que refuerza la cámara de aire.",
      "Un aumento del RT60 en la banda de los medios altos.",
    ],
    ans: 1,
    why: "A la frecuencia de coincidencia, la longitud de onda de flexión del panel iguala la del sonido en el aire a incidencia rasante: el panel se acopla eficientísimo con el aire y el aislamiento se <b>desploma</b> (coincidence dip). Depende del espesor y la rigidez: paneles rígidos y gruesos la tienen en medios (mala zona). Por eso a veces conviene un panel más flexible o dos capas distintas que no coincidan.",
    src: "Hopkins, Sound Insulation · Fahy, Sound and Structural Vibration",
  },
  {
    id: "geo-flanking",
    cat: "Aislamiento", dif: 2,
    q: "La transmisión por flancos (flanking) es…",
    opts: [
      "Sonido que pasa por caminos indirectos, no la pared.",
      "La absorción extra que aportan los bordes del panel.",
      "La reflexión rasante en las paredes laterales duras.",
      "El refuerzo de graves en las esquinas de la sala.",
    ],
    ans: 0,
    why: "El sonido no sólo cruza la pared que separa dos salas: viaja por <b>caminos indirectos</b> — piso, cielorraso, conductos, cañerías, la estructura misma. Podés tener una pared perfecta y aun así oír al vecino porque el sonido «rodea» por el flanco. Por eso el aislamiento serio exige desacoplar toda la envolvente, no sólo la pared obvia: es el motivo de la construcción «sala dentro de sala».",
    src: "Hopkins, Sound Insulation",
  },
  {
    id: "geo-piso-flotante",
    cat: "Aislamiento", dif: 2,
    q: "Un piso flotante sirve para…",
    opts: [
      "Absorber los graves de la sala por resonancia.",
      "Desacoplar la estructura y cortar la vía sólida.",
      "Difundir las reflexiones del piso hacia arriba.",
      "Aumentar la masa del piso para bajar su modo.",
    ],
    ans: 1,
    why: "El piso flotante apoya la losa sobre elementos elásticos (resortes, neopreno, lana densa), creando un sistema masa-resorte que <b>corta la transmisión estructural</b> de vibración hacia el resto del edificio. Es la contraparte inferior de la caja desacoplada. Ojo: mal calculado (resorte muy duro), su f₀ queda alta y deja pasar justo lo que querías frenar.",
    src: "Hopkins, Sound Insulation · Fahy, Sound and Structural Vibration",
  },
  {
    id: "geo-sellado-fugas",
    cat: "Aislamiento", dif: 2,
    q: "Una rendija sin sellar en una pared muy aislante…",
    opts: [
      "No importa: la masa de la pared compensa la fuga.",
      "Arruina el aislamiento: el aire filtra el sonido.",
      "Mejora la ventilación sin afectar la acústica.",
      "Sólo deja pasar graves, que igual no se aíslan.",
    ],
    ans: 1,
    why: "El aislamiento es tan bueno como su punto más débil: una fuga de aire es una fuga de sonido. Una rendija bajo una puerta puede tirar abajo el aislamiento de una pared de 60 dB, porque el sonido pasa <b>directo</b> por el aire sin cruzar masa. Por eso las puertas acústicas llevan burletes y umbral sellado, y todo penetración (caño, enchufe) se sella. La hermeticidad no es un detalle: es la mitad del trabajo.",
    src: "Hopkins, Sound Insulation · Newell, Recording Studio Design",
  },
  {
    id: "geo-nc-hvac",
    cat: "Ruido de fondo", dif: 2,
    q: "Las curvas NC (Noise Criteria) sirven para…",
    opts: [
      "Especificar el ruido de fondo máximo tolerable.",
      "Medir el coeficiente de absorción por banda.",
      "Definir el RT60 objetivo de una sala de control.",
      "Calibrar el nivel de escucha de los monitores.",
    ],
    ans: 0,
    why: "Las curvas NC ponen un techo al <b>ruido de fondo</b> (típicamente del HVAC) por banda de octava, ponderado según la sensibilidad del oído. Un estudio pide NC-15 a NC-25: muy silencioso. Importa porque el ruido de fondo enmascara las colas y el detalle bajo, y arruina las grabaciones. Se logra con conductos anchos y lentos, silenciadores y equipos alejados — no con tratamiento acústico.",
    src: "Everest, Master Handbook of Acoustics · Newell, Recording Studio Design",
  },
  {
    id: "geo-difusor-primo",
    cat: "Difusión", dif: 3,
    q: "En un difusor QRD, ¿por qué la secuencia usa un número primo?",
    opts: [
      "Porque los primos son más fáciles de cortar en madera.",
      "La secuencia de residuos cuadráticos dispersa parejo.",
      "Porque un primo hace el difusor absorbente y difuso.",
      "Porque baja la frecuencia mínima que puede difundir.",
    ],
    ans: 1,
    why: "Las profundidades salen de <code>n² mod N</code> con N primo: esa secuencia de <b>residuos cuadráticos</b> garantiza un espectro de difusión plano, o sea que la energía se reparte pareja en muchas direcciones y órdenes. Con N no primo aparecen direcciones favorecidas y huecos. El primo no cambia la banda (eso lo fijan profundidad y ancho de pozo) ni agrega absorción: define la <i>calidad</i> de la dispersión.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers · Schroeder (1975)",
  },
  {
    id: "geo-difusor-2d",
    cat: "Difusión", dif: 2,
    q: "Un difusor 2D (tipo skyline), frente a uno 1D (de pozos)…",
    opts: [
      "Dispersa en un solo plano, como el 1D pero más ancho.",
      "Dispersa en dos planos: hemisferio, no sólo un abanico.",
      "Sólo absorbe, porque los bloques cierran los pozos.",
      "Funciona a más baja frecuencia con el mismo tamaño.",
    ],
    ans: 1,
    why: "El QRD clásico (1D) tiene pozos en tiras: dispersa en <b>un plano</b> (un abanico horizontal, por ejemplo). El difusor 2D usa bloques de alturas variables y dispersa en <b>los dos planos</b> a la vez, cubriendo un hemisferio. Se elige según lo que necesites: 1D para controlar reflexiones laterales en un plano, 2D para difusión general. El 2D no baja la frecuencia mínima ni absorbe más.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers",
  },
  {
    id: "geo-absorcion-broadband",
    cat: "Absorción", dif: 2,
    q: "Para absorción de banda ancha que llegue a graves hace falta…",
    opts: [
      "Un panel fino con la mayor densidad de material.",
      "Espesor grande, o separación de la pared con cámara.",
      "Un resonador sintonizado a una única frecuencia baja.",
      "Una superficie dura y lisa que refleje los agudos.",
    ],
    ans: 1,
    why: "Un poroso trabaja donde su espesor es comparable a λ/4. Para cubrir <b>banda ancha hasta graves</b> necesitás mucho espesor (la λ/4 de 100 Hz es ~0,85 m) o separarlo de la pared con cámara de aire, que lo lleva a la zona de velocidad alta sin gastar todo en material. Apretar un panel fino y denso no ayuda: sube la resistividad al régimen reflectante. El resonador es lo opuesto: banda angosta.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers",
  },
  {
    id: "geo-cortina-absorcion",
    cat: "Absorción", dif: 1,
    q: "Una cortina pesada colgada frente a una pared absorbe sobre todo…",
    opts: [
      "Los graves, por la masa de la tela colgante.",
      "Los agudos y medios; poco y nada en graves.",
      "Toda la banda por igual si es bien gruesa.",
      "Sólo la banda de la voz, entre 300 y 3000 Hz.",
    ],
    ans: 1,
    why: "La tela es un poroso fino: absorbe donde su espesor y su separación de la pared son comparables a λ/4, o sea <b>medios y agudos</b>. En graves (λ de metros) es casi transparente. Sirve para domar flutter y brillo, no para tratar modos. El error clásico es «llené de cortinas y sigo con problemas de graves»: las cortinas nunca fueron a atacar ese rango.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers · Everest",
  },
  {
    id: "geo-resonador-banda",
    cat: "Absorción", dif: 2,
    q: "Comparado con un poroso, un resonador (membrana/Helmholtz)…",
    opts: [
      "Absorbe en banda ancha, pero sólo en agudos.",
      "Absorbe en banda angosta, sintonizado a una f₀.",
      "No absorbe: sólo difunde la energía incidente.",
      "Absorbe más cuanto más fino sea el material.",
    ],
    ans: 1,
    why: "El resonador es un sistema masa-resorte con una <b>f₀</b> propia: absorbe mucho en una banda <i>angosta</i> alrededor de esa frecuencia, y poco fuera. Por eso sirve para un modo puntual en graves que un poroso no alcanzaría sin un espesor enorme. El precio es que hay que saber a qué sintonizarlo. La lana adentro ensancha la banda y baja el pico. Un poroso, al revés, es de banda ancha pero flojo en graves.",
    src: "Cox & D'Antonio, Acoustic Absorbers and Diffusers · Everest",
  },
  {
    id: "geo-ratios-limite",
    cat: "Proporciones", dif: 2,
    q: "Los ratios de sala recomendados asumen un recinto…",
    opts: [
      "Ya tratado, con absorción repartida en las paredes.",
      "Rectangular, vacío y de paredes rígidas ideales.",
      "De cualquier forma, mientras el volumen sea correcto.",
      "Con los monitores empotrados en la pared frontal.",
    ],
    ans: 1,
    why: "Las fórmulas modales y los ratios (Bolt, Louden, Sepmeyer) valen para una <b>caja rectangular, vacía y de paredes perfectamente rígidas</b>. En la sala real, el mobiliario, el tratamiento y la impedancia finita de las paredes corren y amortiguan los modos. Por eso el ratio es una buena base de diseño, pero no una garantía: dos salas con el mismo ratio pueden sonar distinto según cómo estén tratadas y cargadas.",
    src: "Everest, Master Handbook of Acoustics · Bolt (1946); Louden (1971)",
  },
  {
    id: "geo-vibracion-reradiacion",
    cat: "Construcción", dif: 3,
    q: "Una pared liviana (placa de yeso) frente al campo grave de la sala…",
    opts: [
      "Refleja el grave perfectamente, como una rígida.",
      "Vibra y re-irradia: absorbe algo de grave al flexar.",
      "Difunde el grave en muchas direcciones distintas.",
      "No interactúa: el grave la atraviesa sin tocarla.",
    ],
    ans: 1,
    why: "Una superficie liviana y grande <b>flexa</b> con la presión grave: se comporta como un absorbente de membrana no intencional, disipando algo de energía en baja frecuencia (por eso una sala de placa de yeso suele tener menos problemas de graves que una de hormigón). Es acople vibroacústico: la pared no es rígida, vibra y re-irradia. La contracara es que esa misma vibración transmite sonido al otro lado.",
    src: "Fahy, Sound and Structural Vibration · Everest, Master Handbook of Acoustics",
  },

].map((q) => ({ ...q, area: "geometria" }));
