// ÁREA: Numérica y FEM.
//
// REGLA DE ORO: las 4 opciones van del MISMO largo (tolerancia ±5 caracteres).
// Validar con `python check_banco.py`. Ver juego/CONTENIDO.md.

export const NUMERICA = [

  // ───────────────────── Formulación ─────────────────────
  {
    id: "num-helmholtz",
    cat: "Formulación", dif: 2,
    q: "¿Qué ecuación gobierna el campo de presión armónico en el aire de un recinto?",
    opts: [
      "La ecuación de onda en el tiempo, ∂²p/∂t² = c²∇²p.",
      "La ecuación de Helmholtz, ∇²p + k²p = −iωρ₀·q(x).",
      "La ecuación de Laplace, ∇²p = 0, con k = ω/c fijo.",
      "La ecuación de Poisson con fuente, ∇²p = −ρ/ε₀.",
    ],
    ans: 1,
    why: "Helmholtz es la forma <b>frecuencial</b> de la ecuación de onda: se obtiene asumiendo dependencia temporal <code>e^{iωt}</code>, lo que convierte <code>∂²/∂t²</code> en <code>−ω²</code>. La ecuación de onda en el tiempo no está «mal» como física — es la misma ecuación antes de pasar a frecuencia — pero no es la que se resuelve cuando calculás modos o una FRF.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §1.1 (ec. 1.3) · FEM for Acoustics",
  },
  {
    id: "num-forma-debil",
    cat: "Formulación", dif: 3,
    q: "La forma débil de Helmholtz se obtiene…",
    opts: [
      "Multiplicando por una función de prueba e integrando.",
      "Derivando dos veces la ecuación original completa.",
      "Discretizando el dominio en elementos finitos chicos.",
      "Aplicando la transformada de Fourier a la ecuación.",
    ],
    ans: 0,
    why: "Se multiplica por una función de prueba, se integra sobre el dominio y se integra por partes. El nombre viene de que se le pide <b>menos</b> a la solución: la forma fuerte exige que p sea dos veces derivable en todo punto; la débil, sólo una vez y en sentido integral. Eso es justamente lo que permite usar funciones lineales a trozos, que no tienen segunda derivada. La discretización viene después, y es un paso aparte.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §2.2 (forma débil)",
  },
  {
    id: "num-natural-esencial",
    cat: "Formulación", dif: 3,
    q: "¿Por qué la pared rígida es una condición de borde «natural» en Galerkin?",
    opts: [
      "Porque es la única condición que impone la naturaleza.",
      "El término de frontera se anula solo, sin tocar K ni M.",
      "Porque toda pared real es naturalmente bastante rígida.",
      "Porque se cumple por casualidad al discretizar el aire.",
    ],
    ans: 1,
    why: "Al integrar por partes aparece un término de frontera <code>∫v·(∂p/∂n)dS</code> que se anula solo cuando <code>∂p/∂n = 0</code>. Las condiciones <b>naturales</b> se satisfacen así, sin hacer nada; las <b>esenciales</b> (Dirichlet, p = 0) hay que imponerlas explícitamente en el espacio de prueba. Por eso un solver modal con paredes rígidas es el caso más simple: ensamblás K y M y resolvés el problema generalizado sin restricciones.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §2.2",
  },
  {
    id: "num-funciones-forma",
    cat: "Formulación", dif: 2,
    q: "Las funciones de forma de un elemento finito…",
    opts: [
      "Interpolan el campo entre los nodos del elemento.",
      "Son la solución exacta dentro de cada elemento.",
      "Definen la geometría, nunca el campo de presión.",
      "Sólo existen en elementos de orden cuadrático.",
    ],
    ans: 0,
    why: "Son la base del espacio de aproximación: dentro del elemento, el campo se escribe como <code>p(x) = Σ Nᵢ(x)·pᵢ</code>, donde <code>pᵢ</code> son los valores nodales. Valen 1 en su nodo y 0 en los demás. Toda la precisión del método depende de qué tan bien esa base puede imitar la solución real — y de ahí sale la regla de 6–10 elementos por longitud de onda para funciones lineales.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §2.2 (hat functions)",
  },
  {
    id: "num-isoparametrico",
    cat: "Formulación", dif: 3,
    q: "Un elemento isoparamétrico usa…",
    opts: [
      "Las mismas funciones para geometría y para campo.",
      "Funciones distintas para geometría y para campo.",
      "Sólo funciones lineales, nunca de mayor orden.",
      "Coordenadas globales, sin transformación alguna.",
    ],
    ans: 0,
    why: "«Iso-paramétrico» = mismos parámetros para las dos cosas: las mismas <code>Nᵢ</code> que interpolan la presión mapean el elemento de referencia al elemento real y deformado. La ventaja es enorme: permite elementos curvos y distorsionados usando una única maquinaria, e integrar siempre sobre el elemento de referencia. El precio es que hace falta el Jacobiano del mapeo, y ahí aparecen los problemas de calidad de malla.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-numero-onda",
    cat: "Formulación", dif: 1,
    q: "El número de onda k = ω/c en la ecuación de Helmholtz…",
    opts: [
      "Fija cuántas oscilaciones hay en cada metro.",
      "Es la velocidad del sonido dentro del medio.",
      "Mide la absorción de las superficies rígidas.",
      "Sólo aparece en el dominio del tiempo real.",
    ],
    ans: 0,
    why: "<code>k = ω/c = 2π/λ</code> es la frecuencia <b>espacial</b>: cuántos radianes de fase avanza la onda por metro. Es el parámetro que gobierna todo el problema numérico — la dificultad de un cálculo de Helmholtz no depende de la frecuencia en sí, sino del producto <code>k·L</code> (cuántas longitudes de onda entran en el dominio). Un problema con kL grande es duro, sea en aire o en agua.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §1.1",
  },

  // ───────────────────── Condiciones de borde ─────────────────────
  {
    id: "num-pared-rigida",
    cat: "Condiciones de borde", dif: 2,
    q: "«Pared rígida» significa físicamente que…",
    opts: [
      "La presión acústica se anula sobre toda la superficie.",
      "La velocidad normal es cero: ∂p/∂n = 0 en la pared.",
      "La impedancia acústica de la pared es exactamente cero.",
      "La energía incidente se absorbe de forma instantánea.",
    ],
    ans: 1,
    why: "Rígida = el aire no puede moverse perpendicular a la pared. Como <code>v_n ∝ ∂p/∂n</code> en régimen armónico, se traduce en gradiente normal nulo — y por eso la pared es un <b>antinodo de presión</b>. La opción «la presión se anula» describe el borde opuesto: superficie libre, impedancia cero, como el extremo abierto de un tubo.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §2.2",
  },
  {
    id: "num-impedancia-borde",
    cat: "Condiciones de borde", dif: 3,
    q: "Una condición de borde de impedancia en FEM…",
    opts: [
      "Modela una pared absorbente con su Z compleja.",
      "Es lo mismo que una pared perfectamente rígida.",
      "Sólo se puede aplicar en el dominio del tiempo.",
      "Impone presión nula sobre toda la superficie.",
    ],
    ans: 0,
    why: "Se impone <code>∂p/∂n = −iωρ₀·p/Z</code>, donde Z es la impedancia de superficie: relaciona presión con velocidad en la pared. Es lo que permite modelar absorción en un FEM. Dos consecuencias: la matriz se vuelve <b>compleja</b> (y el problema de autovalores, complejo, con modos que decaen), y aparece la necesidad de un dato difícil — la Z del material, que sale del tubo de impedancia y no de una tabla de α.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · FEM for Acoustics",
  },
  {
    id: "num-pml",
    cat: "Condiciones de borde", dif: 3,
    q: "Una PML (perfectly matched layer) sirve para…",
    opts: [
      "Simular un dominio infinito sin reflexiones.",
      "Acelerar la convergencia del solver iterativo.",
      "Modelar una pared rígida con más precisión.",
      "Refinar la malla sólo en torno a la fuente.",
    ],
    ans: 0,
    why: "Es una capa artificial que rodea el dominio y absorbe todo lo que le llega <b>sin reflejar</b>, en cualquier ángulo y frecuencia. Se logra con un estiramiento complejo de coordenadas: la onda sigue propagándose pero se atenúa exponencialmente. Es la forma estándar de truncar un problema abierto (radiación al exterior, cámara anecoica virtual). En una sala cerrada no hace falta — ahí los bordes son físicos.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · FEM for Acoustics",
  },
  {
    id: "num-elementos-infinitos",
    cat: "Condiciones de borde", dif: 3,
    q: "Los elementos infinitos, frente a una PML…",
    opts: [
      "Son otra forma de truncar un dominio abierto.",
      "Sirven para refinar la malla cerca del borde.",
      "Sólo se usan en problemas estructurales 2D.",
      "Imponen presión nula en el infinito exacto.",
    ],
    ans: 0,
    why: "Resuelven el mismo problema con otra estrategia: en vez de rodear con una capa absorbente, usan funciones de forma que ya llevan incorporado el decaimiento y la fase de una onda saliente hacia el infinito. Son más económicos en grados de libertad, pero menos robustos si la geometría no se parece a la que asumen. PML es hoy la opción por defecto; los infinitos siguen vivos en códigos maduros.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-acoplamiento",
    cat: "Condiciones de borde", dif: 3,
    q: "Un análisis vibroacústico acoplado hace falta cuando…",
    opts: [
      "La pared vibra y su movimiento carga al fluido.",
      "La sala tiene paredes perfectamente rígidas.",
      "Se busca sólo el RT60 en bandas de octava real.",
      "El aire se considera incompresible y estático.",
    ],
    ans: 0,
    why: "Si la estructura es liviana o el fluido pesado, el problema deja de ser separable: el aire empuja la pared, la pared se mueve y ese movimiento vuelve a cargar el aire. Hay que resolver los dos dominios <b>juntos</b>, con matrices acopladas. En aire y con paredes de mampostería el acople es débil y se puede ignorar (por eso «pared rígida» funciona tan bien); en agua, o con paneles livianos y placas de yeso, ya no.",
    src: "Fahy, Sound and Structural Vibration · Ihlenburg",
  },

  // ───────────────────── Malla y precisión ─────────────────────
  {
    id: "num-elementos-lambda",
    cat: "Malla", dif: 2,
    q: "¿Por qué en FEM se piden ~6–10 elementos por longitud de onda si Nyquist pide 2?",
    opts: [
      "Por costumbre heredada de los solvers de mecánica estructural.",
      "Nyquist reconstruye señales; el lineal interpola con rectas.",
      "Porque los solvers iterativos no convergen con menos nodos.",
      "Porque el aire tiene pérdidas que hay que resolver aparte.",
    ],
    ans: 1,
    why: "Son dos problemas distintos. Nyquist responde «¿puedo reconstruir la señal a partir de muestras?» y asume reconstrucción ideal por sinc. El FEM pregunta otra cosa: «¿qué tan bien aproxima mi <b>base de funciones</b> la solución?». Con elementos lineales la base son rectas a trozos, y dibujar un seno con 2 rectas por período no se parece a nada. De ahí la regla de 6–10 — y aun así queda el pollution error encima.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §2.3 (error estimates)",
  },
  {
    id: "num-pollution",
    cat: "Validez", dif: 3,
    q: "¿Qué es el error de dispersión (pollution error) en FEM acústico?",
    opts: [
      "Ruido numérico acumulado por el redondeo de punto flotante.",
      "Desfase que se acumula con las λ recorridas, pese al refinado.",
      "El error de mallar una geometría curva con elementos rectos.",
      "La pérdida de energía que introducen los bordes absorbentes.",
    ],
    ans: 1,
    why: "Es la trampa más contraintuitiva del FEM de alta frecuencia. Uno esperaría que fijar «6 elementos por λ» dé error constante a cualquier frecuencia, pero no: la onda discreta viaja a velocidad levemente distinta de c, y ese error de fase se <b>acumula</b> con el número de longitudes de onda atravesadas. A f alta empeora aunque refines proporcionalmente. Para mantener la precisión hay que refinar <b>más rápido</b> que λ, o subir el orden del elemento (p-FEM), que ataca la dispersión mucho más eficientemente.",
    src: "Ihlenburg, §2.3/§3.2 (large wavenumber) · Stable Multiscale Petrov-Galerkin FEM — referencias/",
  },
  {
    id: "num-h-vs-p",
    cat: "Malla", dif: 3,
    q: "Refinamiento h y refinamiento p se diferencian en que…",
    opts: [
      "h achica elementos; p sube el orden del polinomio.",
      "h sube el orden; p achica el tamaño del elemento.",
      "Son lo mismo con distinto nombre en la literatura.",
      "h se aplica en 2D y p solamente en 3D, siempre.",
    ],
    ans: 0,
    why: "Dos caminos para converger. El <b>h</b> (más elementos, más chicos) es el reflejo automático, pero contra el pollution error es caro: hay que refinar más rápido que λ. El <b>p</b> (mismos elementos, polinomios de mayor orden) ataca la dispersión mucho mejor y suele ser bastante más eficiente en alta frecuencia — a costa de matrices más densas y de mayor complejidad de implementación.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §2.3",
  },
  {
    id: "num-jacobiano",
    cat: "Malla", dif: 3,
    q: "Si el Jacobiano de un elemento se vuelve negativo…",
    opts: [
      "El elemento está invertido: la malla es inválida.",
      "El elemento es de mejor calidad que el promedio.",
      "Indica que la solución convergió correctamente.",
      "Sólo afecta al tiempo de cálculo, no al resultado.",
    ],
    ans: 0,
    why: "El Jacobiano mide cómo el mapeo estira el elemento de referencia hasta el real. Si se vuelve negativo, el mapeo se «dio vuelta»: el elemento está enredado sobre sí mismo y no representa un volumen físico. La integración numérica ahí devuelve basura. Es un error <b>fatal</b> de mallado, no una advertencia de calidad — la mayoría de los mallado res lo chequean y abortan.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-calidad-malla",
    cat: "Malla", dif: 2,
    q: "Un elemento muy alargado (aspect ratio alto) en la malla…",
    opts: [
      "Degrada la precisión y el condicionamiento.",
      "Mejora la precisión al cubrir más volumen.",
      "No afecta en nada mientras h sea pequeño.",
      "Sólo importa en los cálculos estructurales.",
    ],
    ans: 0,
    why: "Un elemento «astilla» tiene mal Jacobiano y aproxima mal los gradientes en la dirección corta, además de empeorar el número de condición de la matriz global. Por eso «h chico» no alcanza como criterio: importa el <b>tamaño y también la forma</b>. Un mallador puede reportar h promedio excelente y esconder un puñado de elementos degenerados que arruinan el resultado.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-tet-hex",
    cat: "Malla", dif: 2,
    q: "Frente a los tetraedros, los hexaedros en FEM acústico…",
    opts: [
      "Dan mejor precisión por grado de libertad usado.",
      "Se generan más fácil en geometrías complicadas.",
      "Son siempre peores, sin ninguna ventaja real.",
      "No se pueden usar en problemas de acústica lineal.",
    ],
    ans: 0,
    why: "El hexaedro rinde más por grado de libertad: sus funciones de forma son productos tensoriales y el error de dispersión es menor. Pero mallar una geometría complicada con hexaedros es difícil y a menudo hay que hacerlo a mano. El tetraedro se genera automáticamente en cualquier forma. Es el canje clásico: hexaedros donde la geometría lo permita, tetraedros donde no quede otra.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-costo-gdl",
    cat: "Malla", dif: 2,
    q: "Al duplicar la frecuencia máxima de un modelo FEM 3D…",
    opts: [
      "Los grados de libertad se multiplican por ocho.",
      "Los grados de libertad simplemente se duplican.",
      "El costo no cambia si el orden se mantiene.",
      "Los grados de libertad se reducen a la mitad.",
    ],
    ans: 0,
    why: "Duplicar f_max reduce λ a la mitad, así que h se reduce a la mitad para mantener los elementos por longitud de onda. En 3D, la cantidad de elementos va como <code>1/h³</code>: <b>×8</b>. Y el costo del solver crece todavía más rápido que los grados de libertad. Es la razón por la que el FEM en salas se usa en graves y se cede a los métodos geométricos en agudos: no es una elección estética, es que no cierra el cómputo.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · FEM for Acoustics",
  },
  {
    id: "num-mesh-independence",
    cat: "Validez", dif: 2,
    q: "Un estudio de independencia de malla consiste en…",
    opts: [
      "Refinar hasta que el resultado deje de cambiar.",
      "Usar la malla más gruesa que el solver acepte.",
      "Comparar dos solvers sobre la misma malla fija.",
      "Ajustar la malla hasta igualar la medición.",
    ],
    ans: 0,
    why: "Se refina progresivamente y se observa la magnitud de interés: cuando deja de moverse, el resultado ya no depende de la discretización. Es el chequeo mínimo antes de creerle a un modelo. Ojo con la última opción, que es la trampa: <b>ajustar la malla hasta que dé lo que querés</b> no es verificar nada — es meter la respuesta a mano y perder todo el poder predictivo del modelo.",
    src: "Ihlenburg · FEM for Acoustics",
  },
  {
    id: "num-verificacion-validacion",
    cat: "Validez", dif: 3,
    q: "Verificación y validación de un modelo se diferencian en que…",
    opts: [
      "Verificar es resolver bien; validar, resolver lo real.",
      "Verificar es comparar con medición; validar, con teoría.",
      "Son sinónimos, usados en distintas normas técnicas.",
      "Verificar aplica a mallas; validar, sólo a solvers.",
    ],
    ans: 0,
    why: "La frase que lo resume: <b>verificar</b> es «¿estoy resolviendo bien las ecuaciones?» (matemática: convergencia, independencia de malla, comparación contra solución analítica). <b>Validar</b> es «¿son éstas las ecuaciones correctas?» (física: comparar contra medición real). Un modelo puede estar perfectamente verificado y ser inválido, porque el problema no está en el solver sino en los supuestos.",
    src: "Ihlenburg · FEM for Acoustics · Roache, Verification and Validation",
  },

  // ───────────────────── Solvers y modos ─────────────────────
  {
    id: "num-matriz-K-M",
    cat: "Solvers", dif: 2,
    q: "En el problema modal acústico, las matrices K y M representan…",
    opts: [
      "Rigidez del aire y su inercia, respectivamente.",
      "La geometría de la sala y el material de pared.",
      "Las condiciones de borde y las fuentes acústicas.",
      "El error de discretización y su gradiente local.",
    ],
    ans: 0,
    why: "Los nombres vienen de la mecánica estructural, pero acá la analogía es directa: <b>K</b> (de <code>∫∇Nᵢ·∇Nⱼ</code>) representa la rigidez del aire — su resistencia a comprimirse — y <b>M</b> (de <code>∫NᵢNⱼ</code>) su inercia. Un modo acústico es exactamente lo mismo que un modo mecánico: energía intercambiándose entre un resorte y una masa. De ahí que el problema tome la forma <code>K·p = λ·M·p</code>.",
    src: "Ihlenburg · FEM for Acoustics",
  },
  {
    id: "num-autovalores",
    cat: "Solvers", dif: 2,
    q: "El problema de autovalores K·p = λ·M·p en acústica da…",
    opts: [
      "Las frecuencias modales y las formas de los modos.",
      "La respuesta en frecuencia ante una fuente dada.",
      "El campo de presión para cada posición de fuente.",
      "El coeficiente de absorción de cada superficie.",
    ],
    ans: 0,
    why: "Los <b>autovalores</b> dan las frecuencias propias (<code>λ = (ω/c)²</code>) y los <b>autovectores</b>, la forma espacial de cada modo — dónde están sus nodos y antinodos. Es una propiedad de la sala sola: no depende de dónde pongas la fuente. Para saber qué se oye en un punto hace falta el paso siguiente: excitar la sala y combinar los modos según cuánto los active esa fuente.",
    src: "Ihlenburg · FEM for Acoustics",
  },
  {
    id: "num-modo-cero",
    cat: "Solvers", dif: 3,
    q: "El autovalor cero de una sala con paredes rígidas corresponde a…",
    opts: [
      "El modo de presión uniforme en todo el volumen.",
      "Un error numérico que hay que eliminar siempre.",
      "El modo axial fundamental del eje más largo.",
      "La frecuencia de Schroeder calculada por FEM.",
    ],
    ans: 0,
    why: "Con todas las paredes rígidas, <code>p = constante</code> satisface la ecuación y todas las condiciones de borde: es un modo legítimo de frecuencia cero, el equivalente al «modo de cuerpo rígido» estructural. Físicamente es presurizar la sala entera de manera uniforme. No es un bug — pero conviene reconocerlo, porque hace singular a K y puede confundir a un solver que no lo espera.",
    src: "Ihlenburg · FEM for Acoustics",
  },
  {
    id: "num-superposicion-modal",
    cat: "Solvers", dif: 3,
    q: "Calcular una FRF por superposición modal…",
    opts: [
      "Reusa los modos ya calculados en cada frecuencia.",
      "Resuelve el sistema completo en cada frecuencia.",
      "Sólo funciona si la sala no tiene absorción alguna.",
      "Da un resultado exacto usando un solo modo propio.",
    ],
    ans: 0,
    why: "Se resuelve <b>una vez</b> el problema de autovalores y después, para cada frecuencia, se suman los modos pesados por su factor de participación y su denominador resonante. Es órdenes de magnitud más rápido que resolver el sistema completo frecuencia por frecuencia (solución directa), que es la alternativa. El costo: hay que truncar la base, y eso mete error cerca del tope de la banda.",
    src: "Ihlenburg · FEM for Acoustics",
  },
  {
    id: "num-truncamiento-modal",
    cat: "Solvers", dif: 3,
    q: "Truncar la base modal en una superposición…",
    opts: [
      "Introduce error en el borde superior de la banda.",
      "No introduce ningún error si hay muchos modos.",
      "Mejora la precisión al descartar los modos altos.",
      "Sólo afecta a la fase, jamás a la magnitud medida.",
    ],
    ans: 0,
    why: "Los modos que quedan fuera de la base igual <b>aportan</b> en la banda de interés: su cola de rigidez contribuye aunque su resonancia esté más arriba. Al truncar, ese aporte se pierde y el error crece hacia el tope de la banda. Regla práctica: calcular modos hasta ~1,5–2 veces la frecuencia máxima que te interesa, o agregar una corrección de residuo estático.",
    src: "Ihlenburg · FEM for Acoustics",
  },
  {
    id: "num-rayleigh",
    cat: "Solvers", dif: 3,
    q: "El amortiguamiento de Rayleigh (proporcional) supone…",
    opts: [
      "C como combinación lineal de las matrices K y M.",
      "Que la absorción es cero en todas las paredes.",
      "Que el amortiguamiento crece con la frecuencia.",
      "Que cada modo tiene su propio factor de pérdida.",
    ],
    ans: 0,
    why: "<code>C = α·M + β·K</code>. Su gracia es puramente matemática: al ser combinación de M y K, los modos del sistema amortiguado son los mismos que los del no amortiguado, y se puede seguir usando superposición modal. Su defecto es físico: en acústica de salas el amortiguamiento viene de <b>superficies</b> concretas con su propia impedancia, y no tiene ninguna razón de ser proporcional a M y K. Es una comodidad, no un modelo.",
    src: "Fahy, Sound and Structural Vibration · FEM for Acoustics",
  },
  {
    id: "num-sparse",
    cat: "Solvers", dif: 2,
    q: "La matriz de un FEM acústico es dispersa (sparse) porque…",
    opts: [
      "Cada nodo sólo se acopla con sus vecinos.",
      "La mayoría de los modos no aportan energía.",
      "Se descartan los elementos de mala calidad.",
      "El solver va eliminando filas redundantes.",
    ],
    ans: 0,
    why: "Las funciones de forma tienen <b>soporte local</b>: <code>Nᵢ</code> vale cero fuera de los elementos que tocan el nodo i. Entonces <code>Kᵢⱼ ≠ 0</code> sólo si los nodos i y j comparten un elemento — cada fila tiene un puñado de entradas y el resto es cero. Es lo que hace viable el FEM: guardar y resolver un sistema de un millón de incógnitas sería imposible con una matriz llena. El BEM, en cambio, da matrices <b>densas</b>.",
    src: "Ihlenburg · FEM for Acoustics",
  },
  {
    id: "num-condicionamiento",
    cat: "Solvers", dif: 3,
    q: "Al subir mucho la frecuencia, la matriz del sistema de Helmholtz…",
    opts: [
      "Se vuelve indefinida y mal condicionada.",
      "Mejora su condicionamiento notablemente.",
      "Se vuelve diagonal y trivial de resolver.",
      "Deja de depender por completo del número k.",
    ],
    ans: 0,
    why: "El operador es <code>K − k²M</code>: al crecer k, deja de ser definido positivo y pasa a ser <b>indefinido</b>, con autovalores de los dos signos. Eso es lo que hace de Helmholtz un problema numéricamente difícil, muy distinto de un Laplace o de la elasticidad estática. Y empeora cerca de una resonancia, donde el sistema se acerca a ser singular.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §3.2 (large wavenumber)",
  },
  {
    id: "num-gmres-helmholtz",
    cat: "Solvers", dif: 3,
    q: "Los solvers iterativos sufren con Helmholtz a alta frecuencia porque…",
    opts: [
      "La matriz es indefinida y no converge fácil.",
      "La matriz es demasiado densa para iterar.",
      "El problema deja de ser lineal en alta f.",
      "No existen precondicionadores para Helmholtz.",
    ],
    ans: 0,
    why: "Los métodos de Krylov (GMRES y compañía) andan muy bien con matrices definidas positivas, pero <code>K − k²M</code> es indefinida: el espectro rodea el origen y la convergencia se degrada, hasta estancarse. Es un problema abierto y con mucha literatura propia (shifted-Laplacian, sweeping preconditioners, métodos multinivel). Por eso en acústica todavía se usan tanto los solvers directos, aunque escalen peor.",
    src: "Ihlenburg, §3.2 · Stable Multiscale Petrov-Galerkin FEM — referencias/",
  },

  // ───────────────────── Otros métodos ─────────────────────
  {
    id: "num-weyl",
    cat: "Densidad modal", dif: 3,
    q: "En la fórmula de Weyl, el término de volumen 4πVf²/c³ dice que la densidad modal…",
    opts: [
      "Es constante con la frecuencia en todo el rango audible.",
      "Crece con f²: los modos se agolpan cada vez más rápido.",
      "Decrece al subir en frecuencia dentro de una sala chica.",
      "Depende sólo de la superficie total del recinto medido.",
    ],
    ans: 1,
    why: "El crecimiento cuadrático es exactamente <b>por qué existe</b> la frecuencia de Schroeder: llega un punto donde hay tantos modos por banda que contarlos de a uno pierde sentido y conviene la descripción estadística. La fórmula completa suma términos de superficie (~f²·S/c²) y de aristas (~f·L/c), que pesan sobre todo en frecuencias bajas y salas chicas.",
    src: "Analysis on Modal Distribution and Modal Density-Based Crossover Frequency — referencias/",
  },
  {
    id: "num-bem-vs-fem",
    cat: "Otros métodos", dif: 3,
    q: "El BEM, frente al FEM, conviene cuando…",
    opts: [
      "El dominio es exterior o infinito, sin bordes.",
      "El dominio es cerrado y con materiales variados.",
      "Hace falta resolver muchos modos de una sala.",
      "El problema es no lineal y depende del tiempo.",
    ],
    ans: 0,
    why: "El BEM sólo malla la <b>superficie</b>, no el volumen, y la condición de radiación al infinito se satisface automáticamente: ideal para radiación de una caja acústica al espacio libre. El precio: matrices <b>densas</b> y no simétricas (cada elemento se acopla con todos), así que escala mal. Para el interior de una sala, con volumen acotado y materiales variados, el FEM gana con comodidad.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · FEM for Acoustics",
  },
  {
    id: "num-fdtd-courant",
    cat: "Otros métodos", dif: 3,
    q: "La condición de Courant en FDTD acústico…",
    opts: [
      "Liga el paso de tiempo con el paso espacial.",
      "Fija el número mínimo de modos a calcular.",
      "Define la impedancia de las paredes rígidas.",
      "Determina el orden del elemento a utilizar.",
    ],
    ans: 0,
    why: "Es una condición de <b>estabilidad</b>: el paso de tiempo tiene que ser lo bastante chico como para que la onda no atraviese más de una celda por paso (<code>c·Δt ≤ Δx/√3</code> en 3D). Si se viola, la simulación no da «un poco peor»: <b>explota</b> exponencialmente. Y como refinar el espacio obliga a refinar el tiempo, el costo de un FDTD 3D crece como la cuarta potencia de la frecuencia.",
    src: "FEM for Acoustics · Courant, Friedrichs & Lewy (1928)",
  },
  {
    id: "num-ray-tracing",
    cat: "Otros métodos", dif: 2,
    q: "El trazado de rayos deja de ser válido…",
    opts: [
      "En baja frecuencia, donde λ es comparable a la sala.",
      "En alta frecuencia, donde hay ya demasiados rayos.",
      "Cuando la sala tiene más de 1000 metros cúbicos.",
      "Si las superficies son perfectamente reflectantes.",
    ],
    ans: 0,
    why: "El rayo es una aproximación de <b>alta frecuencia</b>: supone que λ es mucho menor que todo lo demás, así que ignora difracción e interferencia — o sea, ignora justamente los modos. En graves eso es fatal. Su límite de validez es más o menos la frecuencia de Schroeder: arriba anda bien y es barato; abajo hay que ir a métodos de onda (FEM, BEM, FDTD). De ahí los métodos híbridos.",
    src: "Vorländer, Auralization · Everest, Master Handbook of Acoustics",
  },
  {
    id: "num-fuente-imagen",
    cat: "Otros métodos", dif: 3,
    q: "El método de fuentes imagen, al subir el orden de reflexión…",
    opts: [
      "Crece de forma exponencial en cantidad de fuentes.",
      "Crece de forma lineal con el orden de reflexión.",
      "Mantiene constante el costo computacional total.",
      "Sólo sirve para el primer orden de reflexiones.",
    ],
    ans: 0,
    why: "Cada superficie genera una imagen de cada fuente existente: con N paredes, el orden k da del orden de <code>N·(N−1)^(k−1)</code> imágenes, y encima hay que testear la validez de cada una. Es <b>exacto</b> para geometrías rectangulares simples y órdenes bajos, y por eso se lo usa para las reflexiones tempranas — pero se vuelve impracticable enseguida. La cola tardía se deja al trazado de rayos: ése es el híbrido más común.",
    src: "Vorländer, Auralization · Allen & Berkley (1979)",
  },
  {
    id: "num-hibrido",
    cat: "Otros métodos", dif: 2,
    q: "Un método híbrido en acústica de salas combina…",
    opts: [
      "Onda en graves y geometría en agudos, con cruce.",
      "FEM y BEM aplicados sobre el mismo dominio 3D.",
      "Dos mallas distintas para el mismo recinto real.",
      "Medición y simulación en un resultado combinado.",
    ],
    ans: 0,
    why: "Cada familia de métodos tiene su banda: los de <b>onda</b> (FEM/BEM/FDTD) son exactos pero su costo explota con la frecuencia; los <b>geométricos</b> (rayos, fuentes imagen) son baratos pero ignoran difracción e interferencia. El híbrido usa cada uno donde sirve y cruza cerca de la frecuencia de Schroeder. El punto delicado es justamente el empalme: que las dos mitades peguen sin escalón.",
    src: "Vorländer, Auralization",
  },

  // ═══════════════════════ TANDA 2 (nuevas) ═══════════════════════
  {
    id: "num-cuadratura-gauss",
    cat: "Formulación", dif: 3,
    q: "La cuadratura de Gauss en FEM sirve para…",
    opts: [
      "Resolver el sistema lineal global de una sola vez.",
      "Integrar numéricamente las matrices de un elemento.",
      "Generar la malla a partir de la geometría del CAD.",
      "Ordenar los nodos para reducir el ancho de banda.",
    ],
    ans: 1,
    why: "Las integrales de K y M sobre cada elemento (con Jacobiano de por medio) rara vez tienen forma cerrada, así que se evalúan por <b>cuadratura de Gauss</b>: se suma el integrando en unos pocos puntos con pesos óptimos. Con n puntos integra exacto un polinomio de grado 2n−1. Elegir el orden correcto importa: de menos, subintegra; de más, gasta cómputo. No resuelve el sistema global ni malla ni reordena.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · FEM for Acoustics",
  },
  {
    id: "num-ensamblaje",
    cat: "Solvers", dif: 2,
    q: "El ensamblaje en FEM consiste en…",
    opts: [
      "Sumar las matrices de elemento en la matriz global.",
      "Dividir el dominio en elementos finitos pequeños.",
      "Aplicar la cuadratura de Gauss a cada integral.",
      "Resolver el problema de autovalores generalizado.",
    ],
    ans: 0,
    why: "Cada elemento aporta una matriz chica (K_e, M_e); el <b>ensamblaje</b> las suma en las posiciones globales según qué nodos comparten, armando las matrices K y M del sistema completo. Como cada nodo sólo lo tocan sus elementos vecinos, la matriz global queda <b>dispersa</b>. Es un paso distinto del mallado (que crea los elementos), de la cuadratura (que integra) y del solver (que resuelve).",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · FEM for Acoustics",
  },
  {
    id: "num-lumped-mass",
    cat: "Solvers", dif: 3,
    q: "Una matriz de masa «concentrada» (lumped), frente a la consistente…",
    opts: [
      "Es diagonal y acelera los esquemas explícitos.",
      "Es más densa pero mucho más precisa siempre.",
      "Elimina la necesidad de condiciones de borde.",
      "Sólo se puede usar en problemas estáticos.",
    ],
    ans: 0,
    why: "La masa <b>concentrada</b> agrupa la masa del elemento en sus nodos, dando una matriz M <b>diagonal</b>: invertirla es trivial, lo que hace muy eficientes los esquemas de integración temporal <b>explícitos</b>. El precio es algo menos de precisión que la matriz consistente (que sale directo de las funciones de forma). Es un canje clásico velocidad/precisión, muy usado en FDTD y dinámica explícita.",
    src: "FEM for Acoustics · Fahy, Sound and Structural Vibration",
  },
  {
    id: "num-factorizacion",
    cat: "Solvers", dif: 3,
    q: "Un solver directo resuelve el sistema Ax=b mediante…",
    opts: [
      "Iteraciones sucesivas que se acercan a la solución.",
      "Una factorización de la matriz (tipo LU) y sustitución.",
      "El cálculo previo de todos los autovalores del sistema.",
      "Un refinamiento adaptativo de la malla hasta converger.",
    ],
    ans: 1,
    why: "Un solver <b>directo</b> factoriza la matriz (LU, o Cholesky si es definida positiva) y luego resuelve por sustitución hacia adelante y atrás: da la solución exacta (salvo redondeo) en un número finito de pasos. Es robusto pero su costo y memoria escalan mal con el tamaño (el «fill-in» densifica la factorización). Los <b>iterativos</b> son la alternativa para problemas enormes. No calcula autovalores ni refina malla.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-ancho-banda",
    cat: "Solvers", dif: 3,
    q: "Reordenar los nodos (Cuthill-McKee) antes de factorizar sirve para…",
    opts: [
      "Achicar el ancho de banda y el costo de factorizar.",
      "Mejorar la calidad geométrica de elementos malos.",
      "Subir el orden de los polinomios de las funciones.",
      "Eliminar los modos espurios de la solución modal.",
    ],
    ans: 0,
    why: "El costo y la memoria de un solver directo dependen del <b>ancho de banda</b> de la matriz (qué tan lejos de la diagonal hay entradas no nulas), que a su vez depende de cómo se numeraron los nodos. Reordenar (Cuthill-McKee inverso, nested dissection) agrupa las conexiones cerca de la diagonal y reduce drásticamente el fill-in. Es puramente numérico: no toca la geometría, el orden del elemento ni los modos.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · FEM for Acoustics",
  },
  {
    id: "num-integracion-reducida",
    cat: "Malla", dif: 3,
    q: "La integración reducida en algunos elementos puede provocar…",
    opts: [
      "Modos de energía nula (hourglass) sin control.",
      "Una malla siempre más precisa y sin artefactos.",
      "La pérdida de la simetría de la matriz global.",
      "Que el Jacobiano se vuelva negativo en los bordes.",
    ],
    ans: 0,
    why: "Usar menos puntos de Gauss de los necesarios (integración reducida) abarata el cómputo y a veces alivia el «locking», pero puede dejar sin controlar ciertos patrones de deformación de <b>energía nula</b> (hourglass): modos espurios que contaminan la solución. Se estabilizan con control de hourglass. Es un canje delicado — no es «siempre mejor». No rompe la simetría ni invierte el Jacobiano (eso es mala malla).",
    src: "FEM for Acoustics · Ihlenburg",
  },
  {
    id: "num-error-posteriori",
    cat: "Validez", dif: 3,
    q: "Un estimador de error a posteriori se usa para…",
    opts: [
      "Decidir dónde refinar la malla de forma adaptativa.",
      "Comparar el resultado contra una medición real.",
      "Elegir el paso de tiempo de un esquema explícito.",
      "Fijar la impedancia de las paredes absorbentes.",
    ],
    ans: 0,
    why: "Un estimador <b>a posteriori</b> usa la solución ya calculada para estimar dónde el error es mayor, y así refinar la malla <b>sólo donde hace falta</b> (refinamiento adaptativo): más elementos cerca de esquinas o fuentes, menos donde el campo es suave. Es eficiencia dirigida por el error, no verificación contra medición (eso es validación) ni cálculo de paso temporal ni condiciones de borde.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-convergencia-orden",
    cat: "Validez", dif: 3,
    q: "Que un método converja con orden p significa que el error…",
    opts: [
      "Baja proporcional a h elevado a la p al refinar.",
      "Desaparece por completo con cualquier tamaño h.",
      "Sube con la frecuencia sin importar el refinado.",
      "Depende sólo del solver, no del tamaño de malla.",
    ],
    ans: 0,
    why: "Orden p: al reducir el tamaño de elemento h, el error decae como <code>h^p</code>. Elementos lineales dan p≈2 en la norma L2; los de mayor orden convergen más rápido (más p). Verificar el orden observado (refinando y midiendo la pendiente del error) es parte de la <b>verificación</b> del código. En Helmholtz de alta frecuencia el pollution error degrada esta tasa, y por eso hay que refinar más agresivamente.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-modo-espurio",
    cat: "Solvers", dif: 3,
    q: "Un «modo espurio» en un cálculo modal es…",
    opts: [
      "Un modo físico real que el solver ubicó mal.",
      "Un modo sin sentido físico, artefacto numérico.",
      "El modo de presión uniforme de frecuencia cero.",
      "Un modo axial degenerado por simetría de la sala.",
    ],
    ans: 1,
    why: "Un modo espurio es un <b>artefacto numérico</b> sin correspondencia física: aparece por formulaciones mal planteadas, elementos inadecuados o integración reducida sin control. Hay que reconocerlos y descartarlos, porque ensucian la interpretación. Se distinguen del modo de cuerpo rígido (frecuencia cero, que sí es real) y de los modos degenerados por simetría (también reales, sólo que coinciden en frecuencia).",
    src: "FEM for Acoustics · Ihlenburg",
  },
  {
    id: "num-lanczos",
    cat: "Solvers", dif: 3,
    q: "Para hallar los primeros modos de una malla grande se usa…",
    opts: [
      "Un método directo con todos los autovalores.",
      "Un método iterativo tipo Lanczos o Arnoldi.",
      "La factorización LU de la matriz de rigidez.",
      "Un barrido frecuencia a frecuencia del sistema.",
    ],
    ans: 1,
    why: "Calcular <b>todos</b> los autovalores de un sistema de millones de grados de libertad es imposible y además innecesario: sólo interesan los primeros (los de más baja frecuencia). Los métodos iterativos de subespacio de Krylov (<b>Lanczos</b> para simétrico, Arnoldi para general) extraen unos pocos autovalores/autovectores en un extremo del espectro de forma eficiente. Es el estándar en solvers modales grandes.",
    src: "FEM for Acoustics · Ihlenburg",
  },
  {
    id: "num-shift-invert",
    cat: "Solvers", dif: 3,
    q: "La técnica shift-and-invert en un solver modal permite…",
    opts: [
      "Hallar los modos cercanos a una frecuencia dada.",
      "Evitar por completo factorizar toda la matriz.",
      "Convertir un problema no lineal en uno lineal.",
      "Eliminar el pollution error en alta frecuencia.",
    ],
    ans: 0,
    why: "Aplicar un «shift» σ y trabajar con <code>(K−σM)⁻¹</code> transforma el espectro para que los autovalores <b>cercanos a σ</b> se vuelvan los dominantes, que es donde los métodos de Krylov convergen rápido. Así se extraen modos en una banda de frecuencia arbitraria, no sólo los más bajos. Requiere factorizar (K−σM) una vez. No linealiza nada ni ataca el pollution error.",
    src: "FEM for Acoustics · Ihlenburg",
  },
  {
    id: "num-implicito-explicito",
    cat: "Otros métodos", dif: 3,
    q: "En el dominio del tiempo, un esquema explícito frente a uno implícito…",
    opts: [
      "Es barato por paso pero condicionalmente estable.",
      "Es incondicionalmente estable a cualquier paso.",
      "Necesita resolver un sistema grande en cada paso.",
      "No sirve para problemas de propagación de ondas.",
    ],
    ans: 0,
    why: "El esquema <b>explícito</b> avanza cada paso con muy poco cómputo (sobre todo con masa concentrada, diagonal), pero es <b>condicionalmente estable</b>: el paso de tiempo está limitado por la condición de Courant. El <b>implícito</b> es estable con pasos grandes pero resuelve un sistema por paso (caro). Para ondas acústicas transitorias, donde igual hace falta paso chico por resolución, el explícito suele ganar.",
    src: "FEM for Acoustics · Courant, Friedrichs & Lewy (1928)",
  },
  {
    id: "num-dispersion-anisotropa",
    cat: "Validez", dif: 3,
    q: "En una malla estructurada, el error de dispersión numérica suele ser…",
    opts: [
      "Igual en todas las direcciones de propagación.",
      "Distinto según la dirección respecto de la malla.",
      "Nulo si se usan elementos lineales bien simples.",
      "Independiente de la frecuencia de la onda dada.",
    ],
    ans: 1,
    why: "La velocidad numérica de la onda depende de la dirección respecto de la grilla: una onda que viaja alineada con los ejes se dispersa distinto que una a 45°. Esa <b>anisotropía</b> del error de dispersión deforma frentes de onda que deberían ser isótropos, y crece con la frecuencia. Es una cara del pollution error. Mallas no estructuradas la reparten pero no la eliminan; subir el orden ayuda más.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-autovalor-complejo",
    cat: "Condiciones de borde", dif: 3,
    q: "Al agregar paredes con impedancia (absorción), el problema modal…",
    opts: [
      "Sigue siendo real: sólo cambian las frecuencias.",
      "Se vuelve complejo: los modos decaen en el tiempo.",
      "Deja de tener solución; hay que ir al dominio.",
      "Pierde todos sus modos por debajo de Schroeder.",
    ],
    ans: 1,
    why: "Con impedancia finita en los bordes, las matrices se vuelven <b>complejas</b> y el problema de autovalores da valores complejos: la parte real es la frecuencia del modo y la imaginaria, su <b>amortiguamiento</b> (qué tan rápido decae). Es la representación natural de un modo real de sala, que resuena y se apaga. Con paredes rígidas ideales el problema es real y los modos no decaen — una idealización.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · FEM for Acoustics",
  },
  {
    id: "num-bem-nounicidad",
    cat: "Otros métodos", dif: 3,
    q: "El BEM en radiación exterior sufre, a ciertas frecuencias, de…",
    opts: [
      "No unicidad: la solución falla en frecuencias.",
      "Matrices dispersas que lo hacen demasiado lento.",
      "Imposibilidad de imponer las condiciones de borde.",
      "Pérdida de energía por las capas absorbentes PML.",
    ],
    ans: 0,
    why: "La formulación integral de contorno para problemas exteriores falla en las <b>frecuencias propias del problema interior asociado</b>: ahí la ecuación no tiene solución única y el resultado se corrompe. Se corrige con métodos como CHIEF (puntos interiores extra) o la formulación de Burton-Miller. Es un problema teórico específico del BEM exterior; sus matrices son <b>densas</b> (no dispersas), otro de sus costos.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-fmm",
    cat: "Otros métodos", dif: 3,
    q: "El método multipolar rápido (FMM) sirve para…",
    opts: [
      "Acelerar el BEM agrupando interacciones lejanas.",
      "Refinar la malla cerca de la fuente sonora dada.",
      "Estabilizar los esquemas explícitos en el tiempo.",
      "Generar mallas hexaédricas en geometría curva.",
    ],
    ans: 0,
    why: "El BEM tiene matrices densas: cada elemento interactúa con todos, y el costo escala como N². El <b>FMM</b> agrupa las interacciones <b>lejanas</b> en expansiones multipolares y las trata en bloque, bajando el costo a casi lineal. Es lo que hace viable el BEM en problemas grandes de radiación. No malla, no refina localmente ni tiene que ver con la integración temporal.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-sea",
    cat: "Otros métodos", dif: 3,
    q: "El análisis estadístico de energía (SEA) es apropiado en…",
    opts: [
      "Muy baja frecuencia, donde hay muy pocos modos.",
      "Muy alta frecuencia, con altísima densidad modal.",
      "El punto exacto de la frecuencia de Schroeder.",
      "Sólo problemas de campo libre, sin recinto real.",
    ],
    ans: 1,
    why: "El SEA modela el sistema como subsistemas que <b>intercambian energía</b> y describe promedios estadísticos, no el campo detallado. Es válido justo donde el FEM se vuelve impracticable: <b>alta frecuencia</b>, con tantos modos por banda que sólo importan promedios. Es la contraparte de onda del régimen difuso. FEM/BEM dominan en graves (pocos modos); SEA en agudos (muchos). Se cruzan cerca de la zona de Schroeder.",
    src: "Fahy, Sound and Structural Vibration · Lyon & DeJong, SEA",
  },
  {
    id: "num-green",
    cat: "Formulación", dif: 3,
    q: "La función de Green de un problema acústico es…",
    opts: [
      "La respuesta del campo a una fuente puntual.",
      "La matriz de rigidez de un elemento finito.",
      "El error de dispersión de la malla empleada.",
      "La malla de contorno del método BEM exterior.",
    ],
    ans: 0,
    why: "La función de Green es la <b>respuesta del campo a una fuente puntual</b> (un impulso espacial): conociéndola, la solución para cualquier distribución de fuentes sale por convolución/integral. Es el corazón de las formulaciones integrales de contorno (BEM), que la usan como núcleo. No es una matriz de elemento, ni el error de malla, ni la malla en sí — es una solución fundamental del operador.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-precondicionador",
    cat: "Solvers", dif: 3,
    q: "Un precondicionador en un solver iterativo sirve para…",
    opts: [
      "Acelerar la convergencia transformando el sistema.",
      "Generar la malla antes de ensamblar las matrices.",
      "Calcular exactamente todos los modos de la sala.",
      "Imponer las condiciones de borde de impedancia.",
    ],
    ans: 0,
    why: "Un método iterativo converge tanto más rápido cuanto mejor «condicionada» esté la matriz. El <b>precondicionador</b> M aproxima A⁻¹ de forma barata y transforma el sistema en uno equivalente que converge en muchas menos iteraciones. Para Helmholtz (matriz indefinida) los precondicionadores son un tema de investigación propio (shifted-Laplacian, sweeping). No malla, ni calcula modos, ni impone bordes.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · Stable Multiscale Petrov-Galerkin FEM",
  },

].map((q) => ({ ...q, area: "numerica" }));
