// ÁREA: Numérica y FEM.
//
// REGLA DE ORO: las 4 opciones van del MISMO largo (tolerancia ±5 caracteres).
// Validar con `python check_banco.py`. Ver juego/CONTENIDO.md.

export const NUMERICA = [

  // ───────────────────── Formulación ─────────────────────
  {
    id: "num-helmholtz",
    cat: "Formulación", dif: 2,
    q: "¿Qué ecuación gobierna el campo de presión armónico en el aire de un recinto?",
    opts: [
      "La ecuación de onda en el tiempo, ∂²p/∂t² = c²∇²p.",
      "La ecuación de Helmholtz, ∇²p + k²p = −iωρ₀·q(x).",
      "La ecuación de Laplace, ∇²p = 0, con k = ω/c fijo.",
      "La ecuación de Poisson con fuente, ∇²p = −ρ/ε₀.",
    ],
    ans: 1,
    why: "Helmholtz es la forma <b>frecuencial</b> de la ecuación de onda: se obtiene asumiendo dependencia temporal <code>e^{iωt}</code>, lo que convierte <code>∂²/∂t²</code> en <code>−ω²</code>. La ecuación de onda en el tiempo no está «mal» como física — es la misma ecuación antes de pasar a frecuencia — pero no es la que se resuelve cuando calculás modos o una FRF.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §1.1 (ec. 1.3) · FEM for Acoustics",
  },
  {
    id: "num-forma-debil",
    cat: "Formulación", dif: 3,
    q: "La forma débil de Helmholtz se obtiene…",
    opts: [
      "Multiplicando por una función de prueba e integrando.",
      "Derivando dos veces la ecuación original completa.",
      "Discretizando el dominio en elementos finitos chicos.",
      "Aplicando la transformada de Fourier a la ecuación.",
    ],
    ans: 0,
    why: "Se multiplica por una función de prueba, se integra sobre el dominio y se integra por partes. El nombre viene de que se le pide <b>menos</b> a la solución: la forma fuerte exige que p sea dos veces derivable en todo punto; la débil, sólo una vez y en sentido integral. Eso es justamente lo que permite usar funciones lineales a trozos, que no tienen segunda derivada. La discretización viene después, y es un paso aparte.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §2.2 (forma débil)",
  },
  {
    id: "num-natural-esencial",
    cat: "Formulación", dif: 3,
    q: "¿Por qué la pared rígida es una condición de borde «natural» en Galerkin?",
    opts: [
      "Porque es la única condición que impone la naturaleza.",
      "El término de frontera se anula solo, sin tocar K ni M.",
      "Porque toda pared real es naturalmente bastante rígida.",
      "Porque se cumple por casualidad al discretizar el aire.",
    ],
    ans: 1,
    why: "Al integrar por partes aparece un término de frontera <code>∫v·(∂p/∂n)dS</code> que se anula solo cuando <code>∂p/∂n = 0</code>. Las condiciones <b>naturales</b> se satisfacen así, sin hacer nada; las <b>esenciales</b> (Dirichlet, p = 0) hay que imponerlas explícitamente en el espacio de prueba. Por eso un solver modal con paredes rígidas es el caso más simple: ensamblás K y M y resolvés el problema generalizado sin restricciones.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §2.2",
  },
  {
    id: "num-funciones-forma",
    cat: "Formulación", dif: 2,
    q: "Las funciones de forma de un elemento finito…",
    opts: [
      "Interpolan el campo entre los nodos del elemento.",
      "Son la solución exacta dentro de cada elemento.",
      "Definen la geometría, nunca el campo de presión.",
      "Sólo existen en elementos de orden cuadrático.",
    ],
    ans: 0,
    why: "Son la base del espacio de aproximación: dentro del elemento, el campo se escribe como <code>p(x) = Σ Nᵢ(x)·pᵢ</code>, donde <code>pᵢ</code> son los valores nodales. Valen 1 en su nodo y 0 en los demás. Toda la precisión del método depende de qué tan bien esa base puede imitar la solución real — y de ahí sale la regla de 6–10 elementos por longitud de onda para funciones lineales.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §2.2 (hat functions)",
  },
  {
    id: "num-isoparametrico",
    cat: "Formulación", dif: 3,
    q: "Un elemento isoparamétrico usa…",
    opts: [
      "Las mismas funciones para geometría y para campo.",
      "Funciones distintas para geometría y para campo.",
      "Sólo funciones lineales, nunca de mayor orden.",
      "Coordenadas globales, sin transformación alguna.",
    ],
    ans: 0,
    why: "«Iso-paramétrico» = mismos parámetros para las dos cosas: las mismas <code>Nᵢ</code> que interpolan la presión mapean el elemento de referencia al elemento real y deformado. La ventaja es enorme: permite elementos curvos y distorsionados usando una única maquinaria, e integrar siempre sobre el elemento de referencia. El precio es que hace falta el Jacobiano del mapeo, y ahí aparecen los problemas de calidad de malla.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-numero-onda",
    cat: "Formulación", dif: 1,
    q: "El número de onda k = ω/c en la ecuación de Helmholtz…",
    opts: [
      "Fija cuántas oscilaciones hay en cada metro.",
      "Es la velocidad del sonido dentro del medio.",
      "Mide la absorción de las superficies rígidas.",
      "Sólo aparece en el dominio del tiempo real.",
    ],
    ans: 0,
    why: "<code>k = ω/c = 2π/λ</code> es la frecuencia <b>espacial</b>: cuántos radianes de fase avanza la onda por metro. Es el parámetro que gobierna todo el problema numérico — la dificultad de un cálculo de Helmholtz no depende de la frecuencia en sí, sino del producto <code>k·L</code> (cuántas longitudes de onda entran en el dominio). Un problema con kL grande es duro, sea en aire o en agua.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §1.1",
  },

  // ───────────────────── Condiciones de borde ─────────────────────
  {
    id: "num-pared-rigida",
    cat: "Condiciones de borde", dif: 2,
    q: "«Pared rígida» significa físicamente que…",
    opts: [
      "La presión acústica se anula sobre toda la superficie.",
      "La velocidad normal es cero: ∂p/∂n = 0 en la pared.",
      "La impedancia acústica de la pared es exactamente cero.",
      "La energía incidente se absorbe de forma instantánea.",
    ],
    ans: 1,
    why: "Rígida = el aire no puede moverse perpendicular a la pared. Como <code>v_n ∝ ∂p/∂n</code> en régimen armónico, se traduce en gradiente normal nulo — y por eso la pared es un <b>antinodo de presión</b>. La opción «la presión se anula» describe el borde opuesto: superficie libre, impedancia cero, como el extremo abierto de un tubo.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §2.2",
  },
  {
    id: "num-impedancia-borde",
    cat: "Condiciones de borde", dif: 3,
    q: "Una condición de borde de impedancia en FEM…",
    opts: [
      "Modela una pared absorbente con su Z compleja.",
      "Es lo mismo que una pared perfectamente rígida.",
      "Sólo se puede aplicar en el dominio del tiempo.",
      "Impone presión nula sobre toda la superficie.",
    ],
    ans: 0,
    why: "Se impone <code>∂p/∂n = −iωρ₀·p/Z</code>, donde Z es la impedancia de superficie: relaciona presión con velocidad en la pared. Es lo que permite modelar absorción en un FEM. Dos consecuencias: la matriz se vuelve <b>compleja</b> (y el problema de autovalores, complejo, con modos que decaen), y aparece la necesidad de un dato difícil — la Z del material, que sale del tubo de impedancia y no de una tabla de α.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · FEM for Acoustics",
  },
  {
    id: "num-pml",
    cat: "Condiciones de borde", dif: 3,
    q: "Una PML (perfectly matched layer) sirve para…",
    opts: [
      "Simular un dominio infinito sin reflexiones.",
      "Acelerar la convergencia del solver iterativo.",
      "Modelar una pared rígida con más precisión.",
      "Refinar la malla sólo en torno a la fuente.",
    ],
    ans: 0,
    why: "Es una capa artificial que rodea el dominio y absorbe todo lo que le llega <b>sin reflejar</b>, en cualquier ángulo y frecuencia. Se logra con un estiramiento complejo de coordenadas: la onda sigue propagándose pero se atenúa exponencialmente. Es la forma estándar de truncar un problema abierto (radiación al exterior, cámara anecoica virtual). En una sala cerrada no hace falta — ahí los bordes son físicos.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · FEM for Acoustics",
  },
  {
    id: "num-elementos-infinitos",
    cat: "Condiciones de borde", dif: 3,
    q: "Los elementos infinitos, frente a una PML…",
    opts: [
      "Son otra forma de truncar un dominio abierto.",
      "Sirven para refinar la malla cerca del borde.",
      "Sólo se usan en problemas estructurales 2D.",
      "Imponen presión nula en el infinito exacto.",
    ],
    ans: 0,
    why: "Resuelven el mismo problema con otra estrategia: en vez de rodear con una capa absorbente, usan funciones de forma que ya llevan incorporado el decaimiento y la fase de una onda saliente hacia el infinito. Son más económicos en grados de libertad, pero menos robustos si la geometría no se parece a la que asumen. PML es hoy la opción por defecto; los infinitos siguen vivos en códigos maduros.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-acoplamiento",
    cat: "Condiciones de borde", dif: 3,
    q: "Un análisis vibroacústico acoplado hace falta cuando…",
    opts: [
      "La pared vibra y su movimiento carga al fluido.",
      "La sala tiene paredes perfectamente rígidas.",
      "Se busca sólo el RT60 en bandas de octava real.",
      "El aire se considera incompresible y estático.",
    ],
    ans: 0,
    why: "Si la estructura es liviana o el fluido pesado, el problema deja de ser separable: el aire empuja la pared, la pared se mueve y ese movimiento vuelve a cargar el aire. Hay que resolver los dos dominios <b>juntos</b>, con matrices acopladas. En aire y con paredes de mampostería el acople es débil y se puede ignorar (por eso «pared rígida» funciona tan bien); en agua, o con paneles livianos y placas de yeso, ya no.",
    src: "Fahy, Sound and Structural Vibration · Ihlenburg",
  },

  // ───────────────────── Malla y precisión ─────────────────────
  {
    id: "num-elementos-lambda",
    cat: "Malla", dif: 2,
    q: "¿Por qué en FEM se piden ~6–10 elementos por longitud de onda si Nyquist pide 2?",
    opts: [
      "Por costumbre heredada de los solvers de mecánica estructural.",
      "Nyquist reconstruye señales; el lineal interpola con rectas.",
      "Porque los solvers iterativos no convergen con menos nodos.",
      "Porque el aire tiene pérdidas que hay que resolver aparte.",
    ],
    ans: 1,
    why: "Son dos problemas distintos. Nyquist responde «¿puedo reconstruir la señal a partir de muestras?» y asume reconstrucción ideal por sinc. El FEM pregunta otra cosa: «¿qué tan bien aproxima mi <b>base de funciones</b> la solución?». Con elementos lineales la base son rectas a trozos, y dibujar un seno con 2 rectas por período no se parece a nada. De ahí la regla de 6–10 — y aun así queda el pollution error encima.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §2.3 (error estimates)",
  },
  {
    id: "num-pollution",
    cat: "Validez", dif: 3,
    q: "¿Qué es el error de dispersión (pollution error) en FEM acústico?",
    opts: [
      "Ruido numérico acumulado por el redondeo de punto flotante.",
      "Desfase que se acumula con las λ recorridas, pese al refinado.",
      "El error de mallar una geometría curva con elementos rectos.",
      "La pérdida de energía que introducen los bordes absorbentes.",
    ],
    ans: 1,
    why: "Es la trampa más contraintuitiva del FEM de alta frecuencia. Uno esperaría que fijar «6 elementos por λ» dé error constante a cualquier frecuencia, pero no: la onda discreta viaja a velocidad levemente distinta de c, y ese error de fase se <b>acumula</b> con el número de longitudes de onda atravesadas. A f alta empeora aunque refines proporcionalmente. Para mantener la precisión hay que refinar <b>más rápido</b> que λ, o subir el orden del elemento (p-FEM), que ataca la dispersión mucho más eficientemente.",
    src: "Ihlenburg, §2.3/§3.2 (large wavenumber) · Stable Multiscale Petrov-Galerkin FEM — referencias/",
  },
  {
    id: "num-h-vs-p",
    cat: "Malla", dif: 3,
    q: "Refinamiento h y refinamiento p se diferencian en que…",
    opts: [
      "h achica elementos; p sube el orden del polinomio.",
      "h sube el orden; p achica el tamaño del elemento.",
      "Son lo mismo con distinto nombre en la literatura.",
      "h se aplica en 2D y p solamente en 3D, siempre.",
    ],
    ans: 0,
    why: "Dos caminos para converger. El <b>h</b> (más elementos, más chicos) es el reflejo automático, pero contra el pollution error es caro: hay que refinar más rápido que λ. El <b>p</b> (mismos elementos, polinomios de mayor orden) ataca la dispersión mucho mejor y suele ser bastante más eficiente en alta frecuencia — a costa de matrices más densas y de mayor complejidad de implementación.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §2.3",
  },
  {
    id: "num-jacobiano",
    cat: "Malla", dif: 3,
    q: "Si el Jacobiano de un elemento se vuelve negativo…",
    opts: [
      "El elemento está invertido: la malla es inválida.",
      "El elemento es de mejor calidad que el promedio.",
      "Indica que la solución convergió correctamente.",
      "Sólo afecta al tiempo de cálculo, no al resultado.",
    ],
    ans: 0,
    why: "El Jacobiano mide cómo el mapeo estira el elemento de referencia hasta el real. Si se vuelve negativo, el mapeo se «dio vuelta»: el elemento está enredado sobre sí mismo y no representa un volumen físico. La integración numérica ahí devuelve basura. Es un error <b>fatal</b> de mallado, no una advertencia de calidad — la mayoría de los mallado res lo chequean y abortan.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-calidad-malla",
    cat: "Malla", dif: 2,
    q: "Un elemento muy alargado (aspect ratio alto) en la malla…",
    opts: [
      "Degrada la precisión y el condicionamiento.",
      "Mejora la precisión al cubrir más volumen.",
      "No afecta en nada mientras h sea pequeño.",
      "Sólo importa en los cálculos estructurales.",
    ],
    ans: 0,
    why: "Un elemento «astilla» tiene mal Jacobiano y aproxima mal los gradientes en la dirección corta, además de empeorar el número de condición de la matriz global. Por eso «h chico» no alcanza como criterio: importa el <b>tamaño y también la forma</b>. Un mallador puede reportar h promedio excelente y esconder un puñado de elementos degenerados que arruinan el resultado.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-tet-hex",
    cat: "Malla", dif: 2,
    q: "Frente a los tetraedros, los hexaedros en FEM acústico…",
    opts: [
      "Dan mejor precisión por grado de libertad usado.",
      "Se generan más fácil en geometrías complicadas.",
      "Son siempre peores, sin ninguna ventaja real.",
      "No se pueden usar en problemas de acústica lineal.",
    ],
    ans: 0,
    why: "El hexaedro rinde más por grado de libertad: sus funciones de forma son productos tensoriales y el error de dispersión es menor. Pero mallar una geometría complicada con hexaedros es difícil y a menudo hay que hacerlo a mano. El tetraedro se genera automáticamente en cualquier forma. Es el canje clásico: hexaedros donde la geometría lo permita, tetraedros donde no quede otra.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-costo-gdl",
    cat: "Malla", dif: 2,
    q: "Al duplicar la frecuencia máxima de un modelo FEM 3D…",
    opts: [
      "Los grados de libertad se multiplican por ocho.",
      "Los grados de libertad simplemente se duplican.",
      "El costo no cambia si el orden se mantiene.",
      "Los grados de libertad se reducen a la mitad.",
    ],
    ans: 0,
    why: "Duplicar f_max reduce λ a la mitad, así que h se reduce a la mitad para mantener los elementos por longitud de onda. En 3D, la cantidad de elementos va como <code>1/h³</code>: <b>×8</b>. Y el costo del solver crece todavía más rápido que los grados de libertad. Es la razón por la que el FEM en salas se usa en graves y se cede a los métodos geométricos en agudos: no es una elección estética, es que no cierra el cómputo.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · FEM for Acoustics",
  },
  {
    id: "num-mesh-independence",
    cat: "Validez", dif: 2,
    q: "Un estudio de independencia de malla consiste en…",
    opts: [
      "Refinar hasta que el resultado deje de cambiar.",
      "Usar la malla más gruesa que el solver acepte.",
      "Comparar dos solvers sobre la misma malla fija.",
      "Ajustar la malla hasta igualar la medición.",
    ],
    ans: 0,
    why: "Se refina progresivamente y se observa la magnitud de interés: cuando deja de moverse, el resultado ya no depende de la discretización. Es el chequeo mínimo antes de creerle a un modelo. Ojo con la última opción, que es la trampa: <b>ajustar la malla hasta que dé lo que querés</b> no es verificar nada — es meter la respuesta a mano y perder todo el poder predictivo del modelo.",
    src: "Ihlenburg · FEM for Acoustics",
  },
  {
    id: "num-verificacion-validacion",
    cat: "Validez", dif: 3,
    q: "Verificación y validación de un modelo se diferencian en que…",
    opts: [
      "Verificar es resolver bien; validar, resolver lo real.",
      "Verificar es comparar con medición; validar, con teoría.",
      "Son sinónimos, usados en distintas normas técnicas.",
      "Verificar aplica a mallas; validar, sólo a solvers.",
    ],
    ans: 0,
    why: "La frase que lo resume: <b>verificar</b> es «¿estoy resolviendo bien las ecuaciones?» (matemática: convergencia, independencia de malla, comparación contra solución analítica). <b>Validar</b> es «¿son éstas las ecuaciones correctas?» (física: comparar contra medición real). Un modelo puede estar perfectamente verificado y ser inválido, porque el problema no está en el solver sino en los supuestos.",
    src: "Ihlenburg · FEM for Acoustics · Roache, Verification and Validation",
  },

  // ───────────────────── Solvers y modos ─────────────────────
  {
    id: "num-matriz-K-M",
    cat: "Solvers", dif: 2,
    q: "En el problema modal acústico, las matrices K y M representan…",
    opts: [
      "Rigidez del aire y su inercia, respectivamente.",
      "La geometría de la sala y el material de pared.",
      "Las condiciones de borde y las fuentes acústicas.",
      "El error de discretización y su gradiente local.",
    ],
    ans: 0,
    why: "Los nombres vienen de la mecánica estructural, pero acá la analogía es directa: <b>K</b> (de <code>∫∇Nᵢ·∇Nⱼ</code>) representa la rigidez del aire — su resistencia a comprimirse — y <b>M</b> (de <code>∫NᵢNⱼ</code>) su inercia. Un modo acústico es exactamente lo mismo que un modo mecánico: energía intercambiándose entre un resorte y una masa. De ahí que el problema tome la forma <code>K·p = λ·M·p</code>.",
    src: "Ihlenburg · FEM for Acoustics",
  },
  {
    id: "num-autovalores",
    cat: "Solvers", dif: 2,
    q: "El problema de autovalores K·p = λ·M·p en acústica da…",
    opts: [
      "Las frecuencias modales y las formas de los modos.",
      "La respuesta en frecuencia ante una fuente dada.",
      "El campo de presión para cada posición de fuente.",
      "El coeficiente de absorción de cada superficie.",
    ],
    ans: 0,
    why: "Los <b>autovalores</b> dan las frecuencias propias (<code>λ = (ω/c)²</code>) y los <b>autovectores</b>, la forma espacial de cada modo — dónde están sus nodos y antinodos. Es una propiedad de la sala sola: no depende de dónde pongas la fuente. Para saber qué se oye en un punto hace falta el paso siguiente: excitar la sala y combinar los modos según cuánto los active esa fuente.",
    src: "Ihlenburg · FEM for Acoustics",
  },
  {
    id: "num-modo-cero",
    cat: "Solvers", dif: 3,
    q: "El autovalor cero de una sala con paredes rígidas corresponde a…",
    opts: [
      "El modo de presión uniforme en todo el volumen.",
      "Un error numérico que hay que eliminar siempre.",
      "El modo axial fundamental del eje más largo.",
      "La frecuencia de Schroeder calculada por FEM.",
    ],
    ans: 0,
    why: "Con todas las paredes rígidas, <code>p = constante</code> satisface la ecuación y todas las condiciones de borde: es un modo legítimo de frecuencia cero, el equivalente al «modo de cuerpo rígido» estructural. Físicamente es presurizar la sala entera de manera uniforme. No es un bug — pero conviene reconocerlo, porque hace singular a K y puede confundir a un solver que no lo espera.",
    src: "Ihlenburg · FEM for Acoustics",
  },
  {
    id: "num-superposicion-modal",
    cat: "Solvers", dif: 3,
    q: "Calcular una FRF por superposición modal…",
    opts: [
      "Reusa los modos ya calculados en cada frecuencia.",
      "Resuelve el sistema completo en cada frecuencia.",
      "Sólo funciona si la sala no tiene absorción alguna.",
      "Da un resultado exacto usando un solo modo propio.",
    ],
    ans: 0,
    why: "Se resuelve <b>una vez</b> el problema de autovalores y después, para cada frecuencia, se suman los modos pesados por su factor de participación y su denominador resonante. Es órdenes de magnitud más rápido que resolver el sistema completo frecuencia por frecuencia (solución directa), que es la alternativa. El costo: hay que truncar la base, y eso mete error cerca del tope de la banda.",
    src: "Ihlenburg · FEM for Acoustics",
  },
  {
    id: "num-truncamiento-modal",
    cat: "Solvers", dif: 3,
    q: "Truncar la base modal en una superposición…",
    opts: [
      "Introduce error en el borde superior de la banda.",
      "No introduce ningún error si hay muchos modos.",
      "Mejora la precisión al descartar los modos altos.",
      "Sólo afecta a la fase, jamás a la magnitud medida.",
    ],
    ans: 0,
    why: "Los modos que quedan fuera de la base igual <b>aportan</b> en la banda de interés: su cola de rigidez contribuye aunque su resonancia esté más arriba. Al truncar, ese aporte se pierde y el error crece hacia el tope de la banda. Regla práctica: calcular modos hasta ~1,5–2 veces la frecuencia máxima que te interesa, o agregar una corrección de residuo estático.",
    src: "Ihlenburg · FEM for Acoustics",
  },
  {
    id: "num-rayleigh",
    cat: "Solvers", dif: 3,
    q: "El amortiguamiento de Rayleigh (proporcional) supone…",
    opts: [
      "C como combinación lineal de las matrices K y M.",
      "Que la absorción es cero en todas las paredes.",
      "Que el amortiguamiento crece con la frecuencia.",
      "Que cada modo tiene su propio factor de pérdida.",
    ],
    ans: 0,
    why: "<code>C = α·M + β·K</code>. Su gracia es puramente matemática: al ser combinación de M y K, los modos del sistema amortiguado son los mismos que los del no amortiguado, y se puede seguir usando superposición modal. Su defecto es físico: en acústica de salas el amortiguamiento viene de <b>superficies</b> concretas con su propia impedancia, y no tiene ninguna razón de ser proporcional a M y K. Es una comodidad, no un modelo.",
    src: "Fahy, Sound and Structural Vibration · FEM for Acoustics",
  },
  {
    id: "num-sparse",
    cat: "Solvers", dif: 2,
    q: "La matriz de un FEM acústico es dispersa (sparse) porque…",
    opts: [
      "Cada nodo sólo se acopla con sus vecinos.",
      "La mayoría de los modos no aportan energía.",
      "Se descartan los elementos de mala calidad.",
      "El solver va eliminando filas redundantes.",
    ],
    ans: 0,
    why: "Las funciones de forma tienen <b>soporte local</b>: <code>Nᵢ</code> vale cero fuera de los elementos que tocan el nodo i. Entonces <code>Kᵢⱼ ≠ 0</code> sólo si los nodos i y j comparten un elemento — cada fila tiene un puñado de entradas y el resto es cero. Es lo que hace viable el FEM: guardar y resolver un sistema de un millón de incógnitas sería imposible con una matriz llena. El BEM, en cambio, da matrices <b>densas</b>.",
    src: "Ihlenburg · FEM for Acoustics",
  },
  {
    id: "num-condicionamiento",
    cat: "Solvers", dif: 3,
    q: "Al subir mucho la frecuencia, la matriz del sistema de Helmholtz…",
    opts: [
      "Se vuelve indefinida y mal condicionada.",
      "Mejora su condicionamiento notablemente.",
      "Se vuelve diagonal y trivial de resolver.",
      "Deja de depender por completo del número k.",
    ],
    ans: 0,
    why: "El operador es <code>K − k²M</code>: al crecer k, deja de ser definido positivo y pasa a ser <b>indefinido</b>, con autovalores de los dos signos. Eso es lo que hace de Helmholtz un problema numéricamente difícil, muy distinto de un Laplace o de la elasticidad estática. Y empeora cerca de una resonancia, donde el sistema se acerca a ser singular.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering, §3.2 (large wavenumber)",
  },
  {
    id: "num-gmres-helmholtz",
    cat: "Solvers", dif: 3,
    q: "Los solvers iterativos sufren con Helmholtz a alta frecuencia porque…",
    opts: [
      "La matriz es indefinida y no converge fácil.",
      "La matriz es demasiado densa para iterar.",
      "El problema deja de ser lineal en alta f.",
      "No existen precondicionadores para Helmholtz.",
    ],
    ans: 0,
    why: "Los métodos de Krylov (GMRES y compañía) andan muy bien con matrices definidas positivas, pero <code>K − k²M</code> es indefinida: el espectro rodea el origen y la convergencia se degrada, hasta estancarse. Es un problema abierto y con mucha literatura propia (shifted-Laplacian, sweeping preconditioners, métodos multinivel). Por eso en acústica todavía se usan tanto los solvers directos, aunque escalen peor.",
    src: "Ihlenburg, §3.2 · Stable Multiscale Petrov-Galerkin FEM — referencias/",
  },

  // ───────────────────── Otros métodos ─────────────────────
  {
    id: "num-weyl",
    cat: "Densidad modal", dif: 3,
    q: "En la fórmula de Weyl, el término de volumen 4πVf²/c³ dice que la densidad modal…",
    opts: [
      "Es constante con la frecuencia en todo el rango audible.",
      "Crece con f²: los modos se agolpan cada vez más rápido.",
      "Decrece al subir en frecuencia dentro de una sala chica.",
      "Depende sólo de la superficie total del recinto medido.",
    ],
    ans: 1,
    why: "El crecimiento cuadrático es exactamente <b>por qué existe</b> la frecuencia de Schroeder: llega un punto donde hay tantos modos por banda que contarlos de a uno pierde sentido y conviene la descripción estadística. La fórmula completa suma términos de superficie (~f²·S/c²) y de aristas (~f·L/c), que pesan sobre todo en frecuencias bajas y salas chicas.",
    src: "Analysis on Modal Distribution and Modal Density-Based Crossover Frequency — referencias/",
  },
  {
    id: "num-bem-vs-fem",
    cat: "Otros métodos", dif: 3,
    q: "El BEM, frente al FEM, conviene cuando…",
    opts: [
      "El dominio es exterior o infinito, sin bordes.",
      "El dominio es cerrado y con materiales variados.",
      "Hace falta resolver muchos modos de una sala.",
      "El problema es no lineal y depende del tiempo.",
    ],
    ans: 0,
    why: "El BEM sólo malla la <b>superficie</b>, no el volumen, y la condición de radiación al infinito se satisface automáticamente: ideal para radiación de una caja acústica al espacio libre. El precio: matrices <b>densas</b> y no simétricas (cada elemento se acopla con todos), así que escala mal. Para el interior de una sala, con volumen acotado y materiales variados, el FEM gana con comodidad.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · FEM for Acoustics",
  },
  {
    id: "num-fdtd-courant",
    cat: "Otros métodos", dif: 3,
    q: "La condición de Courant en FDTD acústico…",
    opts: [
      "Liga el paso de tiempo con el paso espacial.",
      "Fija el número mínimo de modos a calcular.",
      "Define la impedancia de las paredes rígidas.",
      "Determina el orden del elemento a utilizar.",
    ],
    ans: 0,
    why: "Es una condición de <b>estabilidad</b>: el paso de tiempo tiene que ser lo bastante chico como para que la onda no atraviese más de una celda por paso (<code>c·Δt ≤ Δx/√3</code> en 3D). Si se viola, la simulación no da «un poco peor»: <b>explota</b> exponencialmente. Y como refinar el espacio obliga a refinar el tiempo, el costo de un FDTD 3D crece como la cuarta potencia de la frecuencia.",
    src: "FEM for Acoustics · Courant, Friedrichs & Lewy (1928)",
  },
  {
    id: "num-ray-tracing",
    cat: "Otros métodos", dif: 2,
    q: "El trazado de rayos deja de ser válido…",
    opts: [
      "En baja frecuencia, donde λ es comparable a la sala.",
      "En alta frecuencia, donde hay ya demasiados rayos.",
      "Cuando la sala tiene más de 1000 metros cúbicos.",
      "Si las superficies son perfectamente reflectantes.",
    ],
    ans: 0,
    why: "El rayo es una aproximación de <b>alta frecuencia</b>: supone que λ es mucho menor que todo lo demás, así que ignora difracción e interferencia — o sea, ignora justamente los modos. En graves eso es fatal. Su límite de validez es más o menos la frecuencia de Schroeder: arriba anda bien y es barato; abajo hay que ir a métodos de onda (FEM, BEM, FDTD). De ahí los métodos híbridos.",
    src: "Vorländer, Auralization · Everest, Master Handbook of Acoustics",
  },
  {
    id: "num-fuente-imagen",
    cat: "Otros métodos", dif: 3,
    q: "El método de fuentes imagen, al subir el orden de reflexión…",
    opts: [
      "Crece de forma exponencial en cantidad de fuentes.",
      "Crece de forma lineal con el orden de reflexión.",
      "Mantiene constante el costo computacional total.",
      "Sólo sirve para el primer orden de reflexiones.",
    ],
    ans: 0,
    why: "Cada superficie genera una imagen de cada fuente existente: con N paredes, el orden k da del orden de <code>N·(N−1)^(k−1)</code> imágenes, y encima hay que testear la validez de cada una. Es <b>exacto</b> para geometrías rectangulares simples y órdenes bajos, y por eso se lo usa para las reflexiones tempranas — pero se vuelve impracticable enseguida. La cola tardía se deja al trazado de rayos: ése es el híbrido más común.",
    src: "Vorländer, Auralization · Allen & Berkley (1979)",
  },
  {
    id: "num-hibrido",
    cat: "Otros métodos", dif: 2,
    q: "Un método híbrido en acústica de salas combina…",
    opts: [
      "Onda en graves y geometría en agudos, con cruce.",
      "FEM y BEM aplicados sobre el mismo dominio 3D.",
      "Dos mallas distintas para el mismo recinto real.",
      "Medición y simulación en un resultado combinado.",
    ],
    ans: 0,
    why: "Cada familia de métodos tiene su banda: los de <b>onda</b> (FEM/BEM/FDTD) son exactos pero su costo explota con la frecuencia; los <b>geométricos</b> (rayos, fuentes imagen) son baratos pero ignoran difracción e interferencia. El híbrido usa cada uno donde sirve y cruza cerca de la frecuencia de Schroeder. El punto delicado es justamente el empalme: que las dos mitades peguen sin escalón.",
    src: "Vorländer, Auralization",
  },

  // ═══════════════════════ TANDA 2 (nuevas) ═══════════════════════
  {
    id: "num-cuadratura-gauss",
    cat: "Formulación", dif: 3,
    q: "La cuadratura de Gauss en FEM sirve para…",
    opts: [
      "Resolver el sistema lineal global de una sola vez.",
      "Integrar numéricamente las matrices de un elemento.",
      "Generar la malla a partir de la geometría del CAD.",
      "Ordenar los nodos para reducir el ancho de banda.",
    ],
    ans: 1,
    why: "Las integrales de K y M sobre cada elemento (con Jacobiano de por medio) rara vez tienen forma cerrada, así que se evalúan por <b>cuadratura de Gauss</b>: se suma el integrando en unos pocos puntos con pesos óptimos. Con n puntos integra exacto un polinomio de grado 2n−1. Elegir el orden correcto importa: de menos, subintegra; de más, gasta cómputo. No resuelve el sistema global ni malla ni reordena.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · FEM for Acoustics",
  },
  {
    id: "num-ensamblaje",
    cat: "Solvers", dif: 2,
    q: "El ensamblaje en FEM consiste en…",
    opts: [
      "Sumar las matrices de elemento en la matriz global.",
      "Dividir el dominio en elementos finitos pequeños.",
      "Aplicar la cuadratura de Gauss a cada integral.",
      "Resolver el problema de autovalores generalizado.",
    ],
    ans: 0,
    why: "Cada elemento aporta una matriz chica (K_e, M_e); el <b>ensamblaje</b> las suma en las posiciones globales según qué nodos comparten, armando las matrices K y M del sistema completo. Como cada nodo sólo lo tocan sus elementos vecinos, la matriz global queda <b>dispersa</b>. Es un paso distinto del mallado (que crea los elementos), de la cuadratura (que integra) y del solver (que resuelve).",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · FEM for Acoustics",
  },
  {
    id: "num-lumped-mass",
    cat: "Solvers", dif: 3,
    q: "Una matriz de masa «concentrada» (lumped), frente a la consistente…",
    opts: [
      "Es diagonal y acelera los esquemas explícitos.",
      "Es más densa pero mucho más precisa siempre.",
      "Elimina la necesidad de condiciones de borde.",
      "Sólo se puede usar en problemas estáticos.",
    ],
    ans: 0,
    why: "La masa <b>concentrada</b> agrupa la masa del elemento en sus nodos, dando una matriz M <b>diagonal</b>: invertirla es trivial, lo que hace muy eficientes los esquemas de integración temporal <b>explícitos</b>. El precio es algo menos de precisión que la matriz consistente (que sale directo de las funciones de forma). Es un canje clásico velocidad/precisión, muy usado en FDTD y dinámica explícita.",
    src: "FEM for Acoustics · Fahy, Sound and Structural Vibration",
  },
  {
    id: "num-factorizacion",
    cat: "Solvers", dif: 3,
    q: "Un solver directo resuelve el sistema Ax=b mediante…",
    opts: [
      "Iteraciones sucesivas que se acercan a la solución.",
      "Una factorización de la matriz (tipo LU) y sustitución.",
      "El cálculo previo de todos los autovalores del sistema.",
      "Un refinamiento adaptativo de la malla hasta converger.",
    ],
    ans: 1,
    why: "Un solver <b>directo</b> factoriza la matriz (LU, o Cholesky si es definida positiva) y luego resuelve por sustitución hacia adelante y atrás: da la solución exacta (salvo redondeo) en un número finito de pasos. Es robusto pero su costo y memoria escalan mal con el tamaño (el «fill-in» densifica la factorización). Los <b>iterativos</b> son la alternativa para problemas enormes. No calcula autovalores ni refina malla.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-ancho-banda",
    cat: "Solvers", dif: 3,
    q: "Reordenar los nodos (Cuthill-McKee) antes de factorizar sirve para…",
    opts: [
      "Achicar el ancho de banda y el costo de factorizar.",
      "Mejorar la calidad geométrica de elementos malos.",
      "Subir el orden de los polinomios de las funciones.",
      "Eliminar los modos espurios de la solución modal.",
    ],
    ans: 0,
    why: "El costo y la memoria de un solver directo dependen del <b>ancho de banda</b> de la matriz (qué tan lejos de la diagonal hay entradas no nulas), que a su vez depende de cómo se numeraron los nodos. Reordenar (Cuthill-McKee inverso, nested dissection) agrupa las conexiones cerca de la diagonal y reduce drásticamente el fill-in. Es puramente numérico: no toca la geometría, el orden del elemento ni los modos.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · FEM for Acoustics",
  },
  {
    id: "num-integracion-reducida",
    cat: "Malla", dif: 3,
    q: "La integración reducida en algunos elementos puede provocar…",
    opts: [
      "Modos de energía nula (hourglass) sin control.",
      "Una malla siempre más precisa y sin artefactos.",
      "La pérdida de la simetría de la matriz global.",
      "Que el Jacobiano se vuelva negativo en los bordes.",
    ],
    ans: 0,
    why: "Usar menos puntos de Gauss de los necesarios (integración reducida) abarata el cómputo y a veces alivia el «locking», pero puede dejar sin controlar ciertos patrones de deformación de <b>energía nula</b> (hourglass): modos espurios que contaminan la solución. Se estabilizan con control de hourglass. Es un canje delicado — no es «siempre mejor». No rompe la simetría ni invierte el Jacobiano (eso es mala malla).",
    src: "FEM for Acoustics · Ihlenburg",
  },
  {
    id: "num-error-posteriori",
    cat: "Validez", dif: 3,
    q: "Un estimador de error a posteriori se usa para…",
    opts: [
      "Decidir dónde refinar la malla de forma adaptativa.",
      "Comparar el resultado contra una medición real.",
      "Elegir el paso de tiempo de un esquema explícito.",
      "Fijar la impedancia de las paredes absorbentes.",
    ],
    ans: 0,
    why: "Un estimador <b>a posteriori</b> usa la solución ya calculada para estimar dónde el error es mayor, y así refinar la malla <b>sólo donde hace falta</b> (refinamiento adaptativo): más elementos cerca de esquinas o fuentes, menos donde el campo es suave. Es eficiencia dirigida por el error, no verificación contra medición (eso es validación) ni cálculo de paso temporal ni condiciones de borde.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-convergencia-orden",
    cat: "Validez", dif: 3,
    q: "Que un método converja con orden p significa que el error…",
    opts: [
      "Baja proporcional a h elevado a la p al refinar.",
      "Desaparece por completo con cualquier tamaño h.",
      "Sube con la frecuencia sin importar el refinado.",
      "Depende sólo del solver, no del tamaño de malla.",
    ],
    ans: 0,
    why: "Orden p: al reducir el tamaño de elemento h, el error decae como <code>h^p</code>. Elementos lineales dan p≈2 en la norma L2; los de mayor orden convergen más rápido (más p). Verificar el orden observado (refinando y midiendo la pendiente del error) es parte de la <b>verificación</b> del código. En Helmholtz de alta frecuencia el pollution error degrada esta tasa, y por eso hay que refinar más agresivamente.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-modo-espurio",
    cat: "Solvers", dif: 3,
    q: "Un «modo espurio» en un cálculo modal es…",
    opts: [
      "Un modo físico real que el solver ubicó mal.",
      "Un modo sin sentido físico, artefacto numérico.",
      "El modo de presión uniforme de frecuencia cero.",
      "Un modo axial degenerado por simetría de la sala.",
    ],
    ans: 1,
    why: "Un modo espurio es un <b>artefacto numérico</b> sin correspondencia física: aparece por formulaciones mal planteadas, elementos inadecuados o integración reducida sin control. Hay que reconocerlos y descartarlos, porque ensucian la interpretación. Se distinguen del modo de cuerpo rígido (frecuencia cero, que sí es real) y de los modos degenerados por simetría (también reales, sólo que coinciden en frecuencia).",
    src: "FEM for Acoustics · Ihlenburg",
  },
  {
    id: "num-lanczos",
    cat: "Solvers", dif: 3,
    q: "Para hallar los primeros modos de una malla grande se usa…",
    opts: [
      "Un método directo con todos los autovalores.",
      "Un método iterativo tipo Lanczos o Arnoldi.",
      "La factorización LU de la matriz de rigidez.",
      "Un barrido frecuencia a frecuencia del sistema.",
    ],
    ans: 1,
    why: "Calcular <b>todos</b> los autovalores de un sistema de millones de grados de libertad es imposible y además innecesario: sólo interesan los primeros (los de más baja frecuencia). Los métodos iterativos de subespacio de Krylov (<b>Lanczos</b> para simétrico, Arnoldi para general) extraen unos pocos autovalores/autovectores en un extremo del espectro de forma eficiente. Es el estándar en solvers modales grandes.",
    src: "FEM for Acoustics · Ihlenburg",
  },
  {
    id: "num-shift-invert",
    cat: "Solvers", dif: 3,
    q: "La técnica shift-and-invert en un solver modal permite…",
    opts: [
      "Hallar los modos cercanos a una frecuencia dada.",
      "Evitar por completo factorizar toda la matriz.",
      "Convertir un problema no lineal en uno lineal.",
      "Eliminar el pollution error en alta frecuencia.",
    ],
    ans: 0,
    why: "Aplicar un «shift» σ y trabajar con <code>(K−σM)⁻¹</code> transforma el espectro para que los autovalores <b>cercanos a σ</b> se vuelvan los dominantes, que es donde los métodos de Krylov convergen rápido. Así se extraen modos en una banda de frecuencia arbitraria, no sólo los más bajos. Requiere factorizar (K−σM) una vez. No linealiza nada ni ataca el pollution error.",
    src: "FEM for Acoustics · Ihlenburg",
  },
  {
    id: "num-implicito-explicito",
    cat: "Otros métodos", dif: 3,
    q: "En el dominio del tiempo, un esquema explícito frente a uno implícito…",
    opts: [
      "Es barato por paso pero condicionalmente estable.",
      "Es incondicionalmente estable a cualquier paso.",
      "Necesita resolver un sistema grande en cada paso.",
      "No sirve para problemas de propagación de ondas.",
    ],
    ans: 0,
    why: "El esquema <b>explícito</b> avanza cada paso con muy poco cómputo (sobre todo con masa concentrada, diagonal), pero es <b>condicionalmente estable</b>: el paso de tiempo está limitado por la condición de Courant. El <b>implícito</b> es estable con pasos grandes pero resuelve un sistema por paso (caro). Para ondas acústicas transitorias, donde igual hace falta paso chico por resolución, el explícito suele ganar.",
    src: "FEM for Acoustics · Courant, Friedrichs & Lewy (1928)",
  },
  {
    id: "num-dispersion-anisotropa",
    cat: "Validez", dif: 3,
    q: "En una malla estructurada, el error de dispersión numérica suele ser…",
    opts: [
      "Igual en todas las direcciones de propagación.",
      "Distinto según la dirección respecto de la malla.",
      "Nulo si se usan elementos lineales bien simples.",
      "Independiente de la frecuencia de la onda dada.",
    ],
    ans: 1,
    why: "La velocidad numérica de la onda depende de la dirección respecto de la grilla: una onda que viaja alineada con los ejes se dispersa distinto que una a 45°. Esa <b>anisotropía</b> del error de dispersión deforma frentes de onda que deberían ser isótropos, y crece con la frecuencia. Es una cara del pollution error. Mallas no estructuradas la reparten pero no la eliminan; subir el orden ayuda más.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-autovalor-complejo",
    cat: "Condiciones de borde", dif: 3,
    q: "Al agregar paredes con impedancia (absorción), el problema modal…",
    opts: [
      "Sigue siendo real: sólo cambian las frecuencias.",
      "Se vuelve complejo: los modos decaen en el tiempo.",
      "Deja de tener solución; hay que ir al dominio.",
      "Pierde todos sus modos por debajo de Schroeder.",
    ],
    ans: 1,
    why: "Con impedancia finita en los bordes, las matrices se vuelven <b>complejas</b> y el problema de autovalores da valores complejos: la parte real es la frecuencia del modo y la imaginaria, su <b>amortiguamiento</b> (qué tan rápido decae). Es la representación natural de un modo real de sala, que resuena y se apaga. Con paredes rígidas ideales el problema es real y los modos no decaen — una idealización.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · FEM for Acoustics",
  },
  {
    id: "num-bem-nounicidad",
    cat: "Otros métodos", dif: 3,
    q: "El BEM en radiación exterior sufre, a ciertas frecuencias, de…",
    opts: [
      "No unicidad: la solución falla en frecuencias.",
      "Matrices dispersas que lo hacen demasiado lento.",
      "Imposibilidad de imponer las condiciones de borde.",
      "Pérdida de energía por las capas absorbentes PML.",
    ],
    ans: 0,
    why: "La formulación integral de contorno para problemas exteriores falla en las <b>frecuencias propias del problema interior asociado</b>: ahí la ecuación no tiene solución única y el resultado se corrompe. Se corrige con métodos como CHIEF (puntos interiores extra) o la formulación de Burton-Miller. Es un problema teórico específico del BEM exterior; sus matrices son <b>densas</b> (no dispersas), otro de sus costos.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-fmm",
    cat: "Otros métodos", dif: 3,
    q: "El método multipolar rápido (FMM) sirve para…",
    opts: [
      "Acelerar el BEM agrupando interacciones lejanas.",
      "Refinar la malla cerca de la fuente sonora dada.",
      "Estabilizar los esquemas explícitos en el tiempo.",
      "Generar mallas hexaédricas en geometría curva.",
    ],
    ans: 0,
    why: "El BEM tiene matrices densas: cada elemento interactúa con todos, y el costo escala como N². El <b>FMM</b> agrupa las interacciones <b>lejanas</b> en expansiones multipolares y las trata en bloque, bajando el costo a casi lineal. Es lo que hace viable el BEM en problemas grandes de radiación. No malla, no refina localmente ni tiene que ver con la integración temporal.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-sea",
    cat: "Otros métodos", dif: 3,
    q: "El análisis estadístico de energía (SEA) es apropiado en…",
    opts: [
      "Muy baja frecuencia, donde hay muy pocos modos.",
      "Muy alta frecuencia, con altísima densidad modal.",
      "El punto exacto de la frecuencia de Schroeder.",
      "Sólo problemas de campo libre, sin recinto real.",
    ],
    ans: 1,
    why: "El SEA modela el sistema como subsistemas que <b>intercambian energía</b> y describe promedios estadísticos, no el campo detallado. Es válido justo donde el FEM se vuelve impracticable: <b>alta frecuencia</b>, con tantos modos por banda que sólo importan promedios. Es la contraparte de onda del régimen difuso. FEM/BEM dominan en graves (pocos modos); SEA en agudos (muchos). Se cruzan cerca de la zona de Schroeder.",
    src: "Fahy, Sound and Structural Vibration · Lyon & DeJong, SEA",
  },
  {
    id: "num-green",
    cat: "Formulación", dif: 3,
    q: "La función de Green de un problema acústico es…",
    opts: [
      "La respuesta del campo a una fuente puntual.",
      "La matriz de rigidez de un elemento finito.",
      "El error de dispersión de la malla empleada.",
      "La malla de contorno del método BEM exterior.",
    ],
    ans: 0,
    why: "La función de Green es la <b>respuesta del campo a una fuente puntual</b> (un impulso espacial): conociéndola, la solución para cualquier distribución de fuentes sale por convolución/integral. Es el corazón de las formulaciones integrales de contorno (BEM), que la usan como núcleo. No es una matriz de elemento, ni el error de malla, ni la malla en sí — es una solución fundamental del operador.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-precondicionador",
    cat: "Solvers", dif: 3,
    q: "Un precondicionador en un solver iterativo sirve para…",
    opts: [
      "Acelerar la convergencia transformando el sistema.",
      "Generar la malla antes de ensamblar las matrices.",
      "Calcular exactamente todos los modos de la sala.",
      "Imponer las condiciones de borde de impedancia.",
    ],
    ans: 0,
    why: "Un método iterativo converge tanto más rápido cuanto mejor «condicionada» esté la matriz. El <b>precondicionador</b> M aproxima A⁻¹ de forma barata y transforma el sistema en uno equivalente que converge en muchas menos iteraciones. Para Helmholtz (matriz indefinida) los precondicionadores son un tema de investigación propio (shifted-Laplacian, sweeping). No malla, ni calcula modos, ni impone bordes.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · Stable Multiscale Petrov-Galerkin FEM",
  },

  // ═══════════════════════ TANDA 3 (difíciles) ═══════════════════════
  {
    id: "num-gls",
    cat: "Validez", dif: 3,
    q: "Los métodos estabilizados (GLS, Petrov-Galerkin) para Helmholtz buscan…",
    opts: [
      "Reducir el error de dispersión del Galerkin estándar.",
      "Acelerar el mallado de geometrías muy complicadas.",
      "Eliminar la necesidad de las condiciones de borde.",
      "Convertir la matriz compleja en una matriz real pura.",
    ],
    ans: 0,
    why: "El Galerkin estándar sufre el error de dispersión (pollution) en alta frecuencia. Métodos como Galerkin Least-Squares (GLS) o Petrov-Galerkin agregan términos que <b>ajustan el número de onda numérico</b> al real, reduciendo el desfase acumulado sin refinar más. Es una estabilización a nivel de formulación, no de malla ni de solver. No tocan las condiciones de borde ni vuelven real la matriz.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · Harari",
  },
  {
    id: "num-dg",
    cat: "Formulación", dif: 3,
    q: "El Galerkin discontinuo (DG), frente al FEM continuo, permite…",
    opts: [
      "Campo discontinuo entre elementos, vía flujo numérico.",
      "Prescindir por completo de la malla de los elementos.",
      "Resolver sólo problemas estáticos, nunca los de onda.",
      "Matrices siempre más chicas que en el FEM continuo.",
    ],
    ans: 0,
    why: "El DG no exige continuidad del campo entre elementos: cada uno tiene sus propios grados de libertad y se comunican por <b>flujos numéricos</b> en las interfaces (como en volúmenes finitos). Ventajas: p-adaptividad flexible, mallas no conformes, buen manejo de propagación de ondas y paralelización. El costo es <b>más</b> grados de libertad (se duplican en las caras), no menos. No elimina la malla.",
    src: "FEM for Acoustics · Hesthaven & Warburton",
  },
  {
    id: "num-sem",
    cat: "Formulación", dif: 3,
    q: "El método de elementos espectrales (SEM) combina…",
    opts: [
      "Polinomios de alto orden con mallas de pocos elementos.",
      "Elementos lineales con una malla sumamente refinada.",
      "El BEM de contorno junto con el FEM de volumen total.",
      "Diferencias finitas con condiciones de borde periódicas.",
    ],
    ans: 0,
    why: "El SEM usa <b>polinomios de orden alto</b> (nodos en puntos de Gauss-Lobatto) dentro de pocos elementos grandes: hereda la convergencia exponencial de los métodos espectrales pero con la flexibilidad geométrica del FEM. Con masa concentrada (diagonal por la cuadratura GLL) es muy eficiente para propagación de ondas. Ataca el pollution error subiendo p, no refinando h. No es BEM ni diferencias finitas.",
    src: "FEM for Acoustics · Patera (1984)",
  },
  {
    id: "num-multigrid-helmholtz",
    cat: "Solvers", dif: 3,
    q: "El multigrid clásico falla en Helmholtz de alta frecuencia porque…",
    opts: [
      "La matriz es indefinida y su error no se suaviza bien.",
      "La malla es demasiado fina para las mallas gruesas.",
      "El problema no tiene solución única en ese régimen.",
      "Las condiciones de borde no se pueden restringir.",
    ],
    ans: 0,
    why: "El multigrid asume que los suavizadores eliminan el error de alta frecuencia y las mallas gruesas el de baja — pero en Helmholtz <b>indefinido</b> hay modos de error oscilatorios que ni se suavizan ni se representan bien en la malla gruesa, y el método diverge. De ahí que se investiguen variantes especiales (shifted-Laplacian como precondicionador, wave-ray). No es un problema de unicidad ni de bordes.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · Erlangga",
  },
  {
    id: "num-shifted-laplacian",
    cat: "Solvers", dif: 3,
    q: "El precondicionador shifted-Laplacian para Helmholtz consiste en…",
    opts: [
      "Usar un Helmholtz con amortiguamiento complejo extra.",
      "Ignorar el término de masa y resolver sólo Laplace.",
      "Duplicar la frecuencia para acelerar la convergencia.",
      "Reordenar los nodos con el algoritmo de Cuthill-McKee.",
    ],
    ans: 0,
    why: "Se precondiciona el sistema indefinido con un operador de Helmholtz <b>desplazado al plano complejo</b> (con amortiguamiento artificial): ese operador «amortiguado» sí es tratable por multigrid y aproxima bien al original, acelerando GMRES. Es de los enfoques más exitosos para Helmholtz a gran escala. No es tirar el término de masa (eso sería Laplace, mal precondicionador) ni cambiar la frecuencia.",
    src: "Erlangga, Vuik & Oosterlee (2006) · Ihlenburg",
  },
  {
    id: "num-domain-decomposition",
    cat: "Solvers", dif: 3,
    q: "La descomposición de dominio (Schwarz) resuelve un problema grande…",
    opts: [
      "Partiéndolo en subdominios que se resuelven aparte.",
      "Reduciéndolo a un solo elemento finito equivalente.",
      "Eliminando los grados de libertad interiores de golpe.",
      "Convirtiéndolo en un problema puramente temporal ya.",
    ],
    ans: 0,
    why: "Se divide el dominio en <b>subdominios</b>, cada uno se resuelve por separado y se intercambia información en las interfaces hasta converger. Es la base del cómputo <b>paralelo</b> en FEM (cada subdominio en un procesador). Para Helmholtz las condiciones de transmisión en las interfaces son delicadas (métodos optimizados de Schwarz con condiciones tipo absorbente). No colapsa el problema a un elemento ni al tiempo.",
    src: "FEM for Acoustics · Ihlenburg",
  },
  {
    id: "num-craig-bampton",
    cat: "Solvers", dif: 3,
    q: "La síntesis modal de componentes (Craig-Bampton) sirve para…",
    opts: [
      "Reducir subestructuras a pocos modos e interfaces.",
      "Refinar la malla en las zonas de mayor error.",
      "Calcular la respuesta al impulso en el tiempo.",
      "Estimar el coeficiente de absorción de un panel.",
    ],
    ans: 0,
    why: "Craig-Bampton reduce cada <b>subestructura</b> a un conjunto chico de modos internos fijos más los modos de restricción de sus interfaces (grados de libertad de borde): el modelo global queda mucho más chico conservando la dinámica relevante. Es reducción de orden por substructuring, clave en modelos grandes vibroacústicos. No es refinamiento de malla ni cálculo temporal ni absorción.",
    src: "Fahy, Sound and Structural Vibration · Craig & Bampton (1968)",
  },
  {
    id: "num-mor",
    cat: "Solvers", dif: 3,
    q: "La reducción de orden de modelo (MOR) para una FRF busca…",
    opts: [
      "Un sistema chico que reproduzca la respuesta en banda.",
      "Refinar la malla hasta la independencia más total.",
      "Resolver el sistema completo en cada frecuencia dada.",
      "Aumentar el número de grados de libertad del modelo.",
    ],
    ans: 0,
    why: "MOR (p. ej. por subespacios de Krylov / momentos) construye un modelo de <b>orden muy reducido</b> que reproduce la función de transferencia en una banda con pocos grados de libertad, evitando resolver el sistema enorme frecuencia por frecuencia. Ideal para barrer FRFs o para diseño iterativo. Es lo opuesto a aumentar los grados de libertad; y no reemplaza la verificación de malla, la asume hecha.",
    src: "FEM for Acoustics · Bai (2002)",
  },
  {
    id: "num-pou-gfem",
    cat: "Formulación", dif: 3,
    q: "El GFEM/PUM enriquecido para Helmholtz agrega a la base…",
    opts: [
      "Funciones de onda plana que ya resuelven la ecuación.",
      "Más nodos lineales para refinar sólo en lo local.",
      "Elementos de contorno acoplados a todo el volumen.",
      "Un amortiguamiento artificial en cada elemento finito.",
    ],
    ans: 0,
    why: "El método de partición de la unidad (PUM/GFEM) multiplica las funciones de forma por <b>ondas planas</b> (o funciones que ya satisfacen Helmholtz localmente): así la base «sabe» oscilar y captura muchas longitudes de onda por elemento, atacando el pollution error con pocos grados de libertad. Es un enriquecimiento de la base, no refinamiento h, ni acople BEM, ni estabilización por amortiguamiento.",
    src: "Ihlenburg · Babuška & Melenk (1997)",
  },
  {
    id: "num-uwvf-trefftz",
    cat: "Formulación", dif: 3,
    q: "Los métodos tipo Trefftz (UWVF) usan funciones de base que…",
    opts: [
      "Satisfacen exactamente la ecuación en cada elemento.",
      "Son polinomios lineales estándar por cada elemento.",
      "Sólo existen sobre el contorno exterior del dominio.",
      "Se anulan en todos los nodos menos en uno solo.",
    ],
    ans: 0,
    why: "En los métodos de Trefftz (como la UWVF, ultra weak variational formulation), las funciones de base <b>ya son soluciones exactas</b> de Helmholtz dentro de cada elemento (típicamente ondas planas en varias direcciones); sólo hay que acoplarlas en las interfaces. Eso da precisión altísima por grado de libertad en régimen de alta frecuencia. Es lo contrario de los polinomios lineales nodales del FEM clásico.",
    src: "Ihlenburg · Cessenat & Després (1998)",
  },
  {
    id: "num-burton-miller",
    cat: "Otros métodos", dif: 3,
    q: "La formulación de Burton-Miller resuelve, en el BEM exterior…",
    opts: [
      "La no unicidad en las frecuencias irregulares.",
      "El alto costo de las matrices densas del BEM.",
      "La generación de la malla de la superficie.",
      "El error de dispersión de la malla de volumen.",
    ],
    ans: 0,
    why: "Burton-Miller combina la ecuación integral de presión con su derivada normal, ponderada por un factor complejo: la combinación <b>no comparte</b> las frecuencias irregulares de cada una por separado, eliminando la <b>no unicidad</b> del BEM exterior. Alternativa a CHIEF, más robusta (aunque exige integrales hipersingulares). Ataca la unicidad, no el costo (para eso está el FMM) ni el mallado.",
    src: "Ihlenburg · Burton & Miller (1971)",
  },
  {
    id: "num-fem-bem-coupling",
    cat: "Otros métodos", dif: 3,
    q: "Acoplar FEM y BEM en un problema vibroacústico conviene para…",
    opts: [
      "FEM en la estructura interior y BEM en el exterior.",
      "Usar dos mallas de volumen distintas en el mismo aire.",
      "Reemplazar las condiciones de borde por fuentes puras.",
      "Evitar por completo resolver la parte estructural.",
    ],
    ans: 0,
    why: "Se aprovecha lo mejor de cada uno: <b>FEM</b> para la estructura y el fluido interior (materiales complejos, matrices dispersas) y <b>BEM</b> para el dominio <b>exterior infinito</b> (satisface la radiación al infinito sin malla de volumen). Se acoplan en la interfaz común. Es el enfoque estándar para radiación de una estructura vibrante al espacio libre. No evita resolver la estructura: la integra.",
    src: "FEM for Acoustics · Ihlenburg",
  },
  {
    id: "num-abc-orden",
    cat: "Condiciones de borde", dif: 3,
    q: "Una condición de borde absorbente (ABC) de orden alto, frente a una simple…",
    opts: [
      "Refleja menos las ondas que inciden oblicuas.",
      "Es exacta a cualquier ángulo de incidencia dado.",
      "Sólo funciona con ondas perpendiculares al borde.",
      "Reemplaza a la malla de volumen por completo.",
    ],
    ans: 0,
    why: "Las ABC aproximan la condición de radiación en un borde artificial. Una de <b>orden bajo</b> absorbe bien sólo la incidencia normal y refleja las ondas oblicuas; subir el orden mejora la absorción en un rango de ángulos más amplio (pero nunca es perfecta a todo ángulo — para eso está la PML). Es un canje precisión/complejidad. No reemplaza la malla ni funciona sólo con incidencia normal.",
    src: "Ihlenburg · Engquist & Majda (1977)",
  },
  {
    id: "num-dtn",
    cat: "Condiciones de borde", dif: 3,
    q: "El mapa Dirichlet-to-Neumann (DtN) en un borde artificial…",
    opts: [
      "Da la condición exacta de radiación, pero es no local.",
      "Es una aproximación local de muy bajo costo total.",
      "Impone presión nula en todo el contorno externo real.",
      "Sólo se aplica en problemas del dominio del tiempo.",
    ],
    ans: 0,
    why: "El operador DtN relaciona el valor del campo (Dirichlet) con su derivada normal (Neumann) en un borde artificial de forma <b>exacta</b>, expandiendo en armónicos — pero es <b>no local</b> (cada punto del borde se acopla con todos los demás), lo que densifica la matriz en esa frontera. Es la referencia «exacta» frente a las ABC locales aproximadas. No impone presión nula ni es sólo temporal.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering · Keller & Givoli (1989)",
  },
  {
    id: "num-pml-discreta",
    cat: "Condiciones de borde", dif: 3,
    q: "Una PML, aunque teóricamente no refleja, en la práctica…",
    opts: [
      "Refleja algo por la discretización y su perfil abrupto.",
      "Refleja más cuanto más gruesa se la haga en total.",
      "Sólo funciona en el dominio de la frecuencia pura.",
      "Necesita más capas que grados de libertad del dominio.",
    ],
    ans: 0,
    why: "La PML es «perfectamente adaptada» en el continuo, pero al <b>discretizarla</b> aparece una reflexión residual: si el perfil de absorción crece muy abruptamente, la malla no lo resuelve y refleja. Se mitiga con un perfil suave (polinómico) y suficientes capas — hacerla <b>más</b> gruesa/suave reduce la reflexión, no la aumenta. Funciona en tiempo y frecuencia. Un puñado de capas suele bastar.",
    src: "Ihlenburg · Berenger (1994)",
  },
  {
    id: "num-condition-resonancia",
    cat: "Solvers", dif: 3,
    q: "Cerca de una frecuencia propia de la sala, el sistema Helmholtz…",
    opts: [
      "Se vuelve casi singular y muy mal condicionado.",
      "Se vuelve diagonal y trivial de resolver ya.",
      "Deja de depender del número de onda k del todo.",
      "Gana condicionamiento y converge más rápido.",
    ],
    ans: 0,
    why: "En una resonancia (paredes rígidas, sin amortiguamiento) el operador <code>K−k²M</code> es exactamente <b>singular</b>: cerca de ella el número de condición se dispara y la solución es enorme y sensible al redondeo. Por eso se evita evaluar FRFs justo en las frecuencias propias y se incluye algo de amortiguamiento (impedancia) que las regulariza. Lo opuesto a mejorar el condicionamiento.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-residuo-estatico",
    cat: "Solvers", dif: 3,
    q: "La corrección de residuo estático en superposición modal compensa…",
    opts: [
      "El aporte de los modos altos que se truncaron.",
      "El error de redondeo del solver de autovalores.",
      "La reflexión residual de las capas PML del borde.",
      "La energía perdida en las paredes absorbentes.",
    ],
    ans: 0,
    why: "Al truncar la base modal se pierde el aporte de <b>rigidez</b> de los modos de frecuencia alta que quedaron fuera (su cola sí influye en la banda de interés). La corrección de residuo estático añade ese aporte como un término cuasi-estático, mejorando la FRF cerca del tope de la banda sin calcular más modos. Ataca el error de <b>truncamiento modal</b>, no el redondeo, la PML ni la absorción.",
    src: "Fahy, Sound and Structural Vibration · FEM for Acoustics",
  },
  {
    id: "num-cuadratura-singular",
    cat: "Otros métodos", dif: 3,
    q: "En el BEM, las integrales sobre el elemento que contiene el punto fuente…",
    opts: [
      "Son singulares y piden una cuadratura especial.",
      "Se anulan siempre y por eso se pueden ignorar.",
      "Se integran con Gauss estándar y sin cuidado.",
      "No existen si la malla es suficientemente fina.",
    ],
    ans: 0,
    why: "El núcleo (función de Green) se vuelve <b>singular</b> cuando el punto de observación cae sobre el elemento que se integra: hay que usar técnicas especiales (extracción de la singularidad, transformaciones tipo Duffy, integración analítica del término singular). Es una de las dificultades centrales del BEM. La cuadratura de Gauss estándar falla ahí, y refinar la malla no elimina la singularidad.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },
  {
    id: "num-lumping-dispersion",
    cat: "Malla", dif: 3,
    q: "Frente a la masa consistente, la masa concentrada cambia…",
    opts: [
      "El error de dispersión: a veces lo compensa un poco.",
      "Sólo el costo de memoria, casi nunca la precisión.",
      "El número total de modos que tiene la malla usada.",
      "Las condiciones de borde naturales del problema.",
    ],
    ans: 0,
    why: "La masa consistente y la concentrada tienen errores de dispersión de <b>signo opuesto</b>: una adelanta y la otra atrasa la velocidad numérica de la onda. De hecho, un <b>promedio</b> de ambas (mass averaging) puede cancelar buena parte del error de dispersión a orden bajo. O sea que el lumping no sólo abarata: <b>afecta la precisión</b> de propagación. No cambia el número de modos ni las condiciones de borde.",
    src: "Ihlenburg · FEM for Acoustics",
  },
  {
    id: "num-cfl-exacto",
    cat: "Otros métodos", dif: 3,
    q: "En FDTD 3D, el paso de tiempo estable es más chico que en 1D porque…",
    opts: [
      "La onda puede viajar en diagonal por la grilla.",
      "Hay más memoria que gestionar en tres ejes.",
      "El error de redondeo crece con la dimensión.",
      "Las tres direcciones usan distinto Δx cada una.",
    ],
    ans: 0,
    why: "La condición de Courant en 3D es <code>c·Δt ≤ Δx/√3</code> (contra Δx/√2 en 2D y Δx en 1D): el factor <b>√3</b> aparece porque la onda puede propagarse en <b>diagonal</b> por la celda cúbica, recorriendo una distancia mayor por paso. Por eso subir de dimensión obliga a pasos temporales más finos. No es cuestión de memoria, redondeo ni de usar Δx distintos por eje.",
    src: "FEM for Acoustics · Courant, Friedrichs & Lewy (1928)",
  },
  {
    id: "num-hp-adaptividad",
    cat: "Validez", dif: 3,
    q: "La hp-adaptividad refina combinando…",
    opts: [
      "Achicar elementos (h) y subir su orden (p) por zonas.",
      "Sólo el orden p, dejando la malla siempre fija igual.",
      "Dos solvers distintos sobre una misma malla fija.",
      "El paso de tiempo y el tamaño de elemento a la vez.",
    ],
    ans: 0,
    why: "La hp-adaptividad decide, guiada por un estimador de error, <b>dónde</b> refinar y <b>cómo</b>: donde la solución es suave conviene subir el orden p (convergencia exponencial); donde hay singularidades (esquinas), achicar h. Bien hecha da convergencia exponencial incluso con singularidades. Es lo más potente y lo más complejo de implementar. Combina h y p, no p solo ni el paso temporal.",
    src: "Ihlenburg · Babuška & Guo",
  },
  {
    id: "num-verificacion-analitica",
    cat: "Validez", dif: 3,
    q: "Para verificar (no validar) un solver modal conviene compararlo con…",
    opts: [
      "La solución analítica de una caja rígida rectangular.",
      "Una medición de RT60 hecha en una sala real grande.",
      "La opinión de un consultor acústico muy experto.",
      "Otra corrida del mismo solver en otra malla, sin más.",
    ],
    ans: 0,
    why: "La <b>verificación</b> chequea que el código resuelve bien las ecuaciones, y para eso se necesita una <b>respuesta exacta conocida</b>: la caja rectangular rígida tiene modos analíticos (<code>(c/2)·√((nx/Lx)²+…)</code>), ideal para comparar. Coincidir con eso valida el solver, no la física. Comparar con una <b>medición</b> real es <b>validación</b> (otra cosa). Comparar dos mallas sólo muestra convergencia, no corrección.",
    src: "Ihlenburg · Roache, Verification and Validation",
  },
  {
    id: "num-error-cuadratura",
    cat: "Formulación", dif: 3,
    q: "Usar muy pocos puntos de Gauss (subintegrar) las matrices puede…",
    opts: [
      "Volver singular la matriz por rango deficiente.",
      "Mejorar siempre la precisión del resultado.",
      "Aumentar el orden de convergencia del método.",
      "Eliminar el error de dispersión por completo.",
    ],
    ans: 0,
    why: "Si la cuadratura no integra con suficiente exactitud, la matriz de rigidez puede quedar con <b>rango deficiente</b> (singular o casi), admitiendo modos de energía nula espurios — el mecanismo detrás del «hourglassing». Hay que usar el orden de cuadratura adecuado al elemento. Subintegrar a veces alivia el locking, pero como técnica descuidada degrada, no mejora, y no toca el error de dispersión.",
    src: "Ihlenburg · FEM for Acoustics",
  },
  {
    id: "num-nyquist-vs-pollution",
    cat: "Validez", dif: 3,
    q: "Mantener «6 elementos por longitud de onda» a toda frecuencia…",
    opts: [
      "No basta: el error crece igual por el pollution.",
      "Garantiza error constante a cualquier frecuencia.",
      "Sólo importa en problemas estáticos sin ondas.",
      "Elimina la necesidad de verificar convergencia.",
    ],
    ans: 0,
    why: "Fijar los elementos por longitud de onda controla el error de <b>interpolación</b>, pero <b>no</b> el de dispersión (pollution), que se acumula con el número de longitudes de onda recorridas: a igual densidad de malla, el error crece con la frecuencia. Por eso en alta frecuencia hay que refinar más rápido que λ, o subir el orden. Es la lección central de Ihlenburg sobre Helmholtz discreto.",
    src: "Ihlenburg, Finite Element Analysis of Acoustic Scattering",
  },

].map((q) => ({ ...q, area: "numerica" }));
